0xMiden/miden-vm

- assembly/src/v1/parsers/field_ops.rs
- core/src/v1/program/operations.rs
This PR refactors VM instruction set. Specifically, it defines most new instructions (including u32 instructions), but does not implement their execution on the processor.
> Instruction set refactoring

- assembly/src/v1/errors.rs
- assembly/src/v1/tests.rs
- assembly/src/v1/tokens/stream.rs
This PR implements the comment parsing #10 
I have 2 questions:
1. I've left #token and token# as invalid_op errors rather than comment errors. Would you prefer for these to give invalid comment errors?
2. There are quite a few “TODO: add comments” instructions throughout. All of the cases seem to be covered by implementing the parsing in TokenStream, but before removing them I wanted to check if there’s something else you intended in those spots or with this implementation in general
> WIP: implement comment parsing

- processor/src/v1/mod.rs
- processor/src/v1/operations/field_ops.rs
- processor/src/v1/operations/io_ops.rs
- processor/src/v1/operations/mod.rs
- processor/src/v1/operations/stack_ops.rs
- processor/src/v1/operations/sys_ops.rs
- processor/src/v1/operations/u32_ops.rs
- processor/src/v1/stack/mod.rs
- processor/src/v1/tests/mod.rs
- processor/src/v1/trace.rs
This PR refactors processor structure in the following ways:
- `Processor` struct is renamed to `Process` struct
- `execute()` function is added. This function instantiates a new process, executes a script against it, and builds an execution trace from the final state of the process.
> Processor refactoring

- assembly/src/v1/parsers/io_ops.rs
Hi Bobbin,
I added some tests to get my bearings. Please let me know if you prefer unit tests more or less collapsed (i.e. all mem variants in one test or splitting the 2 methods of providing address into their own tests).
Hopefully I'm on the right track here!
> PR: assembly parser io ops tests + parse_mem implementation

- core/src/v1/program/inputs.rs
- processor/src/v1/advice/mod.rs
- processor/src/v1/errors.rs
- processor/src/v1/memory/mod.rs
- processor/src/v1/mod.rs
- processor/src/v1/operations/io_ops.rs
- processor/src/v1/operations/mod.rs
- processor/src/v1/stack/mod.rs
- processor/src/v1/trace.rs
This PR implements handling of advice ops in the processor. The ops are: `read` and `readw`.
Also, as a part of this PR basic structure for `AdviceProvider` struct is implemented.
> Implement processing of advice ops

- assembly/src/v1/parsers/io_ops.rs
I added a few tests to check error cases and couldn't assert_eq the exact errors. I guess this is because the PartialEq trait isn't implemented for AssemblyError, but maybe there's another way around this that I'm not aware of yet..? For the moment, I just asserted that the result gave an error without checking to see which one. Let me know if you have any thoughts on this.
> Implement parsing of pushw and env io operations

- assembly/src/errors.rs
- assembly/src/parsers/io_ops.rs
- assembly/src/parsers/mod.rs
I updated the io tests to do exact error checking and then added some additional validation to check the exact op tokens being passed to the parser functions. Let me know if you don't think that belongs here (maybe it's overkill).
> Implement assembly io advice ops

- assembly/Cargo.toml
- core/Cargo.toml
- processor/Cargo.toml
This PR increments versions of `core`, `assembly`, and `processor` crates to v0.2
> chore: increment crate versions to v0.2

- processor/src/lib.rs
- processor/src/memory/mod.rs
- processor/src/memory/tests.rs
- processor/src/trace.rs
This PR implements execution trace generation for memory accesses (reads and writes). It also introduces a `TraceFragment` struct which will be useful in other contexts.
> Implement memory trace generation

- processor/src/bitwise/mod.rs
- processor/src/bitwise/tests.rs
- processor/src/lib.rs
- processor/src/memory/mod.rs
- processor/src/operations/u32_ops.rs
- processor/src/trace.rs
This PR implements trace generation for `u32` bitwise operations: AND, OR, XOR.
> Implement bitwise op trace generation

- assembly/src/parsers/crypto_ops.rs
- processor/src/operations/crypto_ops.rs
- processor/src/tests/crypto_ops.rs
- processor/src/tests/mod.rs
This PR adds a basic unit test for op formatting validity of parse_mtree, implements parse_mtree, and adds tests of execution in the processor for the assembly ops "mtree.get", "mtree.set", "mtree.cwm".
I wanted to reuse 2 of the helper functions in the processor crypto_ops unit tests but wasn't sure about the best place to put them for use in both places (probably processor/src/tests/mod.rs?). Instead, I have recreated them in the tests/crypto_ops.rs file for now.
> Implement assembly mtree crypto ops

- assembly/src/parsers/field_ops.rs
- processor/Cargo.toml
- processor/src/tests/field_ops.rs
- processor/src/tests/mod.rs
This PR implements the field element comparison operations ```eqw```, ```lt```, ```lte```, ```gt```, ```gte``` and adds unit tests and execution tests in the processor. The cycle cost is higher than I had hoped, so I included the cost for each of the expensive ops in the comments.
The extra cost comes from the need to give precedence to the high bit values when comparisons between the high-bit and low-bit values disagree.
For example, during a less-than check:
- If the low-bit values pass the less-than check, but the high-bit values are greater, then the check should fail. However, if the high-bit values are equal, then the check should pass. In both cases the high-bit less-than check failed, but it leads to 2 different results. 
- Similarly, simply checking LTE for the high-bits is …
> Implement assembly comparison operations for field elements

- core/src/operations/mod.rs
- processor/src/operations/io_ops.rs
- processor/src/operations/mod.rs
This PR adds two new processor operations: `fmpadd` and `fmpupdate` and stubs out methods for their handling in the processor.
The operations are needed for easier management of local procedure variables as discussed in #73
> Free memory pointer operations

- core/src/operations/mod.rs
- processor/src/errors.rs
- processor/src/lib.rs
- processor/src/operations/field_ops.rs
- processor/src/operations/io_ops.rs
- processor/src/operations/mod.rs
- processor/src/operations/sys_ops.rs
- processor/src/stack/mod.rs
- processor/src/system/mod.rs
- processor/src/trace.rs
This PR addresses #83. Specifically, it implements processing of operations which read/write `fmp` register (`fmpadd` and `fmpupdate`). It also encapsulates system registers in a new `System` struct.
> Add fmp register to processor and associated operations

- assembly/src/parsers/io_ops.rs
- assembly/src/parsers/mod.rs
- processor/src/tests/mod.rs
- processor/src/tests/u32_ops.rs
This PR addresses #79 
- Removes all execution failure checks from proptests in the u32_tests in the processor
- Updates all u32 proptests to generate valid random u32 values
> Update u32 proptests in the processor to only test valid u32 values

- processor/src/tests/u32_ops.rs
This PR adds manual and randomized tests in the processor for u32 conditional operations. This includes the following operations:
- ```u32eq```, ```u32eq.b```
- ```u32neq```, ```u32neq.b```
- ```u32lt```, ```u32lt.unsafe```
- ```u32lte```, ```u32lte.unsafe```
- ```u32gt```, ```u32gt.unsafe```
- ```u32gte```, ```u32gte.unsafe```
- ```u32min```, ```u32min.unsafe```
- ```u32max```, ```u32max.unsafe```
Note: the ```u32eq_proptest``` is not changed here because it is updated as part of the proptest PR #89.
> Add processor tests for u32 conditional operations

- assembly/src/parsers/u32_ops.rs
The number of VM cycles has been reduced by 5 due to a small optimization of the algorithm. Essentially, the "Not" and "Or" operations have been replaced by a single "And" operation.
> Optimize u32testw assembly instruction parser

- assembly/src/parsers/u32_ops.rs
- processor/src/tests/u32_ops.rs
As described in https://github.com/maticnetwork/miden/issues/76, fix the parsers `parse_u32shl`, `parse_u32shr`, `parse_u32rotl`, `parse_u32rotr` for shift/rotate ops to allow parameter value of **0 <= b <= 31**, according to the [assembly specs](https://hackmd.io/YDbjUVHTRn64F4LPelC-NA?view#Bitwise-operations). Also, adjusted the tests to this parsers added in https://github.com/maticnetwork/miden/pull/75 to validate the ~new~ enforcing parameter bounds.
> Fix u32 assembly parsers for shift/rotate ops to allow b = 0

- processor/src/tests/u32_ops.rs
This PR adds manual and randomized tests to the processor for the following u32 arithmetic operations:
- u32add
- u32add.b
- u32add.full
- u32add.unsafe
- u32addc
- u32addc.unsafe
- u32sub
- u32sub.b
- u32sub.full
- u32sub.unsafe
- u32mul
- u32mul.b
- u32mul.full
- u32mul.unsafe
- u32madd
- u32madd.unsafe
- u32div
- u32div.b
- u32div.full
- u32div.unsafe
- u32mod
- u32mod.b
- u32mod.unsafe
It includes failing test cases for https://github.com/maticnetwork/miden/issues/94 with a comment linking to the issue above the failing tests.
> Add tests for u32 arithmetic ops to the processor

- processor/src/tests/u32_ops.rs
This PR removes references to fixed issues from the code and replaces custom `get_result()` functions for `shl` and `shr` operations with built-ins.
> Minor cleanup of u32 processor tests

- assembly/src/parsers/crypto_ops.rs
- core/Cargo.toml
- core/src/hasher/mod.rs
- core/src/operations/mod.rs
- processor/src/hasher/mod.rs
- processor/src/operations/crypto_ops.rs
- processor/src/tests/crypto_ops.rs
Resolve the hash operation inconsistency raised in #52.
- update Winterfell winter-crypto dependency version
- update assembly rphash parser for consistency with new RP hash result position
- update hasher functions used for merkle tree ops in the processor
- update comments/docs for consistency with the new version
- update tests for RPPERM (processor), rpperm/rphash(assembly)
> Update Winterfell Rp64_256 version to improve hash op consistency

- assembly/src/parsers/io_ops.rs
- assembly/src/parsers/mod.rs
This PR addresses the first stage of #84 and refactors all assembly i/o operations and tests to the new "what.where" format as outlined in the new [specs](https://hackmd.io/YDbjUVHTRn64F4LPelC-NA#Input--output-operations). It does not update the `push` operation for constants to the new spec, although it does remove `pushw` for constants to update the `pushw` parser to the new format.
Updated ops include:
- all mem ops
- all adv ops
- all env ops
- `pushw` operation for constants removed
- handling for local memory ops is stubbed out
> Refactor asm io ops to what.where format

- assembly/src/parsers/io_ops.rs
- assembly/src/parsers/mod.rs
This PR addresses the second stage of #84 as well as the new mem ops specified in #102 
- changes push handling for decimal/hexadecimal constants to allow multiple values in the format `push.a.b.c...` up to 16 values
- adds new hex parsing to allow multiple hex values to be specified without separators, as long as the total number of specified bytes is a multiple of 8 (e.g. `push.0x0000000000001234000000000000abcd`)
- adds `push.mem`/`push.mem.a` and `pop.mem`/`pop.mem.a` to push and pop single elements from/to memory
- stubs out `push.local.i` and `pop.local.i` to be completed with the rest of the local memory handling in stage 3 of #84
- updates and adds unit tests for all of the above
> Implement new specs for push & pop in asm parser

- processor/src/bitwise/mod.rs
- processor/src/hasher/mod.rs
- processor/src/lib.rs
- processor/src/memory/mod.rs
- processor/src/stack/mod.rs
- processor/src/system/mod.rs
- processor/src/tests/aux_table_trace.rs
- processor/src/tests/mod.rs
- processor/src/trace.rs
This PR implements #114.
- handles stacking of the co-processor traces
- adds basic tests for the stacked trace table
- minor refactors
> Implement stacking of auxiliary traces (hasher, bitwise, memory)

- assembly/src/parsers/crypto_ops.rs
- assembly/src/parsers/field_ops.rs
- assembly/src/parsers/io_ops/adv_ops.rs
- assembly/src/parsers/io_ops/constant_ops.rs
- assembly/src/parsers/io_ops/env_ops.rs
- assembly/src/parsers/io_ops/local_ops.rs
- assembly/src/parsers/io_ops/mem_ops.rs
- assembly/src/parsers/io_ops/mod.rs
- assembly/src/parsers/mod.rs
- processor/src/operations/sys_ops.rs
- processor/src/system/mod.rs
- processor/src/tests/io_ops/env_ops.rs
This PR addresses #118 and #105.
- updates `fmp` max and min values for local memory addressing
- updates unit tests for `fmpadd` and `fmpupdate`
- adds new op `push.env.locaddr.i` to push the absolute address of the local at index `i` onto the stack
- updates unit & integration tests for env io ops
- refactors assembly op validation to a macro for greater flexibility and to reduce repeated code in op parsers
> Update local memory fmp and add asm op for absolute local addr

- assembly/src/parsers/u32_ops.rs
Added a division by 0 check for the u32div.b operation, as well as separate processing of the result of the u32div operation when checking for belonging to the u32 type.
> Incorrect implementation of parse_u32div for u32div and u32div.b operations #94

- processor/src/tests/mod.rs
- processor/src/tests/stdlib/mod.rs
- processor/src/tests/stdlib/u64_mod.rs
- stdlib/asm/math/u256.masm
- stdlib/asm/math/u64.masm
- stdlib/src/asm.rs
This PR adds multiplication procedure to `std::math::u64` module. It also adds simple tests for u64 addition and multiplication.
Related to #131
> Add u64 multiplication procedure to standard library

- processor/Cargo.toml
- processor/src/tests/stdlib/crypto/blake3.rs
- processor/src/tests/stdlib/crypto/mod.rs
- processor/src/tests/stdlib/mod.rs
- stdlib/asm/crypto/hashes/blake3.masm
- stdlib/src/asm.rs
This PR implements BLAKE3 2-to-1 hash function for Miden `stdlib`. I'm using BLAKE3 reference [implementation](https://github.com/BLAKE3-team/BLAKE3/blob/da4c792d8094f35c05c41c9aeb5dfe4aa67ca1ac/reference_impl/reference_impl.rs), along with Miden Assembly [specification](https://hackmd.io/YDbjUVHTRn64F4LPelC-NA#Stack-manipulation), as guide.
> BLAKE3 using Miden Assembly

- assembly/src/parsers/io_ops/mod.rs
- assembly/src/parsers/mod.rs
- core/src/operations/advice.rs
- processor/src/operations/decorators/mod.rs
- processor/src/tests/io_ops/adv_ops.rs
- processor/src/tests/stdlib/u64_mod.rs
- stdlib/asm/math/u64.masm
- stdlib/src/asm.rs
This PR implements division of 64-bit unsigned integers in the standard library. The overall methodology is to compute the actual division outside of the VM, provide the result to the VM via the advice tape, and then to verify that the result is correct within the VM. The tasks include:
Overall, u64 division requires about 50 VM cycles. This can be reduced to 39 cycles once we have `u32assert2` operation as described #132 (compare this with 11 cycles needed for u64 multiplication).
> Implement u64 division in standard library

- processor/src/tests/aux_table_trace.rs
- processor/src/tests/crypto_ops.rs
- processor/src/tests/field_ops.rs
- processor/src/tests/flow_control.rs
- processor/src/tests/io_ops/adv_ops.rs
- processor/src/tests/io_ops/constant_ops.rs
- processor/src/tests/io_ops/env_ops.rs
- processor/src/tests/io_ops/local_ops.rs
- processor/src/tests/io_ops/mem_ops.rs
- processor/src/tests/io_ops/mod.rs
- processor/src/tests/mod.rs
- processor/src/tests/stdlib/mod.rs
- processor/src/tests/stdlib/u64_mod.rs
- processor/src/tests/u32_ops/arithmetic_ops.rs
- processor/src/tests/u32_ops/bitwise_ops.rs
- processor/src/tests/u32_ops/comparison_ops.rs
- processor/src/tests/u32_ops/conversion_ops.rs
- processor/src/tests/u32_ops/mod.rs
This PR refactors the processor integration tests to use macros, making testing patterns more consistent and reducing duplication.
> Refactor processor integration tests

- processor/src/tests/io_ops/local_ops.rs
Since local memory is not guaranteed to be zeros, we no longer want to include this in the tests, so the tests explicitly checking uninitialized reads were removed. However, some tests do still load zeros from uninitialized memory, in the interest of keeping the tests to single operation tests. Inline comments were added in these cases.
> test: remove tests reading from uninitialized local memory

- core/src/inputs/mod.rs
- core/src/lib.rs
- processor/src/errors.rs
- processor/src/lib.rs
- processor/src/operations/crypto_ops.rs
- processor/src/operations/decorators/debug_tests.rs
- processor/src/operations/decorators/mod.rs
- processor/src/operations/field_ops.rs
- processor/src/operations/io_ops.rs
- processor/src/operations/stack_ops.rs
- processor/src/operations/sys_ops.rs
- processor/src/operations/u32_ops.rs
- processor/src/stack/mod.rs
- processor/src/tests/io_ops/env_ops.rs
- processor/src/tests/io_ops/local_ops.rs
- processor/src/tests/io_ops/mem_ops.rs
- processor/src/tests/io_ops/mod.rs
- processor/src/tests/mod.rs
- processor/src/tests/stdlib/crypto/blake3.rs
- processor/src/trace.rs
This PR addresses #65 by enforcing a minimum stack depth of 16 and removing the concept of stack underflow.
- updates the initial stack depth & left shift handling
- removes stack depth checks from all operations in the processor
- removes the StackUnderflow ExecutionError
- resolves processor unit test errors introduced by the change
- resolves processor integration test errors introduced by the change and removes irrelevant tests
- updates the docs to reflect the min stack depth and StackUnderflow changes & their effect on processor operation Errors
> Implement minimum stack depth

- processor/src/tests/stdlib/math/u64_mod.rs
- stdlib/asm/math/u64.masm
- stdlib/src/asm.rs
This PR implements u64 comparison operations in the standard library. These include: `lt`, `lte`, `gt`, `gte`. Other comparison procedures are left for future PRs.
This PR also fixes a couple of issues:
- Changes `u32madd` to `u32madd.unsafe` and `u32addc` to `u32addc.unsafe` in `u64` module. This is OK because so far we have only unsafe versions of operations implemented.
- Adds a check to `u64::div_unsafe` to make sure that the remainder provided by the prover is less than the divisor. Without this check, the prover could have cheated. For example, the result of 9/2 could have been set to: quotient = 3, remainder = 3, and the check 2 * 3 + 3 = 9 would have been satisfied.
Overall, the cost of u64 division is now 67 cycles (vs. 11 cycles for multiplication). So, it might be worth …
> Add u64 comparisons and other fixes

- core/src/lib.rs
- processor/src/lib.rs
- processor/src/stack/mod.rs
- processor/src/stack/tests.rs
- processor/src/stack/trace.rs
- processor/src/trace.rs
This PR addresses #65 and updates the stack trace to match the constraint requirement [specs](https://hackmd.io/WhJ7fWXAQRasmS7ebqAKzg) for the minimum stack depth.
- refactors the overflow handling into a table to match the spec
- adds the bookkeeping and helper columns to the stack trace
- updates the documentation in the stack module
- adds simple tests for the stack and helper states after initialization, left shift, and right shift
> Add bookkeeping & helper columns to stack trace

- processor/src/operations/field_ops.rs
- processor/src/operations/io_ops.rs
- processor/src/operations/stack_ops.rs
- processor/src/stack/mod.rs
- processor/src/stack/overflow.rs
- processor/src/stack/tests.rs
- processor/src/stack/trace.rs
This PR refactors processor stack modules to break out overflow table into a separate stack. This approach aligns better with the work being done in #128 
Also, I've used this opportunity to change `step` to `clk` in all stack-related modules. I think having two different names for this is a bit confusing, and between the two, I prefer `clk`. But I'm open to other suggestions.
> Stack refactoring in the processor

- processor/src/lib.rs
- processor/src/operations/u32_ops.rs
- processor/src/trace.rs
This PR addresses the first half of #143 by adding the values that require range checks during u32 operations to the RangeChecker, according to the [specs for u32 operations](https://hackmd.io/NC-yRmmtRQSvToTHb96e8Q#Bitwise-AND)
> Add range checks for u32 operations

- core/src/lib.rs
- processor/src/lib.rs
- processor/src/tests/aux_table_trace.rs
- processor/src/trace.rs
This PR closes #143 by adding the trace generated by the RangeChecker to the overall execution trace.
> Integrate the range check trace with the VM execution trace

- miden/tests/integration/stdlib/math/u64_mod.rs
- stdlib/asm/math/u64.masm
- stdlib/src/asm.rs
Due to the great similarity of the division operation and the modulo operation, the division operation code was taken as the basis, in which the value remaining on the stack was replaced. Now there remains not a quotient, but the remainder of the division.
> Add u64 unsafe modulo operation

- .github/workflows/book.yml
Add github action that automatically pushes doc changes into github page on both pushes to next and master branch
Example running
https://github.com/tnachen/miden/runs/5749281007?check_suite_focus=true
> Add mdbook github action

- air/src/lib.rs
- air/src/range.rs
- air/src/utils.rs
- miden/tests/integration/operations/u32_ops/bitwise_ops.rs
This is a simple initial implementation of the range checker constraints, excluding the constraints for the running product columns used for permutation checks.
There are no tests yet, since I expect that we'll design a system for testing constraints in a separate issue. Additionally, we will likely need to include the number of range checker transition constraints in the ProcessorAir for use when enforcing constraints of other components, but I left this to be done alongside future constraints, since the overall handling of constraints will likely change.
> feat: add range checker constraints (excluding permutation checks)

- miden/tests/integration/stdlib/math/u64_mod.rs
- stdlib/asm/math/u64.masm
- stdlib/src/asm.rs
1. Implementation of safe versions of u64 `add`, `sub`, `mul`, `div`, `mod`, `eq`, `eqz`, `lt`, `lte`, `gt`, `gte`. 
2. Renaming of arithmetic operations according to the Rust convention:
unsafe -> wrapping
safe -> checked
3. Adding an overflowing version for `add`, `sub` and `mul` procedures.
4. implementation of `divmod` procedure.
> u64 stdlib module improvements and refactoring

- air/Cargo.toml
- air/src/lib.rs
- air/src/range.rs
- assembly/Cargo.toml
- assembly/src/context/mod.rs
- assembly/src/lib.rs
- assembly/src/parsers/blocks.rs
- core/Cargo.toml
- core/src/utils/mod.rs
- examples/Cargo.toml
- miden/Cargo.toml
- miden/src/lib.rs
- processor/Cargo.toml
- processor/src/advice/mod.rs
- processor/src/memory/mod.rs
- processor/src/range/mod.rs
- processor/src/stack/overflow.rs
- processor/src/trace.rs
- stdlib/Cargo.toml
- stdlib/src/lib.rs
- verifier/Cargo.toml
This PR updated Winterfell dependencies to v0.4. This includes refactoring of the `ExecutionTrace` struct to comply with the new `Trace` interface and bumping up min Rust version to 1.6.
> Update Winterfell dependencies to v0.4

- miden/tests/integration/operations/stack_ops.rs
Addresses issue #162 
Adds tests for the following stack operations:
> Add integration tests for stack operations

- air/src/lib.rs
- core/src/hasher/mod.rs
- core/src/utils/mod.rs
- processor/src/aux_table/mod.rs
- processor/src/aux_table/tests.rs
- processor/src/bitwise/mod.rs
- processor/src/hasher/mod.rs
- processor/src/lib.rs
- processor/src/memory/mod.rs
- processor/src/range/mod.rs
- processor/src/range/tests.rs
- processor/src/stack/mod.rs
- processor/src/stack/trace.rs
- processor/src/system/mod.rs
- processor/src/trace.rs
This PR implements injection of random values into the last row of execution trace. This ensures that constraint degrees are always stable (regardless of the executed program). The PR also refactors how trace components are merged together into a single execution trace matrix.
One unfortunate consequence of this change is that using random values in tests slows them down quite a bit. In my benchmarking tests are now taking roughly twice as long to run (this is almost exclusively due to integration tests).
In release mode, there is no observable slowdown.
> Random element injection into last trace row

- docs/src/SUMMARY.md
- docs/src/design.md
- docs/src/design/aux_table/bitwise.md
- docs/src/design/aux_table/hasher.md
- docs/src/design/aux_table/main.md
- docs/src/design/aux_table/memory.md
- docs/src/design/aux_table/pow2.md
- docs/src/design/main.md
- docs/src/design/range.md
This PR adds documentation of the operation & constraint designs for processors where constraints have been implemented or recently updated. This includes the following processors:
- Range Checker
- Auxiliary Table (placeholder - not fully implemented yet & may require edits)
- Hash Processor (placeholder - not implemented yet & may require edits)
- Bitwise Processor
- Power of Two Processor
- Memory Processor
During this process, the Bitwise Processor documentation was updated to match the existing implementation and the Memory Processor documentation was also updated with small fixes.
> Add processor design documentation to mdbook

- miden/tests/integration/stdlib/mod.rs
- miden/tests/integration/stdlib/sys.rs
- stdlib/asm/sys.masm
- stdlib/src/asm.rs
Partly addresses #134. 
Add a procedure to stdlib to remove elements in the stack overflow table to clean up at the end of program completion.
It's kept separate for now and not added to the assembler to include to all programs as suggested by @bobbinth.
> Add procedure to clean up stack overflow table

- assembly/src/parsers/u32_ops.rs
- core/src/operations/mod.rs
- miden/tests/integration/operations/u32_ops/conversion_ops.rs
This PR partly addresses #132. In the first phase u32assert2 has been added to the assembly instruction.
> u32assert2 assembly instruction

- air/Cargo.toml
- air/src/aux_table/bitwise.rs
- air/src/aux_table/bitwise_pow2/bitwise.rs
- air/src/aux_table/bitwise_pow2/mod.rs
- air/src/aux_table/bitwise_pow2/pow2.rs
- air/src/aux_table/bitwise_pow2/tests.rs
- air/src/aux_table/mod.rs
- air/src/lib.rs
- core/src/bitwise/mod.rs
- core/src/lib.rs
- docs/src/design/aux_table/pow2.md
- examples/src/lib.rs
- miden/tests/integration/air/bitwise.rs
- miden/tests/integration/air/mod.rs
- miden/tests/integration/helpers.rs
- miden/tests/integration/main.rs
- processor/src/aux_table/tests.rs
- processor/src/bitwise/mod.rs
This PR partially addresses #179, implementing AIR constraints for the bitwise and power of two operations in a shared co-processor inside the auxiliary table.
It also adds:
- a new test helper for generating & verifying a proof of a test's execution
- some simple integration tests for the auxiliary table's AIR constraints for the bitwise and pow2 operations.
- randomized unit tests for bitwise and pow2 air constraints validating that constraints evaluate to 0 for correct traces
It does not add failure tests for air constraints to test for bad trace inputs which should cause constraints to fail or to verify that all constraints are present and correctly applied. These should be addressed in a separate PR, but can use the same approach presented here of testing by frame
> Implement AIR constraints for bitwise & power of two operations

- docs/src/design/aux_table/main.md
This is a rough overview of the current design of the Auxiliary Table's execution trace which outlines the considerations of the current implementation and notes some other options for the future.
Once v0.2 is finished and the design is more settled this should be revisited and updated.
> docs: add initial version of aux table mdbook docs

- air/Cargo.toml
- air/src/aux_table/memory/mod.rs
- air/src/aux_table/memory/tests.rs
- air/src/aux_table/mod.rs
- docs/src/design/aux_table/memory.md
- miden/tests/integration/air/memory.rs
- miden/tests/integration/air/mod.rs
- processor/src/aux_table/mod.rs
- processor/src/aux_table/tests.rs
This PR addresses the following for the Memory co-processor's AIR constraints:
- Adds simple integration tests to prove & verify each of the primary memory operations (local reads/writes are excluded. These should be tested with a more complex script that includes context changes.)
- Adds basic unit tests for the AIR constraints to test transitions between states (context change, address change, or clock change). These tests provide correct states and look for passing constraints. Tests of failure in incorrect states or missing constraints are left for another PR.
- Fixes an error with the constraints.
- Updates the mdbook docs to reflect the constraint changes.
This PR is waiting for #194 to be merged, as there is a shared test helper in the integration tests which is first added there.
> Add tests & fix errors in AIR constraints for Memory co-processor

- air/src/aux_table/bitwise_pow2/bitwise.rs
- air/src/aux_table/bitwise_pow2/tests.rs
> air bitwise operation bug poc test

- miden/tests/integration/operations/field_ops.rs
From issue: #166 
Tests for boolean and assertion field operations need to be added to the [integration tests](https://github.com/maticnetwork/miden/blob/next/miden/tests/integration/operations/field_ops.rs).
Tests should follow the existing pattern with the following tests added for each of the boolean field operations and the assert operation:
a test of simple success cases
a test with applicable failure cases, if there are any (compilation and/or execution failure)
a proptest of the expected success case (removed as it's not necessary)
The [u32 bitwise tests](https://github.com/maticnetwork/miden/blob/next/miden/tests/integration/operations/u32_ops/bitwise_ops.rs) provide an example.
Specs for the operations are in the [Miden Assembly note](https://hackmd.io/YDbjUVHTRn64F4LPelC-NA). …
> add integration tests for boolean and assertion field operations

- assembly/src/parsers/u32_ops.rs
- core/src/operations/mod.rs
- docs/src/user_docs/assembly/u32_operations.md
- miden/tests/integration/operations/u32_ops/conversion_ops.rs
- processor/src/operations/mod.rs
- processor/src/operations/u32_ops.rs
Partly address #132 
Introduced `u32assert2` opcode to the core VM instruction set. It will reduce down the total VM cycle of checking whether top 2 values in the stack is u32 to 1 from atleast 6.
> introduce u32assert2 opcode to VM instruction

- air/src/aux_table/bitwise_pow2/bitwise/mod.rs
- air/src/aux_table/bitwise_pow2/bitwise/tests.rs
- air/src/aux_table/bitwise_pow2/mod.rs
- air/src/aux_table/bitwise_pow2/pow2/mod.rs
- air/src/aux_table/bitwise_pow2/pow2/tests.rs
- air/src/aux_table/memory/mod.rs
- air/src/aux_table/memory/tests.rs
- air/src/aux_table/mod.rs
- air/src/range.rs
- core/src/bitwise/mod.rs
This PR introduces several minor refactors within the air crate, especially the auxiliary table module and tests. The changes address the following:
- make the testing approach consistent in the different co-processors
- makes the constraints more explicit, to make it clearer to understand and minimize the likelihood of errors (reducing agg_constraint usage unless a single constraint is being aggregated)
- fixes an incorrect set of constraints in the bitwise processor
- inlines the methods in the extension frames to improve performance
> refactor: air crate for consistency and to reduce chance of errors

- assembly/src/parsers/u32_ops.rs
- miden/tests/integration/operations/u32_ops/arithmetic_ops.rs
- miden/tests/integration/operations/u32_ops/bitwise_ops.rs
- miden/tests/integration/operations/u32_ops/comparison_ops.rs
- miden/tests/integration/operations/u32_ops/conversion_ops.rs
- miden/tests/integration/operations/u32_ops/mod.rs
- miden/tests/integration/stdlib/math/u64_mod.rs
Change the `u32assert` assembly instruction from `U32SPLIT EQZ ASSERT`
to `PAD U32ASSERT2 DROP` to give the better error message `NotU32Value`
instead of `FailedAssertion`. Update associated tests.
Closes #213
>  (fix)[assembly]: make the u32assert error clearer

- air/src/aux_table/bitwise_pow2/mod.rs
- air/src/aux_table/hasher/mod.rs
- air/src/aux_table/hasher/tests.rs
- air/src/aux_table/mod.rs
- air/src/lib.rs
- air/src/utils.rs
- core/src/hasher/mod.rs
- docs/src/design/aux_table/hasher.md
- miden/tests/integration/air/hasher.rs
- miden/tests/integration/air/mod.rs
- miden/tests/integration/helpers/crypto.rs
- miden/tests/integration/helpers/mod.rs
- miden/tests/integration/operations/crypto_ops.rs
- processor/src/aux_table/tests.rs
- processor/src/hasher/mod.rs
This PR closes #179 , finishing all AIR constraints for the auxiliary table.
It contains the following changes:
- adds the original design docs for the hash processor
- updates the hash processor design with some required constraint changes
- implements the air constraints
- adds integration tests and basic unit test for the hash processor's AIR constraints
> Implement hash processor AIR constraints

- air/src/aux_table/hasher/mod.rs
- assembly/src/errors.rs
- core/src/decoder/mod.rs
- core/src/hasher/mod.rs
- core/src/lib.rs
- core/src/operations/advice.rs
- core/src/operations/debug.rs
- core/src/operations/mod.rs
- core/src/utils/mod.rs
- processor/src/debug.rs
- processor/src/decoder/mod.rs
- processor/src/decoder/tests.rs
- processor/src/decoder/trace.rs
- processor/src/hasher/mod.rs
- processor/src/hasher/tests.rs
- processor/src/hasher/trace.rs
- processor/src/lib.rs
- processor/src/trace.rs
This PR implements decoder trace generation and related changes. This includes:
> Decoder trace generation

- air/src/aux_table/bitwise_pow2/bitwise/mod.rs
- air/src/aux_table/bitwise_pow2/bitwise/tests.rs
- air/src/aux_table/bitwise_pow2/mod.rs
- air/src/aux_table/bitwise_pow2/tests.rs
- docs/src/design/aux_table/main.md
This PR address #206.
New constraints have been added to bitwise_pow2 aux_table to assert that the selector values remain same throughout the cycle.
> feat(air): add new constraint to bitwise_pow2 aux_table 

- air/src/lib.rs
- air/src/range.rs
- core/src/lib.rs
- core/src/range.rs
- docs/src/design/range.md
- miden/tests/integration/air/mod.rs
- miden/tests/integration/air/range.rs
- processor/src/aux_table/tests.rs
- processor/src/decoder/tests.rs
- processor/src/lib.rs
- processor/src/range/mod.rs
- processor/src/range/tests.rs
- processor/src/trace/mod.rs
- processor/src/trace/range.rs
- processor/src/trace/range/mod.rs
- processor/src/trace/range/tests.rs
This PR adds handling of auxiliary trace segments to the ExecutionTrace and the ProcessorAir, and implements the range checker's first running product column `p0` as described in the [docs](https://maticnetwork.github.io/miden/design/range.html).
- add range checker integration tests
- refactor range checker constants
- add auxiliary segment handling to the execution trace
- implement the execution trace for the range checker's running product column `p0`
- add constraint handling for auxiliary columns + constraints for running product column `p0`
- add unit test for the execution trace of the range checker's running product column `p0`
> Implement running product column `p0` in the range checker

- air/src/range.rs
- processor/src/trace/mod.rs
- processor/src/trace/range/mod.rs
- processor/src/trace/range/tests.rs
This PR adds the execution trace for the range checker's auxiliary column `p1`, as well as transition AIR constraints and one of the two required boundary assertions.
> Implement running product column `p1` in the range checker

- air/src/aux_table/bitwise_pow2/mod.rs
- core/src/bitwise/mod.rs
- core/src/operations/mod.rs
- processor/src/aux_table/tests.rs
- processor/src/bitwise/mod.rs
- processor/src/bitwise/tests.rs
- processor/src/decoder/mod.rs
- processor/src/decoder/tests.rs
- processor/src/decoder/trace.rs
- processor/src/operations/mod.rs
- processor/src/operations/u32_ops.rs
- processor/src/trace/range/tests.rs
This PR updates the u32 op executors so that they now set helper registers in the decoder trace with the hint values required for their constraints. As part of this, the following small changes were made:
- fixes a bug in the u32assert2 operation which resulted in 4 extra unnecessary range checks
- refactor the aux_table unit tests so they still pass with the new changes
- update the code & remove the inline TODO that was waiting for the aux table unit test refactor
- add unit tests for the new helper method that sets the helper columns in the decoder trace
- refactors the u32 executor unit tests and the range checker auxiliary column execution trace unit tests, adding a new dummy process for testing with a dummy decoder containing one trace row
> Add u32 operation hint values to the decoder trace

- miden/tests/integration/exec_iters.rs
- processor/src/debug.rs
- processor/src/decoder/mod.rs
- processor/src/lib.rs
Addresses #235.
Adds an `operations` vector to `Decoder` struct and use it to track operation at each VmState. This vector is only populated when programs are executed via `execute_iter()` function.
> feat(processor): add operation to VmState

- assembly/src/parsers/crypto_ops.rs
- assembly/src/parsers/stack_ops.rs
- core/src/operations/mod.rs
- processor/src/operations/mod.rs
- processor/src/operations/stack_ops.rs
1. Native operations `SwapDW`, `MovUp8` and `MovDn8` were added.
2. Native operations `MovUp9`, `MovUp11`, `MovUp13`, `MovUp15`, `MovDn9`, `MovDn11`, `MovDn13`, and `MovDn15` were removed.
3. `movup.n` and `movdn.n` operations for n > 8 were emulated.
> Assembly instruction rationalization

- core/src/decoder/mod.rs
- core/src/lib.rs
- core/src/program/blocks/mod.rs
- core/src/program/blocks/span_block.rs
- core/src/program/mod.rs
- examples/src/lib.rs
- examples/src/main.rs
- miden/tests/integration/helpers/mod.rs
- processor/src/decoder/mod.rs
- processor/src/decoder/tests.rs
- processor/src/decoder/trace.rs
- processor/src/hasher/mod.rs
- processor/src/lib.rs
- processor/src/trace/mod.rs
- processor/src/trace/range/tests.rs
This PR adds op batch flags to the decoder trace and makes a coupe of other small updates:
> Add op batch flags to decoder trace

- assembly/src/parsers/crypto_ops.rs
- assembly/src/parsers/io_ops/local_ops.rs
- assembly/src/parsers/io_ops/mem_ops.rs
- assembly/src/tests.rs
- core/src/operations/mod.rs
- miden/tests/integration/exec_iters.rs
- processor/src/aux_table/tests.rs
- processor/src/memory/mod.rs
- processor/src/operations/io_ops.rs
- processor/src/operations/mod.rs
`MLOAD` and `MSTORE` instructions were introduced to work with individual elements. Using them, the `push.mem` and `pop.mem` operations were optimized.
> Introduction of MLOAD and MSTORE instructions

- air/src/aux_table/mod.rs
- core/src/aux_table.rs
- core/src/lib.rs
- docs/src/design/aux_table/main.md
- miden/tests/integration/exec_iters.rs
- miden/tests/integration/operations/u32_ops/conversion_ops.rs
- miden/tests/integration/stdlib/crypto/blake3.rs
- miden/tests/integration/stdlib/crypto/keccak256.rs
- miden/tests/integration/stdlib/crypto/sha256.rs
- processor/src/aux_table/tests.rs
- processor/src/bitwise/mod.rs
- processor/src/decoder/tests.rs
- processor/src/decoder/trace.rs
- processor/src/hasher/tests.rs
- processor/src/lib.rs
- processor/src/memory/mod.rs
- processor/src/memory/tests.rs
- processor/src/operations/u32_ops.rs
- processor/src/range/tests.rs
- processor/src/stack/trace.rs
- processor/src/trace/decoder/tests.rs
- processor/src/trace/utils.rs
- processor/src/utils.rs
This PR groups together a few small cleanup/refactor tasks that came up while working on adding the memory range checks.
- fixes an error in the mdbook docs
- adds utils for splitting u32 to u16, since this was implemented in different ways in different processors. This also adds a u32 debug assertion for the values before splitting them.
- fixes a decoder test that started failing after the u32 debug assertion was added above
- moves some aux table co-processor constants to core
- creates a util helper function for getting the length of any trace in column-major form
- fixes clippy warnings in tests (these aren't checked during the PR run)
> Minor cleanup: small refactors, clippy warnings, mdbook fix

- core/src/decoder/mod.rs
- miden/tests/integration/air/memory.rs
- processor/src/operations/io_ops.rs
- processor/src/trace/mod.rs
Filling in helper registers for `MLoad`, `MLoadW`, `MStore` and `MStoreW` memory operations.
> Filling in helper registers for memory operations

- air/src/aux_table/memory/mod.rs
- air/src/aux_table/mod.rs
- core/src/aux_table/memory.rs
- core/src/aux_table/mod.rs
- processor/src/aux_table/mod.rs
- processor/src/aux_table/tests.rs
- processor/src/lib.rs
- processor/src/memory/mod.rs
- processor/src/memory/tests.rs
- processor/src/range/mod.rs
- processor/src/trace/mod.rs
This PR reorders the auxiliary table, which is required by #286 which implements range checker `p1` and `q` auxiliary columns. For every row in the memory trace, the value of `p1` changes in the next row, which means that the memory trace rows cannot be placed at the end of the execution trace.
Updating the documentation for the auxiliary table is not addressed here. I propose updating documentation for the auxiliary table along with other changes required by #286 once it is finalized and merged.
> Swap order of memory and padding in the auxiliary table execution trace

- core/src/lib.rs
- docs/src/design/aux_table/memory.md
- processor/src/aux_table/mod.rs
- processor/src/aux_table_bus/aux_trace.rs
- processor/src/aux_table_bus/mod.rs
- processor/src/lib.rs
- processor/src/memory/mod.rs
- processor/src/memory/tests.rs
- processor/src/operations/io_ops.rs
- processor/src/range/mod.rs
- processor/src/range/tests.rs
- processor/src/trace/mod.rs
- processor/src/trace/tests/aux_table.rs
- processor/src/trace/tests/mod.rs
This PR creates the b_aux auxiliary trace bus column for the aux table and adds memory lookups (hasher and bitwise lookups are left for a future PR). 
It includes the following changes:
- `AuxTableBus` component is created and added to the `Process` struct, with memory lookups included from the stack and the Memory processor
- Memory unit tests are updated to include ensuring lookups are provided correctly
- `b_aux` auxiliary trace column execution trace column is built
- unit test for the `b_aux` column for memory is added
- memory design documentation is corrected (constraint error) and updated (notation changes)
Note: I haven't included the Memory selector in the `to_value` function yet, but this can be added when other co-processors are handled
> Create AuxTableBus and build b_aux auxiliary trace column

- assembly/src/parsers/field_ops.rs
- assembly/src/parsers/u32_ops.rs
- miden/tests/integration/operations/field_ops.rs
This PR address a part of first part of #200.
- The pow2 safe mode doesn't check if the input value to which we want to raise 2 to is u32 or not. The PR addresses this.
- Add handling of failures test for cases when the input value is greater than u32 max.
> Pow2 safe mode fix

- assembly/src/parsers/io_ops/adv_ops.rs
- assembly/src/parsers/io_ops/env_ops.rs
- assembly/src/parsers/io_ops/local_ops.rs
- assembly/src/parsers/io_ops/mod.rs
- assembly/src/parsers/mod.rs
- assembly/src/parsers/u32_ops.rs
- miden/tests/integration/air/range.rs
- miden/tests/integration/operations/u32_ops/arithmetic_ops.rs
- stdlib/asm/crypto/hashes/blake3.masm
- stdlib/asm/crypto/hashes/sha256.masm
- stdlib/asm/math/u256.masm
- stdlib/asm/math/u64.masm
- stdlib/src/asm.rs
Refactoring of the `u32add`, `u32sub`, `u32mul`, `u32add3` and `u32madd` operations to match stdlib underscoring style.
> u32 addition, subtraction and multiplication operations refactoring

- assembly/src/parsers/mod.rs
- assembly/src/parsers/u32_ops.rs
- miden/tests/integration/operations/u32_ops/arithmetic_ops.rs
- stdlib/asm/math/u64.masm
- stdlib/src/asm.rs
Refactoring of the `u32div` and `u32mod` operations to match stdlib underscoring style.
> U32 div, mod and divmod operations refactoring

- assembly/src/parsers/mod.rs
- assembly/src/parsers/u32_ops.rs
- miden/tests/integration/air/chiplets/bitwise.rs
- miden/tests/integration/air/chiplets/mod.rs
- miden/tests/integration/operations/u32_ops/bitwise_ops.rs
- miden/tests/integration/operations/u32_ops/comparison_ops.rs
- stdlib/asm/crypto/hashes/blake3.masm
- stdlib/asm/crypto/hashes/keccak256.masm
- stdlib/asm/crypto/hashes/sha256.masm
- stdlib/asm/math/u256.masm
- stdlib/asm/math/u64.masm
- stdlib/src/asm.rs
Refactoring of the 
- `u32and`
- `u32or`
- `u32xor`
- `u32not`
- `u32shl`
- `u32shr`
- `u32rotl`
- `u32rotr`
- `u32lt`
- `u32lte`
- `u32gt`
- `u32gte`
- `u32min`
- `u32max`
operations to match stdlib underscoring style.
> Bitwise and comparison ops refactoring

- assembly/src/parsers/field_ops.rs
- assembly/src/parsers/mod.rs
- assembly/src/parsers/u32_ops.rs
- docs/src/user_docs/assembly/field_operations.md
- docs/src/user_docs/assembly/u32_operations.md
- miden/tests/integration/air/chiplets/bitwise.rs
- miden/tests/integration/air/chiplets/mod.rs
- miden/tests/integration/operations/field_ops.rs
- miden/tests/integration/operations/u32_ops/arithmetic_ops.rs
- miden/tests/integration/operations/u32_ops/bitwise_ops.rs
- miden/tests/integration/operations/u32_ops/comparison_ops.rs
- miden/tests/integration/operations/u32_ops/mod.rs
- stdlib/asm/crypto/hashes/blake3.masm
- stdlib/asm/math/u256.masm
- stdlib/asm/math/u64.masm
- stdlib/src/asm.rs
This PR updated assembly documentation for u32 operation. It also includes four small refactorings:
* Renamed `u32unchecked_add3` to `u32overflowing_add3`.
* Renamed `u32unchecked_madd` to `u32overflowing_madd`.
* Removed `u32overflowing_shl` and `u32overflowing_shr` procedures.
* Refactored `pow2` instruction to have two variants: `checked_pow2` and `unchecked_pow2`.
> Update u32 operation docs

- assembly/src/parsers/crypto_ops.rs
- assembly/src/parsers/field_ops.rs
- core/src/operations/mod.rs
- miden/tests/integration/operations/field_ops.rs
- processor/src/operations/field_ops.rs
- processor/src/operations/mod.rs
- processor/src/stack/mod.rs
This PR addresses https://github.com/maticnetwork/miden/issues/320.
- Removed `EQW` instruction from the VM.
- Emulated `EQW` operation using other VM instruction in the assembly.
- Updated the docs/cycle count of the impacted operations.
> Remove `EQW` vm  instruction

- stdlib/asm/crypto/hashes/blake3.masm
- stdlib/src/asm.rs
This PR uses newly introduced `u32unchecked_rotr.*`, which is faster compared to its checked counterpart --- it improves performance of Blake3 2-to-1 hashing by ~12.41%.
At commit 05bee21 : 5487
At commit 8e9b640 : 4806 [ **latest** ]
> Use faster u32 instructions in BLAKE3 2-to-1 hashing

- air/src/chiplets/bitwise/mod.rs
- air/src/chiplets/bitwise/tests.rs
- air/src/chiplets/mod.rs
- core/src/chiplets/bitwise.rs
- core/src/chiplets/mod.rs
- core/src/lib.rs
- processor/src/chiplets/bitwise/mod.rs
- processor/src/chiplets/bitwise/tests.rs
- processor/src/chiplets/tests.rs
This PR addresses some issues with the modules related to the bitwise chiplet and its tests.
- fixes an error swapping the indices of prev_output and output columns
- minor refactor of consts for consistency (prefix name with `BITWISE_` when indexing globally)
- updates bitwise unit tests in the processor to use constants (this would have caught the error)
- refactors the air unit tests to simplify and reduce the code, now that the prev_output column has been added
- removes an unnecessary unit test from the air tests (irrelevant because output is now aggregated differently)
- adds verification of the previous column to the unit tests of the bitwise execution trace generation in the processor
> Fix bitwise chiplet error & improve bitwise tests

- core/src/chiplets/bitwise.rs
- core/src/chiplets/hasher.rs
- core/src/chiplets/memory.rs
- processor/src/chiplets/bitwise/mod.rs
- processor/src/chiplets/bitwise/tests.rs
- processor/src/chiplets/bus/mod.rs
- processor/src/chiplets/memory/mod.rs
- processor/src/chiplets/mod.rs
- processor/src/trace/tests/chiplets.rs
This PR adds bitwise operations to the chiplets bus.
> Add bitwise operations to the chiplets bus column

- core/src/decoder/mod.rs
- core/src/lib.rs
- core/src/operations/mod.rs
- docs/src/design/chiplets/hasher.md
- docs/src/design/decoder/constraints.md
- docs/src/design/main.md
- docs/src/design/stack/crypto_ops.md
- docs/src/design/stack/field_ops.md
- docs/src/design/stack/io_ops.md
- docs/src/design/stack/op_constraints.md
- docs/src/design/stack/stack_ops.md
- docs/src/design/stack/system_ops.md
- docs/src/design/stack/u32_ops.md
- processor/src/decoder/mod.rs
- processor/src/decoder/tests.rs
- processor/src/decoder/trace.rs
This PR assigns real opcode values (as described in #203) to all operations. It also adds one more column to the decoder to reduce degree of operation flags for high-degree operations (as discussed in the same issue).
> Assign real opcodes to all operations

- air/src/chiplets/hasher/mod.rs
- air/src/chiplets/hasher/tests.rs
- air/src/chiplets/mod.rs
- air/src/lib.rs
- assembly/src/parsers/io_ops/mod.rs
- core/src/chiplets/mod.rs
- core/src/inputs/mod.rs
- core/src/lib.rs
- core/src/program/blocks/span_block.rs
- core/src/program/mod.rs
- miden/tests/integration/operations/crypto_ops.rs
- processor/src/chiplets/hasher/mod.rs
- processor/src/chiplets/hasher/tests.rs
- processor/src/chiplets/hasher/trace.rs
- processor/src/chiplets/tests.rs
- processor/src/decoder/mod.rs
- processor/src/lib.rs
- processor/src/operations/crypto_ops.rs
- processor/src/trace/mod.rs
- processor/src/trace/tests/chiplets/bitwise.rs
- processor/src/trace/tests/chiplets/memory.rs
- processor/src/trace/tests/chiplets/mod.rs
- processor/src/trace/tests/hasher.rs
- processor/src/trace/tests/range.rs
- verifier/src/lib.rs
This PR is a precursor to the PR that will complete the inclusion of the hasher lookups in the b_chip bus column. It includes the following refactors:
- removes the re-export of the hasher module at the top level of `core` and switches imports to go through core::chiplets::hasher (rather than core::hasher)
- moves the index constants for identifying hasher columns within the main trace from `air` to `core`
- moves b_chip tests for memory and bitwise lookups into their own files
> Refactor hash chiplet constants and chiplets trace tests module

- core/src/inputs/mod.rs
- docs/src/intro/overview.md
- docs/src/user_docs/main.md
- miden/tests/integration/main.rs
- verifier/src/lib.rs
This PR fixes a bug reported in #342 - specifically, the one where output ordering had to be reversed the the verifier to accept the proof. It also adds documentation to clarify expected ordering of inputs and outputs, as well as a note on stack depth restrictions.
> Stack input / output ordering fix

- core/src/chiplets/hasher.rs
- processor/src/chiplets/bitwise/mod.rs
- processor/src/chiplets/bitwise/tests.rs
- processor/src/chiplets/bus/aux_trace.rs
- processor/src/chiplets/bus/mod.rs
- processor/src/chiplets/hasher/lookups.rs
- processor/src/chiplets/hasher/mod.rs
- processor/src/chiplets/hasher/tests.rs
- processor/src/chiplets/hasher/trace.rs
- processor/src/chiplets/memory/mod.rs
- processor/src/chiplets/memory/tests.rs
- processor/src/chiplets/mod.rs
- processor/src/decoder/mod.rs
- processor/src/lib.rs
- processor/src/trace/decoder/tests.rs
- processor/src/trace/tests/chiplets/bitwise.rs
- processor/src/trace/tests/chiplets/hasher.rs
- processor/src/trace/tests/chiplets/memory.rs
- processor/src/trace/tests/chiplets/mod.rs
- processor/src/trace/utils.rs
This PR adds hasher lookups to the chiplets bus b_chip auxiliary column.
I left comments in a few specific spots where I opted for simplicity but think things could be improved. (And I'm happy to make those changes in this PR - just wanted to get most of the complexity handled fairly cleanly first)
After this PR is merged, the following related changes will still be needed
- update mdbook description of the operation label in the hasher chiplet design docs
- update mdbook description of the chiplets and b_chip bus column
- update [unit tests in the hasher module](https://github.com/maticnetwork/miden/blob/next/processor/src/trace/tests/chiplets/hasher.rs) to test that lookups were correctly recorded
- add a unit test to the [hasher chiplet trace unit …
> Add hasher lookups to the chiplets bus

- miden/tests/integration/air/range.rs
- processor/src/range/aux_trace.rs
- processor/src/range/mod.rs
- processor/src/trace/tests/range.rs
#342 raised an issue where verification failed when range checks of `u16::MAX` were required. This was due to 2 issues:
1. There was an indexing error in the generation of the execution trace for the `p1` column (now referred to in the docs as `b_range`) which caused lookups of `u16::MAX` not to be included in the `p1` column.
2. After fixing (1), verification continued to fail because there wasn't sufficient trace length in the `p1` column to hold the lookup value associated with the final range check value (u16::MAX). This is because data for these values comes from the "current" row, while lookups are included in the "next" row. The trace was only long enough to contain 1 additional row after the u16::MAX value in the range checker trace, which is always reserved for a random value. …
> Fix range checker auxiliary column trace

- docs/src/design/chiplets/bitwise.md
- docs/src/design/chiplets/main.md
- docs/src/design/multiset.md
- docs/src/design/range.md
This PR addresses some outstanding documentation clarifications & improvements from #364.
- minor improvements to multiset/chiplets descriptions for clarity and consistency
- add degrees to range checker constraint formulas
- switch range checker constraints to use $\alpha_i$
> Update multiset and range checker documentation

- docs/src/design/decoder/constraints.md
- docs/src/design/stack/op_constraints.md
This PR updates the constraints in the decoder documentation as required by the new operation flag assignments.
- update degrees of decoder constraints
- define more efficient flag for control flow operations
> docs(mdbook): update decoder constraints

- docs/src/user_docs/assembly/stack_manipulation.md
Tiny inconsistency in our docs. In the [overview](https://maticnetwork.github.io/miden/intro/overview.html), we say depth is 2^32; in the [assembly user docs](https://maticnetwork.github.io/miden/user_docs/assembly/stack_manipulation.html), we say 2^16. 
I change it to 2^32 for now, however, I am not sure if this is entirely correct.
According to @bobbinth:
- Stack depth is theoretically unlimited, the overflow table can absorb as many items as needed
- VM can push at most 1 item onto the stack at each clock cycle, and because of the parameters we use (field, blowup factor) we cannot execute more than 2^29 cycles on the VM
- Limitation will change somewhat with the PR that grjte is working on now: ability to initialize the stack with a large number of values
- Repo forked and branch …
> Ensuring stack depth consistency in docs

- air/Cargo.toml
- air/benches/compute_op_flags.rs
- air/src/lib.rs
- air/src/stack/mod.rs
- air/src/stack/op_flags/mod.rs
- air/src/stack/op_flags/tests.rs
- core/src/operations/mod.rs
This PR introduces a struct in the AIR crate where all the individual stack constraint flags are computed to reduce multiplication and subtraction operation cost as suggested by @bobbinth in this [PR](#370).
> Centralised struct to compute stack constraint flags

- assembly/src/parsers/field_ops.rs
- assembly/src/parsers/mod.rs
- assembly/src/parsers/u32_ops.rs
- assembly/src/tests.rs
- docs/src/user_docs/assembly/field_operations.md
- docs/src/user_docs/assembly/u32_operations.md
Added `assertz`, `u32wrapping_madd`, and `u32wrapping_add3` to assembly instructions.
Ref: #357 
Also updated the documentation to accommodate the new insructions.
> New assembly instructions

- air/benches/compute_op_flags.rs
- air/src/lib.rs
- air/src/stack/field_ops/mod.rs
- air/src/stack/field_ops/tests.rs
- air/src/stack/mod.rs
- air/src/stack/op_flags/mod.rs
- air/src/stack/op_flags/tests.rs
- air/src/stack/stack_manipulation/mod.rs
- air/src/stack/stack_manipulation/tests.rs
- air/src/stack/system_ops/mod.rs
- air/src/stack/system_ops/tests.rs
- air/src/utils.rs
- core/src/lib.rs
- core/src/stack/mod.rs
- miden/tests/integration/air/stack/field_ops.rs
- miden/tests/integration/air/stack/mod.rs
- miden/tests/integration/air/stack/stack_manipualtion_ops.rs
This PR introduces a structure for the stack operations AIR constraints to the VM. Simple operations constraints were implemented from different logical group which doesn't require a stack shift, interaction with chiplets and helper variables in decoder.
> Stack AIR constraints structure

- air/src/lib.rs
- air/src/stack/mod.rs
- processor/src/range/mod.rs
- processor/src/range/tests.rs
- processor/src/stack/mod.rs
- processor/src/stack/tests.rs
- processor/src/stack/trace.rs
- processor/src/system/mod.rs
This PR contains minor code fixes and clean-ups:
* Replaced `Felt::ZERO` and `Felt::ONE` with just `ZERO` and `ONE` in several files.
* Replaced `Felt::new(Felt::MODULUS - 1)` with `-ONE` in several places.
* Made sure `h0` column of stack trace is initialized to `1/(init_depth - 16)` when `init_depth > 16`.
> fix: minor code cleanup

- assembly/src/parsers/io_ops/adv_ops.rs
- assembly/src/parsers/io_ops/constant_ops.rs
- assembly/src/parsers/io_ops/env_ops.rs
- assembly/src/parsers/io_ops/mod.rs
- assembly/src/parsers/mod.rs
- docs/src/user_docs/assembly/io_operations.md
- miden/tests/integration/operations/decorators/advice.rs
- miden/tests/integration/operations/io_ops/adv_ops.rs
- stdlib/asm/math/poly512.masm
- stdlib/asm/math/u64.masm
- stdlib/src/asm.rs
Operations have been renamed and optimized:
`loadw.adv` --> `adv_loadw`
`push.adv.n` --> `adv_push.n`
> Advice operations refactoring

- air/src/stack/mod.rs
- air/src/stack/op_flags/mod.rs
- air/src/stack/op_flags/tests.rs
- air/src/stack/stack_manipulation/mod.rs
- assembly/src/parsers/io_ops/mem_ops.rs
- core/src/decoder/mod.rs
- core/src/lib.rs
- miden/tests/integration/exec_iters.rs
- miden/tests/integration/flow_control/mod.rs
- miden/tests/integration/helpers/mod.rs
- processor/src/chiplets/memory/mod.rs
- processor/src/chiplets/memory/segment.rs
- processor/src/chiplets/memory/tests.rs
- processor/src/chiplets/mod.rs
- processor/src/debug.rs
- processor/src/decoder/aux_hints.rs
- processor/src/decoder/block_stack.rs
- processor/src/decoder/mod.rs
- processor/src/decoder/tests.rs
- processor/src/decoder/trace.rs
- processor/src/lib.rs
- processor/src/operations/io_ops.rs
- processor/src/system/mod.rs
This PR adds support for multiple memory contexts. Specifically:
This PR does not yet include:
- Stack depth manipulations when `CALL` operation is executed.
- Inclusion of `ctx`, `fmtp` and stack depth into block stack table.
- Documentation updates.
These will be addressed in future PRs.
> Implement multi-context memory

- assembly/src/context/mod.rs
- assembly/src/errors.rs
- assembly/src/lib.rs
- assembly/src/parsers/blocks.rs
- assembly/src/tokens/mod.rs
- core/src/lib.rs
- core/src/operations/mod.rs
- core/src/program/blocks/call_block.rs
- core/src/program/blocks/mod.rs
- core/src/program/mod.rs
- miden/tests/integration/flow_control/mod.rs
- miden/tests/integration/helpers/mod.rs
- miden/tests/integration/main.rs
- processor/src/chiplets/tests.rs
- processor/src/decoder/tests.rs
- processor/src/errors.rs
- processor/src/lib.rs
- processor/src/operations/mod.rs
- processor/src/trace/tests/mod.rs
This PR implements `SYSCALL` operation and the associated assembly instruction. Main changes are:
- Implement `Kernel` struct which is now included with every program.
- Update assembler to enable instantiation with a given kernel source and parsing programs in the context of the specified kernel.
- Update processor to execute programs in the context of a given kernel.
This PR does not include:
- Updates to the decoder required to enforce syscall semantics
- Updates to chiplets component to enforce verification of kernel calls
- Updates to the documentation
> Implement syscall operation

- core/src/chiplets/hasher.rs
- core/src/chiplets/mod.rs
- processor/src/chiplets/hasher/mod.rs
- processor/src/chiplets/hasher/tests.rs
- processor/src/chiplets/hasher/trace.rs
- processor/src/chiplets/mod.rs
- processor/src/decoder/block_stack.rs
Partly addressing #103.
Adds memoization of hash execution traces for program blocks so that we don't need to build the trace every time the same program block is encountered.
Benchmark (Execution times):
| Program | Without memoization  | With memoization  | Improvement (%)  |
|-------------|-------------------------------|--------------------------|--------------------|
| sha256   | 18.54 ms | 18.41  | Insignificant  |
| keccak256 | 99.91 ms  | 96.89 ms  | ~ 3% |
| blake3  | 5.68ms | 5.62 ms  | Insignificant  |
Just to have an idea of maximum improvement possible with memoization, we can consider programs that have highly repeated small program blocks. Consider the following program:
```
repeat.200
push.10 drop
while.true neq.0 end
end
```
Here we see the execution time reduce from …
> Hasher execution trace memoization

- air/benches/enforce_stack_constraint.rs
- air/src/stack/io_ops/mod.rs
- air/src/stack/io_ops/tests.rs
- air/src/stack/mod.rs
- air/src/stack/op_flags/mod.rs
- air/src/stack/u32_ops/mod.rs
- air/src/stack/u32_ops/tests.rs
This PR introduces u32 and input/output air constraints. 
On running the benchmark test with u32 and io constraints included, the following numbers have been observed:
```
enforce_stack_constraint/enforce_stack                                                                             
time:   [1.0001 µs 1.0008 µs 1.0017 µs]
change: [+78.924% +79.160% +79.435%] (p = 0.00 < 0.05)
Performance has regressed.
```
> Stack io u32 operations

- core/src/chiplets/hasher.rs
- core/src/chiplets/mod.rs
- processor/src/chiplets/bitwise/mod.rs
- processor/src/chiplets/bus/aux_trace.rs
- processor/src/chiplets/bus/mod.rs
- processor/src/chiplets/hasher/aux_trace.rs
- processor/src/chiplets/hasher/lookups.rs
- processor/src/chiplets/hasher/mod.rs
- processor/src/chiplets/hasher/trace.rs
- processor/src/chiplets/memory/mod.rs
- processor/src/decoder/aux_hints.rs
- processor/src/lib.rs
- processor/src/range/aux_trace.rs
- processor/src/range/request.rs
- processor/src/stack/aux_trace.rs
- processor/src/stack/overflow.rs
- processor/src/trace/decoder/mod.rs
- processor/src/trace/decoder/tests.rs
- processor/src/trace/tests/hasher.rs
- processor/src/trace/tests/stack.rs
- processor/src/trace/utils.rs
Partly addressing #360.
Benchmark:
Execution time for keccak256 reduced from 91.833 ms to 87.36 ms, an improvement of ~4.8% after removing `HasherState` from `HasherLookup`.
> Refactor HasherLookup

- processor/src/chiplets/bus/mod.rs
- processor/src/chiplets/hasher/lookups.rs
- processor/src/chiplets/hasher/mod.rs
- processor/src/chiplets/hasher/tests.rs
- processor/src/chiplets/mod.rs
Partly addressing #360.
Removes `lookups` from the `Hasher` struct and refactors sending responses to the Chiplet Bus so that the responses are provided to the bus at the same time as the requests.
> Remove lookups from Hasher struct

- docs/src/user_docs/assembly/field_operations.md
- docs/src/user_docs/assembly/flow_control.md
This commit updates the documentation for `while` and `assertz` of the assembly documentation.
An example was added for `while` to clarify its expectation of having a boolean on top of the stack, instead of using a constant `true` as argument.
The `assertz` directive was updated from a nit that suggested there was a `b` to be evaluated, when in fact it is a constant `0`.
> docs(assembly): change examples for while, assertz

- .github/workflows/ci.yml
- core/src/utils/mod.rs
This commit introduces the --release flag for the tests. It will sacrifice some build time to greatly improve the tests execution.
One concern to add `release` is that `debug_assert` checks will no longer be performed. These are used in `miden` and upstream dependencies. To fix that, the `debug-assertions` compiler flag was added so these assertions will be executed.
To ensure the CI always executes the debug assertions, a test `debug_assert_is_checked_in_ci` was added. It will expect a panic and will fail by default, unless the `CI` environment variable is set. If it is set, then it will panic only if `debug_assert` is evaluated.
The CI variable is always set to `true` in github CI environments. For more info:
https://docs.github.com/en/actions/learn-github-actions/environment-variables
> chore(ci): add release to tests

- assembly/src/parsers/ast/io_ops.rs
- assembly/src/parsers/ast/tests.rs
Small bug fix: now `push` operation with multiple constants are available for use in AST parsing module
> fix: multiple constants in push operation

- verifier/src/lib.rs
clippy introduced a new lint that requires `Eq` to be derived when `PartialEq` is present
> refactor(verifier): add `Eq` derive to verifier

- assembly/Cargo.toml
- assembly/src/parsers/ast/context.rs
- assembly/src/parsers/ast/mod.rs
- assembly/src/parsers/ast/nodes.rs
- assembly/src/parsers/ast/serde/deserialization.rs
- assembly/src/parsers/ast/serde/serialization.rs
- assembly/src/parsers/ast/tests.rs
`exec` and `call` AST nodes now take hash of the path instead of path itself
> AST exec and call nodes refactoring

- assembly/Cargo.toml
- assembly/src/lib.rs
- assembly/src/tests.rs
- miden/Cargo.toml
- miden/src/cli/data.rs
- miden/src/examples/fibonacci.rs
- miden/src/tools/mod.rs
- miden/tests/integration/helpers/mod.rs
- stdlib/Cargo.toml
- stdlib/src/lib.rs
This initial step for the solution of #298 removes stdlibrary as dependency of assembler.
This decoupling will increase the assembler module extraction flexibility. As next step, an efficient lookup of hasher module+label will be introduced in order to fetch parsed/compiled procedures.
> Provide stdlib via module provider to assembler

- stdlib/build.rs
- stdlib/src/asm.rs
Fixed unescaped backslash and quotation symbols bug when generating `asm.rs` in `stdlib`, as it mention in #399
> Unescaped backslash and quotation 

- core/src/chiplets/bitwise.rs
- core/src/chiplets/kernel_rom.rs
- core/src/chiplets/memory.rs
- core/src/chiplets/mod.rs
- core/src/lib.rs
- core/src/program/mod.rs
- miden/tests/integration/helpers/mod.rs
- processor/src/chiplets/kernel_rom/mod.rs
- processor/src/chiplets/kernel_rom/tests.rs
- processor/src/chiplets/memory/tests.rs
- processor/src/chiplets/mod.rs
- processor/src/chiplets/tests.rs
- processor/src/decoder/tests.rs
- processor/src/decorators/mod.rs
- processor/src/lib.rs
- processor/src/operations/mod.rs
- processor/src/trace/tests/mod.rs
This PR implements Kernel ROM chiplet within the `processor` crate. This includes:
* Implementing Kernel ROM chiplet.
* Updating the Decoder to rely on Kernel ROM chiplet to check `syscall` validity.
Things left for future PRs:
* Updating mdBook docs to describe the new structure of chiplets.
* Implementing additional `syscall` semantics:
- Setting `fmp` to $2^{31}$ when for inside `syscall`s.
- Adding trace columns to enable checks preventing `syscall`s from within kernel context.
* Update aux trace column needed for enforcing correctness of kernel ROM (this includes updates to chiplet bus).
- Setting boundary constraints for the kernel against which a program was executed.
> Implement Kernel ROM

- stdlib/asm/crypto/dsa/falcon.masm
- stdlib/asm/crypto/hashes/blake3.masm
- stdlib/asm/crypto/hashes/keccak256.masm
- stdlib/asm/crypto/hashes/sha256.masm
- stdlib/asm/math/ec_ext5.masm
- stdlib/asm/math/ext2.masm
- stdlib/asm/math/ext5.masm
- stdlib/asm/math/ntt512.masm
- stdlib/asm/math/poly512.masm
- stdlib/asm/math/secp256k1.masm
- stdlib/asm/math/u256.masm
- stdlib/asm/math/u64.masm
- stdlib/asm/sys.masm
- stdlib/src/asm.rs
- stdlib/stdlib_docs.rs
Comment symbols in stdlib `.masm` files were changed from "#" to "#!", as it mentioned in first bullet point of #296 issue
> New type of doc comments

- miden/Cargo.toml
- miden/src/cli/mod.rs
- miden/src/cli/prove.rs
- miden/src/cli/repl.rs
- miden/src/main.rs
- miden/src/repl/mod.rs
This PR addresses #423 and is in continuation to the work done by the scribe team [here](https://github.com/ControlCplusControlV/Scribe/blob/main/transpiler/src/repl.rs#L8). 
The following tasks are addressed in this PR:
> Implement Repl tool in Miden VM

- assembly/src/lib.rs
- assembly/src/parsers/ast/mod.rs
- assembly/src/parsers/mod.rs
- assembly/src/tests.rs
- core/src/program/library.rs
- stdlib/Cargo.toml
- stdlib/build.rs
- stdlib/src/asm.rs
- stdlib/src/lib.rs
This commit introduces the deserialization of precompiled modules as ModuleAst instead of strings to be parsed somewhere else.
We have two pending actions introduced by this PR
- build stdlib docs in build.rs
- The assembly module provider shouldn't return the source str. Instead, it should return a ModuleAst. However, this will cause non-negligible impact in the module parsing of the assembly.
> Update stdlib build to ast

- assembly/src/parsers/ast/context.rs
- assembly/src/parsers/ast/mod.rs
- assembly/src/parsers/ast/nodes.rs
- assembly/src/parsers/ast/serde/deserialization.rs
- assembly/src/parsers/ast/serde/serialization.rs
- assembly/src/parsers/ast/tests.rs
`index` field in `ProcedureAst` structure was pulled out to `ProcMap`. Thus this field is not serializing anymore
> Remove index field from ProcedureAst struct

- core/src/decoder/mod.rs
- core/src/lib.rs
- processor/src/decoder/block_stack.rs
- processor/src/decoder/mod.rs
- processor/src/decoder/tests.rs
- processor/src/decoder/trace.rs
- processor/src/lib.rs
- processor/src/operations/sys_ops.rs
- processor/src/system/mod.rs
This PR updates the decoder to correctly process SYSCALL blocks. This includes:
- Adding an `in_syscall` column to the decoder trace. Values in this column are set to 1 when we are inside a SYSCALL block and to 0 otherwise. We will use this column in constraints to make sure that executing a `SYSCALL` operation within a SYSCALL block is not possible.
- Setting the `h7` register to 1 when we are exiting a SYSCALL block (i.e., when `END` operation is executed). This means that we now make use of all helper registers when `END` operation is executed. Specifically, registers `h4` - `h7` are now set to the following flags: `[is_loop_body, is_loop, is_call, is_syscall]`.
- Updating logic for how `fmp` values are set. Specifically, the logic remains the same for regular procedure and function …
> Implement SYSCALL block processing in decoder

- air/src/stack/overflow/mod.rs
- air/src/stack/overflow/tests.rs
This PR fixes #466. It also sets the next frame correctly, which was not happening in the last [PR](#473), where the current frame was updated again instead of the next. Due to this, the tests were failing because of other stack overflow constraints.
> Fix the overflow stack depth air constraint

- docs/src/intro/overview.md
This PR removes a few references to the 16-element input & output restrictions that were dropped when we refactored the stack overflow initialization/finalization handling.
> Update the documentation of inputs & outputs

- assembly/src/parsers/ast/context.rs
- assembly/src/parsers/ast/nodes.rs
- assembly/src/parsers/ast/serde/deserialization.rs
- assembly/src/parsers/ast/serde/mod.rs
- assembly/src/parsers/ast/serde/serialization.rs
- assembly/src/todo/instruction/crypto_ops.rs
- assembly/src/todo/instruction/mod.rs
- assembly/src/todo/span_builder.rs
This PR adds handlers for compiling cryptographic instructions in the new assembler structure.
> Compile crypto ops in the new assembler structure

- assembly/src/errors.rs
- assembly/src/todo/instruction/field_ops.rs
- assembly/src/todo/instruction/mod.rs
- assembly/src/todo/instruction/u32_ops.rs
This PR adds handlers for compiling most u32 instructions in the new assembler structure. Only the comparison operations have not been addressed yet.
> Compile most u32 ops in the new assembler structure

- assembly/src/parsers/ast/context.rs
- assembly/src/parsers/ast/u32_ops.rs
- miden/tests/integration/operations/u32_ops/arithmetic_ops.rs
Fixed  `parse_u32checked_eq()` and  `parse_u32checked_neq()` parsers ― now `checked_eq` and `checked_neq` operations could be used with immediate values. 
Error messages in `u32checked_div_b_fail()`, `u32checked_mod_b_fail()` and `u32checked_divmod_b_fail()` integration tests was updated with new `AssemblerError` messages.
> eq and neq parsers, u32 error message

- assembly/src/assembler/instruction/adv_ops.rs
- assembly/src/assembler/instruction/env_ops.rs
- assembly/src/assembler/instruction/mem_ops.rs
- assembly/src/assembler/instruction/mod.rs
- assembly/src/assembler/instruction/u32_ops.rs
- assembly/src/assembler/span_builder.rs
- assembly/src/errors.rs
- assembly/src/lib.rs
This PR implements handling of advice injectors in the new assembler structure. It also fixes a couple of bugs and contains minor refactorings of u32 operation handlers.
> Implement handling of advice injectors in new assembler

- assembly/src/assembler/instruction/field_ops.rs
- assembly/src/assembler/instruction/mod.rs
- assembly/src/assembler/span_builder.rs
- assembly/src/lib.rs
This PR implements handlers for compiling `exp` operations in the new assembler. It also fixes a few bugs in the field operation handlers and cleans up comments in the `fild_ops` module.
> Implement compilation of exp operations

- assembly/src/assembler/context.rs
- assembly/src/assembler/instruction/adv_ops.rs
- assembly/src/assembler/instruction/crypto_ops.rs
- assembly/src/assembler/instruction/env_ops.rs
- assembly/src/assembler/instruction/field_ops.rs
- assembly/src/assembler/instruction/mem_ops.rs
- assembly/src/assembler/instruction/mod.rs
- assembly/src/assembler/instruction/procedures.rs
- assembly/src/assembler/instruction/u32_ops.rs
- assembly/src/assembler/mod.rs
- assembly/src/assembler/span_builder.rs
- assembly/src/errors.rs
- assembly/src/lib.rs
- assembly/src/tests.rs
- miden/src/lib.rs
- miden/src/main.rs
- miden/src/repl/mod.rs
- miden/src/tools/mod.rs
- miden/tests/integration/operations/u32_ops/arithmetic_ops.rs
This PR refactors `AssemblerError` as follows:
- Change `AssemblerError` from struct into an enum.
- Rename `AssemblerError` into `AssemblyError`.
- Add more info to some error variants.
This PR also fixes a couple of small errors in Miden executable to make it compile and run.
> Refactor AssemblyError and fix Miden executable

- assembly/src/assembler/instruction/crypto_ops.rs
- assembly/src/assembler/instruction/env_ops.rs
- assembly/src/assembler/instruction/u32_ops.rs
This PR reorganizes some of the instructions implementations and move repeated code into helpers
> refactor: assembly ops impls for crypto, u32 and env

- air/src/stack/u32_ops/tests.rs
- processor/src/decoder/mod.rs
- processor/src/decoder/trace.rs
- processor/src/operations/u32_ops.rs
This PR addresses #510. I've tried to reproduce the error by writing a failed unit test. The issue seems to be how the upper bits are aggregated and updated in helper registers in the `u32add` operation. Here is a brief explanation of why we are having this issue:
The processor splits the sum of the top two elements into two 32-bit limbs and sents both for range check. In the case of `u32add`, instead of sending the `hi` 32-bit limb, it sends a ZERO, due to which the top two most significant bits in the user helper register are being set to ZERO. When the sum of the two top elements of the stack overflows an u32, we will have the issue. 
The unit tests used the `hi` as the second most significant in the helper register, due to which they were not failing. If we set the second most …
> Fix: u32add and upper bits agg constraint

- assembly/src/parsers/serde/serialization.rs
This PR introduce a fix for #553. 
The ExpImm and ExpBitLength instructions were not using their respective opcode during serialization, causing a few tests in #553 to fail. This PR rectifies this issue, and the correct opcode is assigned to both.
> ExpImm and ExpBitLength assembly serialization fix

- .github/workflows/ci.yml
- assembly/src/assembler/context.rs
- assembly/src/assembler/mod.rs
- assembly/src/assembler/module_provider.rs
- assembly/src/assembler/tests.rs
- assembly/src/errors.rs
- assembly/src/lib.rs
- assembly/src/parsers/context.rs
- assembly/src/parsers/field_ops.rs
- assembly/src/parsers/mod.rs
- assembly/src/parsers/nodes.rs
- assembly/src/parsers/serde/deserialization.rs
- assembly/src/parsers/tests.rs
- assembly/src/procedures/mod.rs
- assembly/src/tests.rs
- assembly/src/tokens/mod.rs
- core/src/operations/decorators/advice.rs
- miden/benches/program_compilation.rs
- miden/benches/program_execution.rs
- miden/src/cli/data.rs
- miden/src/tools/mod.rs
- miden/tests/integration/helpers/mod.rs
- processor/src/decoder/trace.rs
- processor/src/trace/mod.rs
- stdlib/md_renderer.rs
- stdlib/src/lib.rs
This commit changes the Library trait of assembly to provide AST modules to the compilation process.
It also introduces a type-safe path for library namespace, module path (relative), procedure name, and absolute path. Prior to this commit, there was no distinction between these different states and they were treated as raw strings. It was a context-heavy task to define when a path is absolute and when is relative to a module.
The procedure ID, used to compile AST into MAST, is calculated always with the absolute path of a procedure. Having only strings was error-prone to compute the procedure ID correctly. With this commit, the absolute path, used to compute a procedure ID, can only be obtained from a sequence of validations in the namespace, module path, and procedure name.
This commit …
> refactor(assembly): library trait to provide ast modules

- assembly/src/errors.rs
- assembly/src/lib.rs
- assembly/src/parsers/context.rs
- assembly/src/parsers/mod.rs
- assembly/src/parsers/nodes.rs
- assembly/src/parsers/serde/deserialization.rs
- assembly/src/parsers/serde/serialization.rs
- assembly/src/parsers/tests.rs
- assembly/src/procedures/mod.rs
- assembly/src/tests.rs
- assembly/src/tokens/mod.rs
- miden/src/cli/data.rs
- miden/src/tools/mod.rs
This PR improves error handling in the assembly parser and cleans up parser structure. Specifically:
- Addresses #514. This was actually much simpler than I thought as the logic was already there - we just need to break out of the loop instead of returning an error.
- Streamlines parsing of control flow blocks. There is no longer a need for check `is_control_token()` during parsing.
- Improves error reporting for invoking procedures - e.g., invalid invocation strings, un-imported modules etc.
- Moves validation of procedure names into `ProcedureName` struct.
Refactoring of validation of import paths and procedure invocation labels are left to future PRs.
> Assembly parser error reporting improvements

- air/src/lib.rs
Clippy [complained](https://github.com/0xPolygonMiden/miden-vm/actions/runs/3829167260/jobs/6517287374):
```
error: the borrowed expression implements the required traits
--> air/src/lib.rs:266:22
|
266 |         target.write(&stack);
|                      ^^^^^^ help: change this to: `stack`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
= note: `-D clippy::needless-borrow` implied by `-D clippy::all`
error: the borrowed expression implements the required traits
--> air/src/lib.rs:270:22
|
270 |         target.write(&overflow_addrs);
|                      ^^^^^^^^^^^^^^^ help: change this to: `overflow_addrs`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow …
```
> Fix clippy warning about needless borrows

- docs/src/user_docs/assembly/io_operations.md
This resolves the docs issue noted in #604.
> docs: fix ref to renamed assembly instruction

- assembly/src/tests.rs
- miden/tests/integration/helpers/mod.rs
- miden/tests/integration/operations/decorators/asmop.rs
- miden/tests/integration/operations/field_ops.rs
- miden/tests/integration/operations/io_ops/adv_ops.rs
- miden/tests/integration/operations/io_ops/constant_ops.rs
- miden/tests/integration/operations/io_ops/env_ops.rs
- miden/tests/integration/operations/io_ops/mem_ops.rs
- miden/tests/integration/operations/u32_ops/arithmetic_ops.rs
- miden/tests/integration/operations/u32_ops/bitwise_ops.rs
- miden/tests/integration/operations/u32_ops/comparison_ops.rs
- miden/tests/integration/operations/u32_ops/mod.rs
- miden/tests/integration/stdlib/crypto/falcon.rs
- miden/tests/integration/stdlib/crypto/keccak256.rs
- miden/tests/integration/stdlib/crypto/sha256.rs
- miden/tests/integration/stdlib/math/ecgfp5/base_field.rs
- miden/tests/integration/stdlib/math/ecgfp5/group.rs
- miden/tests/integration/stdlib/math/ntt512.rs
- miden/tests/integration/stdlib/math/poly512.rs
- miden/tests/integration/stdlib/math/secp256k1/scalar_field.rs
- miden/tests/integration/stdlib/math/u64_mod.rs
- processor/src/decoder/tests.rs
- processor/src/stack/tests.rs
As part of CI/CD we are running
```
cargo clippy --all -- -D clippy::all -D warnings
```
Inspired by that, I asked clippy to also suggest a few additional
fixes to me to apply manually once:
```
cargo clippy --all --fix --allow-dirty -- -D clippy::all -D warnings
```
Most changes are quite trivial (but make the code a bit cleaner), but
have a look at `miden/tests/integration/stdlib/math/ecgfp5/group.rs` for
the one non-trivial refactor.
> Automatic fixes from clippy

- core/src/inputs/mod.rs
- miden/benches/program_execution.rs
- miden/src/cli/prove.rs
- miden/src/cli/run.rs
- miden/src/examples/fibonacci.rs
- miden/src/examples/mod.rs
- miden/src/lib.rs
- miden/src/repl/mod.rs
- miden/src/tools/mod.rs
- miden/tests/integration/flow_control/mod.rs
- miden/tests/integration/helpers/mod.rs
- miden/tests/integration/operations/io_ops/env_ops.rs
- processor/src/advice/mem_provider.rs
- processor/src/advice/mod.rs
- processor/src/chiplets/tests.rs
- processor/src/decoder/tests.rs
- processor/src/decorators/mod.rs
- processor/src/lib.rs
- processor/src/operations/mod.rs
- processor/src/trace/tests/mod.rs
- prover/src/lib.rs
This commit introduces the advice trait as argument of the execute function of the processor. It will, downstream, impact on the prover and miden binaries.
Currently, there is no mechanism to serialize a generic instance of the advice provider to a file so it can be reconstructed for CLI applications. The only use-case is to have in-memory, default implementation of the advice provider, so it is using hardcoded `MemAdviceProvider`.
The examples are also falling back to in-memory provider so we don't add complexity and require them to serialize a generic advice provider.
closes #409
> feat(processor): advice provider as exec argument

- docs/src/user_docs/assembly/field_operations.md
Fixes typo in ext2 instructions in docs.
> fix: fix ext2 instructions typo

- docs/src/design/decoder/main.md
- docs/src/user_docs/assembly/io_operations.md
Small changes:
- fixes a typo and an error
- adds details about the element order when using tape operations
> Documentation changes

- air/src/lib.rs
- assembly/src/parsers/mod.rs
- core/src/inputs/mod.rs
- core/src/inputs/stack.rs
- core/src/lib.rs
- core/src/outputs.rs
- core/src/program/info.rs
- core/src/program/mod.rs
- miden/README.md
- miden/src/cli/verify.rs
- miden/src/examples/mod.rs
- miden/src/lib.rs
- miden/src/repl/mod.rs
- miden/tests/integration/helpers/mod.rs
- processor/src/chiplets/kernel_rom/mod.rs
- processor/src/chiplets/kernel_rom/tests.rs
- processor/src/chiplets/mod.rs
- processor/src/chiplets/tests.rs
- processor/src/decoder/tests.rs
- processor/src/decorators/mod.rs
- processor/src/lib.rs
- processor/src/operations/mod.rs
- processor/src/trace/mod.rs
- processor/src/trace/tests/mod.rs
- prover/src/lib.rs
- verifier/src/lib.rs
This commit introduces `ProgramInfo`, a structure that will bind both the program hash and the used kernel to the generated zk proof.
It will use the kernel procedures as public inputs of the proof so the security guarantees provided by the kernel can be extended to any state transition with a valid proof. It will also allow efficient queries for members of the kernel.
The CLI currently doesn't support kernel as argument as it will only take the code root hash of a given program. It is currently using as fallback and empty/default kernel.
related issue #409
> feat(processor): add program info

- processor/src/advice/mem_provider.rs
- processor/src/advice/mod.rs
- processor/src/advice/source.rs
- processor/src/decorators/mod.rs
- processor/src/lib.rs
- processor/src/operations/io_ops.rs
This commit introduces `[AdviceSource]` as enum to wrap the possible variants that can be used as input for the advice provider.
This new type can be extended in the future to have more complex structures such as signatures or batched field elements.
related issue: #409
> feat(processor): add advice source

- assembly/src/procedures/mod.rs
Return an error instead of panic, as described on #578
> fix: handle invalid utf8 on deserialization

- assembly/src/assembler/instruction/field_ops.rs
- assembly/src/assembler/instruction/mod.rs
Follows the same pattern as immediate addition and when subtracting by zero translates to a `Nop` instead of two opcodes, saving one cycle on this edge case.
> Optimize immediate sub

- docs/src/user_docs/assembly/field_operations.md
`neq` is 2 cycles [ref](https://github.com/0xPolygonMiden/miden-vm/blob/main/assembly/src/assembler/instruction/mod.rs#L66)
`neq.imm` is 2/3 cycles [ref](https://github.com/0xPolygonMiden/miden-vm/blob/main/assembly/src/assembler/instruction/field_ops.rs#L217-L222)
> docs: neq is always 2 cycles

- core/Cargo.toml
- core/src/chiplets/hasher.rs
- core/src/program/blocks/call_block.rs
- core/src/program/blocks/join_block.rs
- core/src/program/blocks/loop_block.rs
- core/src/program/blocks/mod.rs
- core/src/program/blocks/span_block.rs
- core/src/program/blocks/split_block.rs
- processor/src/chiplets/hasher/mod.rs
- processor/src/chiplets/hasher/tests.rs
- processor/src/chiplets/mod.rs
- processor/src/decoder/mod.rs
- processor/src/trace/tests/chiplets/hasher.rs
This PR adds a domain specifier to the second element of the capacity register when hashing control blocks using Rescue prime optimised in Miden.  This is to avoid hash collisions of different programs when constructing a MAST.   The domain is calculated using bitwise composition of the opcode bits as such `[bit_0 * 2**0 + bit_1 * 2**1 + ... + bit_6 * 2**6 + 1]`.
closes: #605
> Add control block domain to MAST hashing

- assembly/src/errors.rs
- assembly/src/lib.rs
- assembly/src/parsers/context.rs
- assembly/src/parsers/io_ops.rs
- assembly/src/parsers/labels.rs
- assembly/src/parsers/mod.rs
- assembly/src/procedures/mod.rs
- assembly/src/tests.rs
- assembly/src/tokens/mod.rs
- docs/src/user_docs/assembly/code_organization.md
This PR adds basic functionality that allows for the declaration of constants.  The current implementation allows for constants to be defined below imports and above any procedures / begin bodies.  The constants are scoped to the file they are defined in.  At the current point in time constants are only available to the push operation.
Example:
```
const.ONE_TWO=12
const.FIVE_SIX=56
begin
push.ONE_TWO.FIVE_SIX
mul
end
```
> Assembly constants

- assembly/src/assembler/instruction/crypto_ops.rs
- assembly/src/assembler/instruction/mod.rs
- assembly/src/parsers/context.rs
- assembly/src/parsers/nodes.rs
- assembly/src/parsers/serde/deserialization.rs
- assembly/src/parsers/serde/mod.rs
- assembly/src/parsers/serde/serialization.rs
- docs/src/user_docs/assembly/cryptographic_operations.md
- miden/tests/integration/operations/crypto_ops.rs
Introduce a new assembly instruction `hash` which performs a 1-to-1 hash using an Rpo permutation.  This PR migrates the 1-to-1 hashing logic from [this](https://github.com/0xPolygonMiden/miden-vm/blob/9092607c758183cee571713638faeab200e1fda7/stdlib/asm/crypto/hashes/rescue_prime.masm) masm script with a modification to the way in which the capacity register is instantiated.  The first element is instantiated to 0 in accordance with the new Rpo hashing rules.
> Introduce `hash` assembly instruction

- assembly/src/parsers/nodes.rs
- assembly/src/parsers/serde/deserialization.rs
- assembly/src/parsers/serde/serialization.rs
- assembly/src/tokens/mod.rs
This PR enabled `repeat` statements with `u32` parameter specifying the number of iteration (before this PR, this was limited to `u16`).
> Repeat statements with u32 parameters

- assembly/src/assembler/context.rs
This PR moves assertions to the start of functions. Resolves #537.
- Repo forked and branch created from `next` according to the naming convention.
> Refactor: move assertions to start of functions

- assembly/src/errors.rs
- assembly/src/lib.rs
- assembly/src/parsers/labels.rs
- assembly/src/procedures/mod.rs
numeric casts truncate the data, so the comparison should be done against the `usize` and then converted to the smaller representation.
Note: This is not user observable issue, the `TryFrom` implementation checks the length already. This adds a test to make sure that is not lost and makes it clearer to someone reading the code that this was thought of.
> Procedure length, check before cast

- assembly/src/tokens/mod.rs
Added a bit of docs to the `Token` struct.
Does anyone know why it was opted to modify this in place?
> Token docs

- core/Cargo.toml
- core/src/program/info.rs
- core/src/program/mod.rs
- core/src/program/tests.rs
Currently, `ProgramInfo` implements only `Serializable`. It is so to keep the coupling between winter-utils and miden minimal, as the serialization traits are defined in winterfell.
However, this might create some challenges for consumers of miden-vm as they might have to deserialize the struct, such as when representing the type within other targets (i.e. WASM).
This commit introduces Deserializable for Kernel and ProgramInfo.
related issue: #731
> feat: implement Deserializable for ProgramInfo

- air/src/chiplets/hasher/mod.rs
- air/src/chiplets/hasher/tests.rs
- air/src/chiplets/mod.rs
Updates some of the documentation to refer to the hasher as a chiplet instead of a co-processor, and tries to clarify the expected value of the selector flags. Hopefully this should be a bit clearer 
> Hasher chiplet docs update

- processor/src/chiplets/hasher/trace.rs
The previous version converted column to row form, and then saved the row into the columns, an unnecessary round trip.
This just copies the data in the columns directly to its end using the `Vec::extend_within`.
> Hasher simplify copy trace

- miden/src/cli/compile.rs
- miden/src/cli/data.rs
- miden/src/cli/debug/mod.rs
- miden/src/cli/prove.rs
- miden/src/cli/run.rs
This PR enables debug mode on the assembler for the debugger.  This enables the debugger to map VM execution to the corresponding assembly instruction and provide this information to the user.
> Enable debug mode on assembler for debugger

- processor/src/chiplets/hasher/mod.rs
The VM has migrated to the Rescue Prime Optimized sponge function, which does not use the capacity to count the number of elements. Only to signal if padding is necessary. The user documentation is up-to-date and contains more details.
> docs: fixed inline comments

- core/src/chiplets/bitwise.rs
- core/src/chiplets/hasher.rs
- core/src/chiplets/memory.rs
- docs/src/design/chiplets/main.md
I was a bit confused why the selector value didn't match what the comments said, it seems the bits are in reverse order, possible because of endianess difference? In this PR I try to clarify the definition of the label value.
> Label definition clarification

- Makefile
- miden/Cargo.toml
- processor/src/stack/mod.rs
- processor/src/stack/trace.rs
This PR exposes `stack.trace_state()` via the internals flag.  This is required for testing of the note setup script in which we need to assert the note inputs are placed on the stack following the completion of the procedure. 
It also enables the `internals` flag by default for the `processor` crate in `miden` tests via specifying the feature in the dev dependency.
> feat: expose stack trace_state() via internals flag

- .github/workflows/ci.yml
- Cargo.toml
- Makefile
- docs/src/intro/usage.md
This commit removes the mandatory optimization from cargo toml and creates makefile tasks to replace them.
They will allow the user to choose when he wants a full optimization, or a partial. The full optimization is useful for release artifacts, and partial is useful for development tasks such as tests.
closes #768
> chore: update cargo toml and makefile parameters

- assembly/src/assembler/context.rs
- assembly/src/assembler/instruction/mod.rs
- assembly/src/assembler/span_builder.rs
- assembly/src/parsers/context.rs
- assembly/src/parsers/nodes.rs
- assembly/src/parsers/serde/serialization.rs
- core/src/operations/decorators/assembly_op.rs
- docs/src/intro/usage.md
- miden/src/cli/debug/command.rs
- miden/src/cli/debug/executor.rs
- miden/tests/integration/exec_iters.rs
- miden/tests/integration/operations/decorators/asmop.rs
- processor/src/debug.rs
- processor/src/lib.rs
This commit introduces `breakpoint`, a transparent instruction that will cause a debug execution to break when reached.
This instruction will not be serialized into libraries, and will not have an opcode or be part of the code block tree.
For debug executions, it will produce a `NOOP`, so the internal clock of the VM will be affected.
The decision of not including this as part of the code block is to avoid further consuming variants of opcodes as they are already scarce.
related issue: #580
> feat: add breakpoint instruction

- docs/src/user_docs/assembly/u32_operations.md
Very small change just make the two-complement explicit (it was not mentioned in the user docs, but only the design docs).
> docs: explicitly state u32 are two-complement

- miden/src/cli/data.rs
This PR introduces the ability to define advice map entries and merkle store data structures via the cli inputs file.
- Advice map keys are defined as a 32 byte hex string.
- Merkle tree leafs are defined as 32 byte hex strings. 
- Current support for `MerkleTree` and `SparseMerkleTree` data structures.
Please see this [miden example PR](https://github.com/0xPolygonMiden/examples/pull/120/files) for an example of this functionality and data definition.
> CLI advice map + merkle structures

- docs/src/intro/usage.md
Currently, it is not described which inputs are allowed in the  `inputs` file to run a program via the CLI.
> Adding the different input types to the CLI docs

- miden/src/cli/data.rs
- processor/src/lib.rs
This PR introduces support for merkle path set data structures via CLI.  Data definition description:
String representation of a Merkle path set. A Merkle path set is represented as a vector of tuples where each tuple consists of a u64 node index, a 32 byte hex string representing the value of the node, and a vector of 32 byte hex strings representing the Merkle path to the node.
> Merkle path set

- miden/examples/recursive_verification/recursive_verification.masm
This PR adds a proposed comment to the recursive verification example to help people attempting to use `verify` understand it better.
> Add comments to the recursive verification example

- test-utils/src/lib.rs
On a failure, instead of printing:
```
thread 'stdlib::collections::mmr::test_mmr_get_single_peak' panicked at 'assertion failed: `(left == right)`
left: `[BaseElement(4294967295), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0
), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0)]`,
right: `[BaseElement(17179869180), BaseElement(12884901885), BaseElement(4294967295000), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0), BaseEl
ement(0), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0), BaseElement(0)]`', miden/tests/integration/helpers/mod.rs:96:9
```
This prints:
```
thread …
```
> debug: convert from montgomery form prior to assert

- assembly/src/errors.rs
- assembly/src/parsers/context.rs
- assembly/src/parsers/io_ops.rs
- assembly/src/parsers/mod.rs
- assembly/src/tests.rs
- docs/src/user_docs/assembly/code_organization.md
This PR introduces constant support for the following operations:
* `locaddr.CONSTANT`
* `loc_load.CONSTANT`
* `loc_loadw.CONSTANT`
* `loc_store.CONSTANT`
* `loc_storew.CONSTANT`
* `mem_load.CONSTANT`
* `mem_loadw.CONSTANT`
* `mem_store.CONSTANT`
* `mem_storew.CONSTANT`
> Add constant support for memory operations

- stdlib/asm/crypto/fri/ext2fri.masm
- stdlib/asm/crypto/hashes/sha256.masm
This is a first iteration on the existing masm code to move the formatting according to https://github.com/0xPolygonMiden/miden-vm/discussions/698 . Hopefully I didn't introduce any errors :)
On this round I just added the Input/Output, only counted cycles for a very simple method, after I started this I realized the whole codebase will take a lot of time, so I decided to open this small PR first, with just a few of the changes to get it started, the other changes / files will come on follow ups.
> chore: format ext2fri and sha256 docstrings using current guidelines

- docs/src/design/decoder/constraints.md
- docs/src/design/decoder/main.md
- docs/src/design/stack/crypto_ops.md
- docs/src/design/stack/op_constraints.md
- docs/src/design/stack/stack_ops.md
- docs/src/design/stack/u32_ops.md
This PR fixes small typos in Miden VM documentation.
> Fix typos in docs

- assembly/src/parsers/nodes.rs
- assembly/src/procedures/mod.rs
This small PR address the issue described in https://github.com/0xPolygonMiden/miden-vm/issues/711. Instead of using BLAKE3_192 variant for computing 24 -bytes procedure id from procedure path name, we're using BLAKE3_160 variant now.
> Reduce Procedure Id Length to 20 -bytes

- miden/Cargo.toml
- miden/src/repl/mod.rs
- processor/src/debug.rs
This PR addresses the issue described in https://github.com/0xPolygonMiden/miden-vm/issues/719
> Remove Dependency of Miden REPL on `internals` feature of `miden-processor`

- CHANGELOG.md
- assembly/src/assembler/instruction/mod.rs
- assembly/src/parsers/adv_ops.rs
- assembly/src/parsers/nodes.rs
- assembly/src/parsers/serde/deserialization.rs
- assembly/src/parsers/serde/mod.rs
- assembly/src/parsers/serde/serialization.rs
- assembly/src/parsers/tests.rs
- core/src/lib.rs
- core/src/operations/decorators/advice.rs
- processor/Cargo.toml
- processor/src/advice/mem_provider.rs
- processor/src/advice/mod.rs
- processor/src/decorators/mod.rs
- processor/src/decorators/tests.rs
- processor/src/errors.rs
- stdlib/asm/collections/smt.masm
- stdlib/docs/smt_collections.md
- stdlib/tests/collections/mod.rs
- stdlib/tests/collections/smt.rs
- test-utils/src/crypto.rs
- test-utils/src/lib.rs
- test-utils/src/rand.rs
This commit introduces a `collections` module for the `stdlib`. It contains, initially, functions to support Sparse Merkle Tree functionality.
It also adds a `mtree_smt_index` operation that will fetch a depth/index pair from the advice provider and push onto the operand stack.
> feat: add stdlib smt collection

- assembly/src/errors.rs
- assembly/src/parsers/mod.rs
- assembly/src/parsers/tests.rs
- assembly/src/tokens/mod.rs
- assembly/src/tokens/stream.rs
Prior to this commit, [ParsingError] tracked the step of the source instead of the line number.
This is not friendly to the user as he won't be able to find the location of the error. A common standard is to display the line number, so the user can easily spot the location of the error.
This commit introduces such track. It keeps a 1:1 map on [TokenStream] from the token to the parsed line. As in common text editors, line number starts at `1`.
It also removes the `pos` from [Token] as its only purpose was to display the step to the user. The introduction of `line` completely supersedes that.
closes #574
> feat: add line number to parsing error

- docs/src/intro/usage.md
- miden/examples/fib/fib.inputs
- miden/examples/fib/fib.masm
Current version of Fibonacci example computes not 1000th, but 1002nd Fibonacci number. This PR fixes this by putting only `[1]` to the input and changing number of cycles to 999.
> Fibonacci example fix

- assembly/src/tokens/lines.rs
- assembly/src/tokens/mod.rs
- assembly/src/tokens/stream.rs
This commit introduces [Tokenizer], a tokens iterator that will decouple tokenizing logic from the parse logic of [TokenStream].
It will create the foundation to bind tokens to their location, regardless of parse constraints.
This commit aims to unblock the source mapping work.
related issue: #857
> feat: add assembly [Tokenizer]

- docs/src/design/stack/op_constraints.md
This PR fixes a small mistake in Operation constraints documentation. 
The operation bits order assumes reverse order of operation registers, but `f_drop` flag was computed using direct order.
> Fix of drop flag registers order

- stdlib/tests/crypto/fri/mod.rs
- stdlib/tests/crypto/fri/verifier_fri_e2f4.rs
It is a bit better to have a struct with named fields instead of a tuple with unnamed ones for readability. 
> Replaced tuple with struct for readability

- assembly/src/errors.rs
- assembly/src/lib.rs
- assembly/src/parsers/mod.rs
- assembly/src/parsers/tests.rs
- assembly/src/tokens/lines.rs
- assembly/src/tokens/location.rs
- assembly/src/tokens/mod.rs
- assembly/src/tokens/stream.rs
- assembly/src/tokens/tokenizer.rs
This commit introduces [SourceLocation], a structure linked to a [Token] via [TokenStream].
It will allow the link between a MASM source and a parsed [Operation].
related issue: https://github.com/0xPolygonMiden/miden-vm/issues/857
> feat: add assembly SourceLocation

- docs/src/design/chiplets/hasher.md
- docs/src/design/decoder/constraints.md
- docs/src/design/decoder/main.md
- docs/src/design/stack/op_constraints.md
- docs/src/design/stack/stack_ops.md
- docs/src/design/stack/system_ops.md
- docs/src/user_docs/assembly/io_operations.md
This PR adds usage of half-open intervals `[a, b)` in documentation.
To keep consistency, not only `a..b` was changed, but also `{a, ..., b}` .
> Use half-open intervals in documentation

- core/src/lib.rs
- processor/src/advice/inputs.rs
- processor/src/advice/mod.rs
This PR introduces three methods on the `AdviceInputs` struct.  These methods allow the `AdviceInputs` struct to be extended without it being consumed. This supports our efforts to introduce and implement `AdviceInputsBuilder` and `ToAdviceInputs` traits in `miden-base`.
> Add public mutators to `AdviceInputs` struct

- miden/src/cli/data.rs
This PR modifies the invocation of the `SimpleSmt::with_leaves(..)` constructor to support the new api.  We will use this branch to prepare downstream branches (`midne-base`) for the new `SimpleSmt` api.
> chore: specify simple-smt branch for crypto crate

- stdlib/asm/crypto/stark/random_coin.masm
Review/Merge after #897 
This saves the trace_length to memory so that it can later be used to compute the periodic values.
> stark verifier: save trace length to memory

- assembly/src/lib.rs
- assembly/src/parsers/context.rs
- assembly/src/parsers/mod.rs
- assembly/src/parsers/tests.rs
Export the `assembly::procedures` and `assembly::parsers` modules.
This change is necessary because the Miden IR compiler needs those modules to generate assembly code.
> Export assembly submodules

- assembly/src/assembler/mod.rs
- assembly/src/library/masl.rs
- assembly/src/library/mod.rs
- assembly/src/library/tests.rs
- assembly/src/parsers/body.rs
- assembly/src/parsers/context.rs
- assembly/src/parsers/mod.rs
- assembly/src/parsers/nodes.rs
- assembly/src/parsers/serde/deserialization.rs
- assembly/src/parsers/serde/mod.rs
- assembly/src/parsers/serde/serialization.rs
- assembly/src/parsers/tests.rs
- assembly/src/tokens/location.rs
- assembly/src/tokens/mod.rs
- assembly/src/tokens/stream.rs
- stdlib/build.rs
This commit adds source location to parsed nodes, allowing the construction of source mapping.
It modifies the [Node] structure based on the discussion that took place here:
https://github.com/0xPolygonMiden/miden-vm/issues/866#issuecomment-1524230664
The implementation is slightly different than the one discussed as every instruction individually will contain a [SourceLocation] - it will be less expensive to store it like that instead of creating sets for each of the block variants.
The [SourceLocation] itself is a cheap type that will contain integers only.
This commit doesn't touch the serialization question for ModuleAst with SourceLocation. These additional bytes might be optional, and including them might be optional as they will consume additional production storage when they will …
> feat: add SourceLocation to Node

- assembly/src/assembler/context.rs
- assembly/src/assembler/mod.rs
- assembly/src/ast/mod.rs
- assembly/src/errors.rs
- assembly/src/tests.rs
This PR introduces the `build_cb_table(..)` method on the `Assembler` and modifies the signature of `compile_in_context(..)` such that it works with references of `ProgramAst`.
> Assembler: Introduce code block builder and refactor compile in context

- processor/src/chiplets/bitwise/mod.rs
- processor/src/chiplets/kernel_rom/mod.rs
- processor/src/chiplets/kernel_rom/tests.rs
- processor/src/trace/tests/chiplets/bitwise.rs
- processor/src/trace/tests/chiplets/memory.rs
This PR updates the kernel rom tests to check the chiplets bus communications. It also includes a fix for an error found during testing and some minor renaming for terminological consistency between chiplets
> update kernel rom tests

- docs/src/design/chiplets/bitwise.md
This PR removes documentation about request side from the [bitwise chiplet bus constraint](https://0xpolygonmiden.github.io/miden-vm/design/chiplets/bitwise.html#bitwise-chiplet-bus-constraints). Now documentation redirects user to the stack u32 operations where request side is described.
> Remove request side from bitwise chiplet bus constraint 

- assembly/src/ast/mod.rs
- assembly/src/ast/nodes/advice.rs
- assembly/src/ast/parsers/adv_ops.rs
- assembly/src/ast/parsers/mod.rs
- core/src/operations/decorators/advice.rs
- docs/src/user_docs/assembly/io_operations.md
- miden/tests/integration/operations/decorators/advice.rs
- processor/src/advice/mem_provider.rs
- processor/src/advice/source.rs
- processor/src/decorators/adv_stack_injectors.rs
- processor/src/decorators/mod.rs
- processor/src/errors.rs
This PR addresses #835 and #880 but introducing additional variants of `adv.push_mapval` instruction. Specifically:
- We add `adv.push_mapvaln` instruction to enable pushing the number of elements in a value list onto the advice stack.
- We allow parameterization of both `adv.push_mapval` and `adv.push_mapvaln` to specify the offset of the key on the stack.
Tasks:
> Add more variants for `adv.push_mapval` instruction

- core/Cargo.toml
- miden/tests/integration/air/chiplets/hasher.rs
- processor/src/advice/mem_provider.rs
- processor/src/chiplets/hasher/mod.rs
- processor/src/chiplets/hasher/tests.rs
- processor/src/chiplets/mod.rs
- processor/src/decorators/tests.rs
- processor/src/lib.rs
- processor/src/operations/crypto_ops.rs
- processor/src/trace/tests/hasher.rs
- stdlib/tests/collections/mmr.rs
- stdlib/tests/collections/smt.rs
- stdlib/tests/collections/smt64.rs
- stdlib/tests/crypto/fri/verifier_fri_e2f4.rs
- stdlib/tests/crypto/stark/verifier_recursive/channel.rs
This PR updates `miden-crypto` crypto dependency to the latest version. Right now this points to the `next` branch, but once the next version of `miden-crypto` is released, I'll update this to point to the crates.io version.
The main update is the change in the API of many Merkle structs to use `RpoDigest` instead of `Word`.
> Update miden-crypto dependency to the latest version

- stdlib/asm/crypto/stark/deep_queries.masm
In this particular case it is better to push the values to the stack instead of loading from memory.
> stark: pushing constants instead of loading from memory

- assembly/src/ast/mod.rs
- assembly/src/ast/serde.rs
- assembly/src/ast/tests.rs
- assembly/src/library/masl.rs
- assembly/src/library/mod.rs
Imports have added to ProgramAst and ModuleAst serialization and deserialization.
The struct `AstSerializationOptions` has been added to allow for serialization with or without imports. The serialization options are also serialized as a sort of header, so that deserialization can happen without knowing which options were used for serialization.
Serialization currently happens in two places elsewhere in the repo, and in a few tests. I have assumed that we don't want changes to the behavior in those places, so imports are not serialized from there. 
I'd like to add a couple of tests, but otherwise the code can be reviewed as is.
- Relevant …
> Serialize and deserialize imports in ProgramAst and ModuleAst

- stdlib/asm/crypto/fri/helper.masm
- stdlib/asm/crypto/stark/constants.masm
- stdlib/docs/constants_stark.md
- stdlib/docs/helper_fri.md
As the PR titles says. I'm going to changed https://github.com/0xPolygonMiden/miden-vm/pull/960 to compute the constant and save it here, but I needed a bit more detail about the stack state to do that.
Opening as a separated PR for an easier review.
> stark: additional documentation for generate_fri_parameters

- Cargo.toml
- assembly/src/ast/code_body.rs
- assembly/src/ast/nodes/advice.rs
- assembly/src/ast/nodes/mod.rs
- assembly/src/ast/nodes/serde/deserialization.rs
- assembly/src/ast/nodes/serde/mod.rs
- assembly/src/ast/parsers/labels.rs
- assembly/src/ast/parsers/mod.rs
- assembly/src/library/mod.rs
- assembly/src/library/path.rs
- processor/src/chiplets/aux_trace/bus.rs
- test-utils/src/lib.rs
This PR enables resolver 2 feature resolution. It is similar to #980 but is made against the `main` branch and fixes things in a slightly different way.
> Enable resolver 2

- processor/src/advice/mod.rs
- processor/src/advice/providers.rs
This PR introduces `get_mapped_values(..)` and `get_store_subset(..)` methods on the `AdviceProvider` trait and implements the methods for `BaseAdviceProvider`, `MemAdviceProvider` and `RecAdviceProvider`.
> feat: Extend `AdviceProvider` trait

- assembly/src/ast/imports.rs
- assembly/src/ast/invocation_target.rs
- assembly/src/ast/mod.rs
- assembly/src/ast/parsers/context.rs
- assembly/src/ast/parsers/mod.rs
- assembly/src/ast/tests.rs
- assembly/src/errors.rs
- assembly/src/library/masl.rs
- assembly/src/procedures/mod.rs
A map from procedure IDs of imported procedures to the procedure's name and module path has been added to `ProgramAst` and `ModuleAst`.
This map is needed for the MASM pretty-printer, because the instructions that represent calls to imported procedures only contain the procedure's ID and not its name. The procedure's ID is a hash, and it is therefore impossible to print the assembly for the call instruction without this map.
The map is populated during parsing as part of the `ParserContext`. Since the parser does not have access to the code of imported modules, only the procedures that are actually called are represented in the map. This also explains why the map is named `used_imported_procs`.  
Like the imports map, this new map can optionally be serialized when the AST is serialized. …
> Add map of imported procedures to AST structs

- assembly/src/assembler/span_builder.rs
- assembly/src/library/mod.rs
- miden/src/cli/bundle.rs
- miden/src/cli/mod.rs
- miden/src/main.rs
This adds a CLI command to compile masm files to a masl, useful for CLI users.
> cli: add command to compile libraries

- assembly/src/assembler/span_builder.rs
- assembly/src/library/mod.rs
Since we are using nightly, what clippy likes and dislikes changes from day to day.
This PR fixes a few things clippy is now unhappy about.
> chore: make clippy happy

- .github/dependabot.yml
This PR enables automated dependency updates built into GitHub.  That's useful for keeping up-to-date on security updates for example.
https://github.com/0xPolygonMiden/miden-vm/pull/1012 fixes the spurious clippy error we see here.
> chore: enable github's Dependabot

- assembly/src/ast/format.rs
- assembly/src/ast/imports.rs
- assembly/src/ast/mod.rs
- assembly/src/ast/nodes/format.rs
- assembly/src/ast/nodes/mod.rs
- assembly/src/library/path.rs
- assembly/src/procedures/mod.rs
A default formatter is added to `ProgramAst` and `ModuleAst`. The formatter acts as a pretty-printer for the AST, including indentation and procedure names rather than procedure indices/ids.
In order to perform indentation and to output legal assembly, a set of `Formattable` structs have been added. These keep track of the formatting context.
Call instructions are handled separately from other instructions, because the procedure indices and ids must be transformed into procedure names. 
No tests have been added at this stage, because the formatter will be tested when connected to the compiler. It might also be worthwhile to add a `-pp` or `-format` option to the command-line assembler - comments regarding this feature would be appreciated.
No documentation has been added, since this PR is …
> AST formatter/pretty-printer

- assembly/src/assembler/context.rs
- assembly/src/assembler/instruction/procedures.rs
- assembly/src/assembler/mod.rs
- assembly/src/assembler/procedure_cache.rs
- assembly/src/assembler/tests.rs
- assembly/src/errors.rs
- assembly/src/procedures/mod.rs
> Switch CallSet to track RpoDigests instead of ProcedureIds

- assembly/src/assembler/context.rs
- assembly/src/assembler/instruction/procedures.rs
- assembly/src/assembler/mod.rs
- assembly/src/assembler/procedure_cache.rs
- assembly/src/errors.rs
- assembly/src/lib.rs
- assembly/src/procedures/mod.rs
This PR refactors `ProcedureCache` to track procedures based on their MAST root (rather than ID) in procedure cache. It also introduces the concept of a `NamedProcedure` (same as previous `Procedure`) and keeps only basic metadata in the `Procedure` struct.
To be reviewed after #1017.
> Track procedures by their MAST root in procedure cache

- CHANGELOG.md
- assembly/src/assembler/context.rs
- assembly/src/assembler/instruction/procedures.rs
- assembly/src/assembler/mod.rs
- assembly/src/errors.rs
- assembly/src/library/mod.rs
- assembly/src/tests.rs
This PR addresses #918. Specifically, a flag has been added to `AssemblyContext` which specifies whether phantom calls are allowed.
Phantom calls are not allowed by default. To enable them, `AssemblyContext::with_phantom_calls` method should be used. Thus, only the methods which accept `AssemblyContext` can produce programs with phantom calls (these methods are `Assembler::compile_in_context()` and `Assembler::compile_module()`.
I did not enable this functionality for `Assembler::compile()` method as I wanted to avoid breaking changes in this PR. So, phantom calls are currently not allowed in programs compiled via this method.
To be reviewed after #1018.
> Allow the assembler to produce programs with phantom calls

- assembly/src/assembler/procedure_cache.rs
- assembly/src/tests.rs
This PR ensures that the `proc_id_map` in the `ProcedureCache` is updated when a MAST root collision is found.
Fixes: #1022
> Fix: Duplicate MAST root different procedure Id

- core/Cargo.toml
- processor/src/advice/inputs.rs
- processor/src/advice/providers.rs
This PR introduces the following changes:
- Introduces instance of `AdviceInputs` which exposes its internal fields.  Put this behind the `internals` feature flag.
- Refactor the finalizer of the `RecordingAdviceMap` to return (`AdviceInputs`, `MemAdviceProvider`) tuple.
- Implement `into_parts()` on `MemAdviceProvider` and `BaseAdviceProvider<SimpleAdviceMap, SimpleMerkleMap>`
> `AdviceProvider` finalisation refactoring

- CHANGELOG.md
- assembly/src/ast/parsers/constants.rs
- assembly/src/ast/parsers/mod.rs
- assembly/src/errors.rs
- assembly/src/tests.rs
- assembly/src/tokens/mod.rs
- docs/src/user_docs/assembly/code_organization.md
This PR implements basic arithmetic for constant values. Currently supported operations are `+`, `-`, `*`, `/`, and `//`, where `//` is the field division. Round parentheses are also supported.
> Implement basic arithmetic on constant values 

- CHANGELOG.md
- processor/src/chiplets/tests.rs
- processor/src/decoder/tests.rs
- processor/src/trace/mod.rs
- processor/src/trace/utils.rs
This PR implements `TraceInfo` struct which holds data about lengths of:
- Main trace
- Range checker trace
- Chiplets trace lengths: hasher, bitwise, memory, kernel ROM
- Maximum trace length 
- Final padded trace length
> Persist traces lengths in `ExecutionTrace`

- CHANGELOG.md
- assembly/src/ast/imports.rs
- assembly/src/errors.rs
- assembly/src/tests.rs
- assembly/src/tokens/mod.rs
- docs/src/user_docs/assembly/code_organization.md
Addressing #1020. Allows users to define an alias for the imported module. For eg.
```
use.std::math::u64->bigint
begin
push.1.0
push.2.0
exec.bigint::add
end
```
> feat: add support for module aliases

- docs/src/design/lookups/logup.md
The `alpha - v` term is being multiplied twice, when it should be
> $$
b \cdot (\alpha - x) \cdot (\alpha - v)
$$
instead.
> fix(docs): constraint expression multiplies same term twice

- CHANGELOG.md
- processor/src/chiplets/memory/mod.rs
- processor/src/chiplets/memory/segment.rs
- processor/src/chiplets/memory/tests.rs
- processor/src/chiplets/mod.rs
- processor/src/operations/io_ops.rs
This PR imposes the limitation on the memory addresses, allowing usage of the addresses only in range between `[0, 2^32]`. This leads to the error throwing in the `mem_load`, `mem_loadw`, `mem_store` and `mem_storew` instructions if an address stored on the top of the stack is greater that `u32::MAX`. 
Tasks:
> Impose limit on the memory addresses

- miden/src/cli/run.rs
- miden/tests/integration/cli/cli_test.rs
- processor/src/trace/utils.rs
- prover/src/lib.rs
This small PR improves the print of the cycles required for the each VM component. Currently it looks like so:
```
VM cycles: 3045 (stack: 3045, range checker: 39, chiplets: hash 336, bitwise 0, memory 0, kernel 0) extended to 4096 steps.
```
This PR closes issues #442 and #1047
> Print VM cycles after CLI execution

- assembly/src/assembler/mod.rs
- assembly/src/errors.rs
The existing error only prints the procid, so it is hard to figure out which procedure is missing. This change adds the procedure name to the error message as a clarification.
> Add details to reexport proc error

- assembly/src/ast/parsers/adv_ops.rs
- assembly/src/ast/parsers/io_ops.rs
- assembly/src/ast/parsers/mod.rs
- assembly/src/ast/parsers/stack_ops.rs
- assembly/src/errors.rs
- assembly/src/tests.rs
- assembly/src/tokens/mod.rs
Fixes the issue raised in issue #843.
Introduced a few new parameters in the function `missing_param` in `assembly/src/errors.rs` namely `minimum_expected_params`, `maximum_expected_params`, and `param_description`. The error message would also contain the value of the actual number of parameters. This should help the developers to know how many parameters are expected, how many are missing, and what are they used for and debug their case faster.
> missing params descriptive error message

- assembly/src/assembler/context.rs
- assembly/src/assembler/mod.rs
- assembly/src/ast/mod.rs
- assembly/src/errors.rs
- assembly/src/lib.rs
- assembly/src/tests.rs
- miden/src/examples/fibonacci.rs
This PR adds procedure name to the `ImportedProcModuleNotFound` error, so now it will look like so: 
```
ImportedProcModuleNotFound(
ProcedureName { name: "foo" }, 
ProcedureId([76, 6, 174, 102, 136, 197, 185, 191, 0, 2, 63, 207, 185, 182, 172, 255, 235, 226, 6, 56])
)
```
> Improve error `ImportedProcModuleNotFound`

- assembly/src/assembler/context.rs
- assembly/src/assembler/mod.rs
- assembly/src/tests.rs
This PR makes `ProgramAst` parameter for `AssemblyContext::from_program()` constructor optional. This resolves an inconvenience referenced in https://github.com/0xPolygonMiden/miden-base/pull/236#discussion_r1321868388.
> Make `ProgramAst` parameter for `AssemblyContext` optional

- CHANGELOG.md
- assembly/src/assembler/instruction/mod.rs
- assembly/src/assembler/span_builder.rs
- assembly/src/ast/nodes/mod.rs
- assembly/src/ast/nodes/serde/debug.rs
- assembly/src/ast/nodes/serde/deserialization.rs
- assembly/src/ast/nodes/serde/mod.rs
- assembly/src/ast/nodes/serde/serialization.rs
- assembly/src/ast/parsers/context.rs
- assembly/src/ast/parsers/debug.rs
- assembly/src/ast/parsers/mod.rs
- core/src/lib.rs
- core/src/operations/decorators/debug.rs
- core/src/operations/decorators/mod.rs
- core/src/operations/mod.rs
- core/src/program/blocks/span_block.rs
- docs/src/SUMMARY.md
- docs/src/user_docs/assembly/debugging.md
- miden/Cargo.toml
- miden/src/cli/run.rs
- processor/src/decorators/mod.rs
- processor/src/lib.rs
- processor/src/stack/mod.rs
This PR implements a basic variant of `Debug` decorator mentioned in https://github.com/0xPolygonMiden/miden-vm/issues/988#issuecomment-1711099264. Specifically, this decorator can print out only the state of the stack (i.e., functionality to print out memory or procedure locals is left to future PRs).
> Implement basic Debug decorator

- CHANGELOG.md
- assembly/src/ast/parsers/io_ops.rs
- assembly/src/ast/tests.rs
- docs/src/user_docs/assembly/io_operations.md
- miden/tests/integration/operations/io_ops/constant_ops.rs
This PR changes how `push.*` instruction is parsing long hex strings. Earlier hex string was parsed as if it was created from big-endian bytes, but now we assume that it was created from little-endian bytes (since it was actually created like that).
This change fixes an [issue](https://github.com/0xPolygonMiden/miden-vm/issues/993#issuecomment-1721673702) when  hex strings were created form little-endian bytes array, but were parsed as string created from big-endian bytes, making unavailable to use printed he strings as inputs to the VM.
Todo:
> Make `push` instruction parse hex strings in little-endian

- miden/examples/merkle_store/merkle_store.masm
It turns out that after some PRs merged this example stops working properly. After the investigation I couldn't figure out how it even worked before, because it wasn't supposed to — `assert_eq` operation was used incorrectly and also the order of elements on the stack was incorrect (as if `mtree_get` was putting a word on the stack in a different order). I am sure that it was working, but now I can't neither remember, nor understand how. 
Anyway, this small PR fixed this example, so now it works fine.
> Fix the Merkle Store example

- assembly/src/assembler/context.rs
- assembly/src/assembler/mod.rs
- assembly/src/assembler/procedure_cache.rs
- assembly/src/ast/mod.rs
- assembly/src/library/path.rs
- assembly/src/procedures/mod.rs
- assembly/src/tests.rs
This PR makes it possible to compile `Module` with no `LibraryPath` provided. As a result of this `NamedProcedure` now can be created without `id`.
Tasks:
> Enable compiling modules without library paths

- .github/workflows/ci.yml
- Makefile
- air/Cargo.toml
- assembly/Cargo.toml
- core/Cargo.toml
- miden/Cargo.toml
- processor/Cargo.toml
- processor/src/chiplets/bitwise/tests.rs
- processor/src/chiplets/hasher/tests.rs
- processor/src/decoder/tests.rs
- processor/src/operations/crypto_ops.rs
- processor/src/operations/ext2_ops.rs
- processor/src/operations/field_ops.rs
- processor/src/operations/fri_ops.rs
- processor/src/operations/u32_ops.rs
- processor/src/range/tests.rs
- processor/src/trace/decoder/tests.rs
- processor/src/trace/tests/chiplets/mod.rs
- processor/src/trace/tests/mod.rs
- processor/src/trace/tests/range.rs
- prover/Cargo.toml
- stdlib/Cargo.toml
- test-utils/Cargo.toml
This PR adds Graviton compilation target to the makefile. When compiling to this target we enable `sve` feature on `miden-crypto` recently introduced in https://github.com/0xPolygonMiden/crypto/pull/190.
I also bumped up minimum `rustc` version to 1.73 (this should address #917) and generally cleaned up `.toml` files a bit.
The time it takes to generate a proof for a program taking $2^{20}$ cycles on a 64-core Graviton3 instance:
| Hash function used | SVE acceleration | Time (seconds)  | Implied frequency | Baseline multiple |
| ------------------ | :--------------: | :-------------: | :---------------: | :---------------: |
| BLAKE3             | No               | 3.9             | 268 KHz           | 1x                |
| RPO256             | No               | 22.1            | 47 …
> Graviton compilation target

- miden/Cargo.toml
- miden/src/tools/mod.rs
- processor/src/debug.rs
- processor/src/lib.rs
- processor/src/trace/utils.rs
This PR adds extended information about traces lengths of VM components to the `analyze` tool output.
> Improve cycles output in `analyze` tool

- CHANGELOG.md
- assembly/src/assembler/mod.rs
- assembly/src/ast/mod.rs
- miden/src/cli/compile.rs
- miden/src/cli/data.rs
- miden/src/cli/debug/mod.rs
- miden/src/cli/prove.rs
- miden/src/cli/run.rs
- miden/src/lib.rs
Closes #1098 
Adds the procedure `write_to_file` into `ProgramAst` Struct to allow reading standard note scripts, e.g., P2ID and P2IDR, see https://github.com/0xPolygonMiden/miden-base/pull/269
> Writing `ProgramAst` into files 

- assembly/src/library/masl.rs
This PR exposes `MaslLibrary::new` to consumers of the `miden-assembly` crate. In particular, I plan to use this from the compiler to emit multi-module libraries to disk. I didn't observe any particular reason why this function was kept crate-local, since it is a safe API to call, so just assumed there hadn't been a need for it yet.
> feat(assembly): allow creation of masl libraries via api

- CHANGELOG.md
- stdlib/asm/collections/smt.masm
- stdlib/asm/collections/smt64.masm
- stdlib/asm/utils.masm
- stdlib/docs/utils.md
This PR introduces a `std::utils` assembly module whose purpose is to hold utility methods.  It has initially been created with the `is_empty_word` method.  Usage of this procedure have been replaced in the std library.
> Introduce `std::utils` assembly module

- assembly/src/assembler/context.rs
- assembly/src/ast/imports.rs
- assembly/src/ast/mod.rs
- assembly/src/library/masl.rs
This PR contains two related changes:
1. Changed the `import_info` fields of ProgramAst and ModuleAst to remove the `Option` wrapper.
Wrapping this field in an `Option` does not appear to serve a specific purpose, and actively hinders/complicates access to module import information in the AST. As a result of this, there was a number of places where code to access common import info was duplicated; and a couple of places where a panic would be raised when an empty import table would be a suitable fallback.
After this change, one can access the `ModuleImports` struct directly on both `ProgramAst` and `ModuleAst` via the `import_info` function, which returns a reference to the field. Redundant functions in both structs were removed if they are already provided by `ModuleImports`.
2. Added …
> feat: improve ergonomics of/access to module import info apis

- docs/src/design/chiplets/bitwise.md
The sentence describing the column $k_0$ had its order reversed, and the
table headers were incorrectly named as $x_i$ and $y_i$ instead of $a_i$
and $b_i$ as described in the introduction.
> docs(mdbook): minor change in the bitwise chiplet

- CHANGELOG.md
- assembly/src/ast/mod.rs
- assembly/src/ast/nodes/serde/debug.rs
- assembly/src/ast/parsers/context.rs
- assembly/src/ast/parsers/debug.rs
- core/src/operations/decorators/debug.rs
- docs/src/user_docs/assembly/debugging.md
- miden/examples/debug/debug.inputs
- miden/examples/debug/debug.masm
- processor/src/host/debug.rs
- processor/src/host/mod.rs
- processor/src/lib.rs
- stdlib/docs/utils.md
This PR expands the capabilities of the `debug` instruction by printing information about memory and procedure locals, namely:
- `debug.mem` prints out the entire contents of RAM.
- `debug.mem.<n>` prints out contents of memory at address `n`.
- `debug.mem.<n>.<m>` prints out the contents of memory starting at address `n` and ending at address `m` (both inclusive). `m` must be greater than `n`.
- `debug.local` prints out all locals of the currently executing procedure.
- `debug.local.<n>` prints out contents of the local at index `n` for the currently executing procedure.
- `debug.local.<n>.<m>` prints out contents of the local starting at index `n` and ending at index `m` (both inclusive). `m` must be greater than `n`.
TODO:
> Expand capabilities of the `debug` instruction

- docs/src/design/decoder/main.md
Proposes minor fixes to the decoder docs.
> Minor doc fixes

- miden/src/repl/mod.rs
- miden/tests/integration/exec_iters.rs
- processor/Cargo.toml
- processor/src/chiplets/memory/mod.rs
- processor/src/chiplets/memory/tests.rs
- processor/src/chiplets/mod.rs
- processor/src/debug.rs
- processor/src/decoder/aux_hints.rs
- processor/src/decoder/block_stack.rs
- processor/src/decoder/tests.rs
- processor/src/host/debug.rs
- processor/src/lib.rs
- processor/src/operations/io_ops.rs
- processor/src/system/mod.rs
- stdlib/tests/mem/mod.rs
- test-utils/src/lib.rs
Creates the `ContextId` type instead of using `u32` everywhere. This makes the code easier to understand to a newcomer; e.g. types such as `(u32, u32, u32)` make understanding the code harder. And this newtype will also prevent bugs which e.g. use the context ID as an address (who's also a `u32`).
I suggest we also introduce a newtype for memory `Address`.
> Memory: Create newtype `ContextId`

- CHANGELOG.md
- air/Cargo.toml
- air/src/options.rs
- core/Cargo.toml
- core/src/random.rs
- core/src/utils/mod.rs
- miden/Cargo.toml
- miden/tests/integration/air/range.rs
- miden/tests/integration/cli/cli_test.rs
- processor/Cargo.toml
- processor/src/lib.rs
- prover/Cargo.toml
- prover/src/gpu.rs
- prover/src/lib.rs
- stdlib/Cargo.toml
- stdlib/tests/collections/mmr.rs
- stdlib/tests/crypto/fri/verifier_fri_e2f4.rs
- stdlib/tests/crypto/stark/verifier_recursive/channel.rs
- stdlib/tests/crypto/stark/verifier_recursive/mod.rs
- test-utils/Cargo.toml
- test-utils/src/lib.rs
- verifier/Cargo.toml
- verifier/src/lib.rs
As the title says though probably does  not  include the best way to use the `AcceptableOption` argument. 
I also had to make on modification to the `cli` test as well as some changes to the MMR tests as well. Probably the problems forcing those changes were due to some rebasing issues.
> Migrate to using Winterfell 0.7

- processor/src/errors.rs
This PR introduces the `EventError` variant for the `ExecutionError` enum. The `EventError` contains a `String`, this data model has been used as the `processor` crate need to know the error type as compile time.  This means we must either define the `EventError` type in the `processor` crate or alternatively use a generic on the `ExecutionError` enum. I decided not to define the `EventError` type in the `processor` crate as it would be leaking application logic into the virtual machine.
> Introduce `EventError`

- CHANGELOG.md
- assembly/src/ast/mod.rs
- assembly/src/ast/parsers/context.rs
- assembly/src/ast/parsers/mod.rs
- assembly/src/ast/tests.rs
- assembly/src/tests.rs
- assembly/src/tokens/mod.rs
- docs/src/user_docs/assembly/flow_control.md
This small PR adds support for constants used as counters in repeat loops.
For example:
```
const.A=3
begin 
repeat.A
push.1
end
end
```
> Support constants in MASM `repeat` loops

- stdlib/tests/collections/mmr.rs
breaking changes introduced by https://github.com/0xPolygonMiden/crypto/pull/210
> crypto: update api

- assembly/src/ast/imports.rs
- core/src/program/blocks/call_block.rs
- core/src/program/blocks/dyn_block.rs
- core/src/program/blocks/join_block.rs
- core/src/program/blocks/loop_block.rs
- core/src/program/blocks/mod.rs
- core/src/program/blocks/proxy_block.rs
- core/src/program/blocks/span_block.rs
- core/src/program/blocks/split_block.rs
- core/src/stack/inputs.rs
- processor/src/errors.rs
- processor/src/host/advice/inputs.rs
This is helpful for tests. For example we can write a succinct
```rust
assert_eq!(result, Err(ExecutionError::Variant(vec![x,y,z])));
```
instead of 
```rust
match result {
Ok(_) => panic!(""),
Err(err) => match err {
Variant(v) => assert_eq!(v, vec![x,y,z]),
_ => panic!("")
}
}
```
> Derive `PartialEq, Eq` for `ExecutionError`

- assembly/src/assembler/instruction/u32_ops.rs
- docs/src/user_docs/assembly/u32_operations.md
This small PR updates the cycle count in the documentation of the `shl`, `shr`, `rotl` and `rotr` instructions.
> Update u32 shift and rotate instructions' docs

- CHANGELOG.md
- core/src/stack/outputs.rs
Followup to discussions in https://github.com/0xPolygonMiden/miden-vm/pull/1146
> `StackOutputs`: `get_stack_{item, word}()` methods

- CHANGELOG.md
- docs/src/tools/repl.md
- miden/src/cli/repl.rs
- miden/src/repl/mod.rs
This PR makes it possible to specify libraries to be used in the REPL programs. It also introduces the `!use` command for Miden REPL. This command could be used with or without parameter. 
- If `!use` command is used without parameters, it prints all modules available for import to the program.
- If `!use` command is used with parameter, it imports the provided module to the program.
> Support libraries in Miden REPL

- assembly/src/assembler/instruction/procedures.rs
- docs/src/user_docs/assembly/code_organization.md
- miden/tests/integration/flow_control/mod.rs
This small PR makes it possible to use dynamic instructions (`dyncall` and `dynexec`) after `procref` instruction, without using `call` or `syscall` as it was explained in the #1150 issue.
> Use dynamic calls after `procref`

- core/src/errors.rs
- core/src/stack/inputs.rs
- processor/src/operations/ext2_ops.rs
- processor/src/operations/fri_ops.rs
Adds deserialization to the stack inputs
> Stack inputs serde

- core/src/errors.rs
- core/src/stack/outputs.rs
> stackoutputs: add deserializer and size validation

- CHANGELOG.md
- docs/src/intro/usage.md
- miden/Cargo.toml
- miden/src/examples/blake3.rs
- miden/src/examples/mod.rs
This PR introduces new internal example: sequential calculation of 1-to-1 BLAKE3 hash. 
As well as the fibonacci example it could be used with `example` subcommand:
```
./target/optimized/miden example [name]
```
> Implement internal BLAKE3 hashing example

- CHANGELOG.md
- assembly/Cargo.toml
- assembly/src/assembler/mod.rs
- assembly/src/ast/mod.rs
- assembly/src/ast/module.rs
- assembly/src/ast/program.rs
- assembly/src/library/masl.rs
- assembly/src/library/path.rs
- docs/src/intro/usage.md
- miden/Cargo.toml
- miden/src/cli/data.rs
- miden/src/cli/debug/mod.rs
- miden/src/cli/prove.rs
- miden/src/cli/run.rs
- miden/src/cli/verify.rs
- miden/src/examples/mod.rs
- miden/src/main.rs
- processor/Cargo.toml
- processor/src/lib.rs
- prover/Cargo.toml
- prover/src/gpu.rs
- prover/src/lib.rs
- verifier/Cargo.toml
- verifier/src/lib.rs
This PR implements [Tracing](https://docs.rs/tracing/latest/tracing/index.html#) logger for the Miden VM.
TODO:
> Add logging to the assembler

- CHANGELOG.md
- air/src/constraints/stack/op_flags/mod.rs
- air/src/constraints/stack/system_ops/tests.rs
- assembly/src/assembler/instruction/ext2_ops.rs
- assembly/src/assembler/instruction/field_ops.rs
- assembly/src/assembler/instruction/mod.rs
- core/src/operations/mod.rs
- miden/tests/integration/operations/sys_ops.rs
- processor/src/errors.rs
- processor/src/host/mod.rs
- processor/src/operations/sys_ops.rs
This small PR adds an `on_assert_failed()` method to the `Host` trait as it was proposed in the [related issue](https://github.com/0xPolygonMiden/miden-vm/issues/1188).
As a subtask the error code type was changed from `Felt` to `u32`.
> Add `on_assert_failed()` method to the Host trait

- CHANGELOG.md
- assembly/src/ast/parsers/io_ops.rs
- assembly/src/ast/parsers/mod.rs
- assembly/src/tests.rs
- docs/src/user_docs/assembly/code_organization.md
This small PR adds support for hexadecimal values in constants, e.g.
```
const.TEST_CONSTANT=0xFF
```
> Support hexadecimal literals in constants

- core/Cargo.toml
- core/src/lib.rs
- miden/src/cli/data.rs
- stdlib/tests/collections/mod.rs
- stdlib/tests/collections/smt64.rs
- test-utils/src/crypto.rs
Fixes build after https://github.com/0xPolygonMiden/crypto/pull/245
> Fix build after `SimpleSmt` change in miden-crypto

- processor/src/stack/aux_trace.rs
- processor/src/stack/mod.rs
- processor/src/stack/overflow.rs
- processor/src/stack/tests.rs
- processor/src/trace/tests/stack.rs
This PR cleans up a little auxiliary column code generator for the stack overflow table.
Specifically:
- Moved some functions inline when the body of a function contains just a single function call.
- Used `OverflowTableRow::to_value()` method to compute aux request/responses.
- Removed `OverflowTable.update_trace` field since it is no longer needed.
We can further simplify the `OverflowTable` struct by not tracking all overflow table rows and instead tracking only current ones. But I didn't do this in this PR.
> Clean up aux column generator for stack overflow table

- air/Cargo.toml
- air/src/trace/main_trace.rs
- processor/Cargo.toml
- processor/src/chiplets/aux_trace/mod.rs
- processor/src/chiplets/mod.rs
- processor/src/chiplets/tests.rs
- processor/src/decoder/auxiliary.rs
- processor/src/decoder/tests.rs
- processor/src/range/aux_trace.rs
- processor/src/range/mod.rs
- processor/src/range/request.rs
- processor/src/stack/aux_trace.rs
- processor/src/stack/mod.rs
- processor/src/trace/mod.rs
- processor/src/trace/tests/hasher.rs
- processor/src/trace/utils.rs
- prover/src/gpu.rs
- Implement Deref for MainTrace to &ColMatrix
- Remove lifetime annotation from Maintrace
- new method now takes in ColMatrix as opposed to &ColMatrix
- Replace &ColMatrix with &MainTrace  
relevant issue: #1201
> refactor: Deref `MainTrace` type to `ColMatrix`

- processor/src/errors.rs
- processor/src/operations/crypto_ops.rs
Converts a `panic!()` into an error when Merkle Path verification fails.
> `mpverify`: don't panic when verification fails

- air/src/trace/main_trace.rs
- docs/src/design/stack/crypto_ops.md
- docs/src/design/stack/op_constraints.md
- processor/src/chiplets/aux_trace/mod.rs
- processor/src/operations/comb_ops.rs
Updates the bus to handle the two memory requests made by `RCOMBBASE` and updates docs.
> Handle additional memory requests made by `RCOMBBASE`

- core/Cargo.toml
This small PR updates the `miden-crypro` dependency to the version 0.8.
> Update `miden-crypto` to v0.8

- processor/src/operations/comb_ops.rs
- stdlib/tests/crypto/falcon.rs
- test-utils/src/lib.rs
> Falcon test prove-verify

- assembly/src/ast/parsers/io_ops.rs
Fix TryFrom warning:
```
warning: the item `TryFrom` is imported redundantly
--> assembly/src/ast/parsers/io_ops.rs:9:12
|
9   | use core::{convert::TryFrom, ops::RangeBounds};
|            ^^^^^^^^^^^^^^^^
|
::: /Users/hack/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/prelude/mod.rs:129:13
|
129 |     pub use core::prelude::rust_2021::*;
|             ------------------------ the item `TryFrom` is already defined here
```
> Fix tryfrom tryinto warnings

- assembly/src/assembler/instruction/crypto_ops.rs
- processor/src/host/advice/injectors/adv_map_injectors.rs
- processor/src/host/advice/mod.rs
This small PR changes the doc comments related to `mtree_merge` instruction.
It removes any comments about returning an error if provided roots are not in the advice provider (since we don't return it).
> Update `mtree_merge` doc comments

- CHANGELOG.md
- air/src/constraints/stack/mod.rs
- assembly/src/ast/imports.rs
- processor/src/host/advice/mod.rs
- processor/src/host/advice/providers.rs
This small PR removes unused `find_lone_leaf()` function from the Advice Provider.
> Remove `find_lone_leaf()`

- miden/Cargo.toml
- miden/README.md
- miden/benches/program_execution.rs
- miden/src/cli/data.rs
- miden/src/cli/debug/executor.rs
- miden/src/cli/prove.rs
- miden/src/cli/verify.rs
- miden/src/examples/blake3.rs
- miden/src/examples/fibonacci.rs
- miden/src/examples/mod.rs
- miden/src/main.rs
- miden/src/repl/mod.rs
- miden/src/tools/mod.rs
- miden/tests/integration/flow_control/mod.rs
As per the PR title. This makes the library crate name match the package name.
> miden-vm: match the crate with the package name. Fix #1270

- CHANGELOG.md
- core/src/errors.rs
- core/src/stack/inputs.rs
- core/src/stack/mod.rs
- core/src/stack/outputs.rs
- miden/README.md
- miden/src/cli/data.rs
- miden/src/examples/blake3.rs
- miden/src/examples/fibonacci.rs
- miden/src/examples/mod.rs
- processor/src/lib.rs
- processor/src/stack/mod.rs
- prover/README.md
- test-utils/src/lib.rs
This PR updates the fields of `StackOutputs` struct. 
It changes them from `Vec<u64>` to `Vec<Felt>` to make them consistent with the stack values.
> Update `StackOutputs` fields

- CHANGELOG.md
- core/src/errors.rs
- core/src/program/mod.rs
- core/src/stack/inputs.rs
- core/src/stack/outputs.rs
- miden/README.md
- miden/src/cli/data.rs
- miden/src/examples/blake3.rs
- miden/src/examples/fibonacci.rs
- miden/src/tools/mod.rs
- miden/tests/integration/flow_control/mod.rs
- miden/tests/integration/operations/io_ops/env_ops.rs
- processor/src/chiplets/tests.rs
- processor/src/decoder/tests.rs
- processor/src/operations/comb_ops.rs
- processor/src/operations/crypto_ops.rs
- processor/src/operations/ext2_ops.rs
- processor/src/operations/field_ops.rs
- processor/src/operations/fri_ops.rs
- processor/src/operations/stack_ops.rs
- processor/src/operations/sys_ops.rs
- processor/src/operations/u32_ops.rs
- processor/src/stack/tests.rs
- processor/src/trace/tests/chiplets/hasher.rs
- processor/src/trace/tests/hasher.rs
- processor/src/trace/tests/mod.rs
- stdlib/tests/crypto/falcon.rs
- stdlib/tests/crypto/stark/mod.rs
- test-utils/src/lib.rs
- test-utils/src/test_builders.rs
This PR changes the serialization and deserialization method of `usize` values to `write_usize()` and `read_usize()` respectively.
> Update `usize` serialization and deserialization 

- docs/src/user_docs/assembly/field_operations.md
fix typo: filed to field
found a typo when reading the docs
> fix typo in docs

- air/src/options.rs
- processor/src/host/mod.rs
- processor/src/lib.rs
This PR allows enabling of debug mode via `ExecutionOptions`. This, in turn, allows us to execute programs in debug mode via `processor::execute()` function - something that is needed to enable more streamlined debugging for users.
This PR is made against the `main` branch because this is a non-breaking change that we would like to release sooner rather than later as we want to propagate it to the transaction executor in `miden-base`.
> Allow enabling debug mode via `ExecutionOptions`

- CHANGELOG.md
- stdlib/asm/crypto/hashes/native.masm
Adds a procedure to initialize the stack with the native hasher initial state. This only covers the case without the need for padding.
Related to https://github.com/0xPolygonMiden/miden-vm/issues/1311
> stdlib: adds native hasher init procedure without padding

- assembly/build.rs
- assembly/src/ast/ident.rs
- assembly/src/ast/procedure/name.rs
- stdlib/build.rs
This was overlooked when merging the assembler refactoring, but is required by the compiler, as it is working directly with the AST in memory, rather than parsing MASM text.
Callers are expected to uphold the validity requirements of bare/quoted identifiers when using these APIs, but failure to do so doesn't really matter that much, aside from breaking the ability to round-trip code containing the invalid identifier through the text format (and making it all but impossible to reference from other code). As a result, I don't really see a need to treat these as particularly dangerous functions, so I haven't marked them `unsafe` (not that there is any potential for them to be unsafe in Rust terms, but occasionally `unsafe` is useful for flagging things that you want to be _really_ sure are …
> fix: support creation of raw identifiers when working with AST in memroy

- assembly/src/assembler/mod.rs
- stdlib/build.rs
This small PR removes the usage of `group_vector_elements()` function from `combine_blocks()` function which was causing issues in WASM compilation in the newer versions of Rust compiler (and `group_vector_elements()` is removed from Winterfell versions v0.9.0 and later).
> Remove usage of group_vector_elements() from combine_blocks()

- CHANGELOG.md
- assembly/src/assembler/instruction/field_ops.rs
- assembly/src/assembler/instruction/mod.rs
- assembly/src/ast/instruction/deserialize.rs
- assembly/src/ast/instruction/mod.rs
- assembly/src/ast/instruction/opcode.rs
- assembly/src/ast/instruction/print.rs
- assembly/src/ast/instruction/serialize.rs
- assembly/src/ast/visit.rs
- assembly/src/parser/grammar.lalrpop
- docs/src/user_docs/assembly/field_operations.md
- miden/tests/integration/operations/field_ops.rs
This PR makes it possible to use `lt`, `lte`, `gt` and `gte` comparison instructions with an immediate values.
Related issue: #1326
> Support the immediate values for `lt`, `lte`, `gt` and `gte` comparison instructions

- rust-toolchain.toml
This PR adds a `rust-toolchain.toml` file, which ensures that default Rust toolchain commands use the configured toolchain, rather than whatever the global toolchain on your machine happens to be. In this case, I've configured to use `1.78` explicitly.
So when you run, say, `cargo check`, this will ensure that the given Rust toolchain is installed, along with the configured targets and components, and will use that toolchain to run the given command. This applies to all Rust toolchain binaries, e.g. `rustc`, `clippy`, and so on.
If you wish to compile with `nightly`, simply run `cargo +nightly check` or whatever.
This also ensures that when CI runs, it uses the same toolchain as we are using locally (again, unless explicitly overridden, such as when specifying `nightly` as the toolchain …
> ci: add rust-toolchain.toml

- assembly/src/assembler/mod.rs
- assembly/src/assembler/module_graph/mod.rs
- assembly/src/assembler/module_graph/name_resolver.rs
- assembly/src/assembler/module_graph/procedure_cache.rs
- assembly/src/assembler/tests.rs
- assembly/src/ast/instruction/print.rs
- assembly/src/ast/invocation_target.rs
- assembly/src/ast/module.rs
- assembly/src/ast/procedure/alias.rs
- assembly/src/ast/procedure/mod.rs
- assembly/src/ast/procedure/name.rs
- assembly/src/ast/procedure/resolver.rs
- assembly/src/parser/error.rs
- assembly/src/parser/grammar.lalrpop
- assembly/src/parser/lexer.rs
- assembly/src/sema/mod.rs
- assembly/src/sema/passes/verify_invoke.rs
- docs/src/user_docs/assembly/code_organization.md
This PR does two things:
* Adds syntax for specifying absolute paths to procedures/modules in MASM, specifically, prefixing a path with `::` (just like in Rust) will treat the resulting path as absolute and fully-qualified, regardless of imports or other context.
* Ensures absolute paths are handled correctly throughout the assembler. Some support already existed, but was not complete due to lack of frontend implementation.
Additionally, it fixes some bugs with the current frontend around procedure paths and special namespaces.
When absolute paths are used, one does not need to explicitly import the module containing the referenced item, as there is no need for an import when the dependency is explicit.
**NOTE:** Due to uniformity of syntax representation in the parser, it is now possible …
> feat: support absolute module/procedure paths

- assembly/src/assembler/instruction/mem_ops.rs
- assembly/src/tests.rs
This small PR adds an underflow check in the [local_to_absolute_addr](https://github.com/0xPolygonMiden/miden-vm/blob/ddf536cd7157053f0940d7be41998b2a6546b4c1/assembly/src/assembler/instruction/mem_ops.rs#L110) function and return of proper error message instead of panic "subtract with underflow" one.
Related issue: #1372
> Return proper message at underflow

- air/src/constraints/stack/op_flags/mod.rs
- assembly/src/assembler/instruction/mod.rs
- assembly/src/assembler/instruction/u32_ops.rs
- core/src/mast/serialization/basic_block_data_builder.rs
- core/src/mast/serialization/basic_block_data_decoder.rs
- core/src/mast/serialization/tests.rs
- core/src/operations/mod.rs
- processor/src/operations/u32_ops.rs
This small PR changes the internal value type (type of error code) of the `u32assert2` operation from `Felt` to `u32`.
Related issue: #1381
> Change the type of the error code of `u32assert2` operation from `Felt` to `u32`

- processor/src/lib.rs
While doing some testing in the compiler where I wanted to set up some VM state and then execute a program on that state, I realized that there is no currently public API that allows one to access the state of the process to do so, short of using the `internals` feature flag of the crate.
Rather than requiring the use of that flag, this commit instead makes public the [Process] struct, but with all of its fields private unless the `internals` flag is enabled. This makes it possible to use the public APIs of the various traits implemented by `Process` to interact with it in a more fine-grained fashion.
It is still expected that most people will use the `execute` or `execute_iter` APIs, but this makes it possible to take control over that yourself when necessary/useful. I should also note …
> feat(processor): expose the process api

- processor/src/trace/mod.rs
Missed this when making `Process` public, but it is necessary to be able to construct an `ExecutionTrace` when you manually construct/execute a `Process`.
> feat(processor): allow public construction of execution trace

- processor/src/debug.rs
Sorry for the noise, but found another API that should be public connected to `Process`. I _think_ this is the last one, but if you have any thoughts on others I may run into as I work through testing in the compiler, let me know.
> feat(processor): allow public construction of vm state iterator

- .github/workflows/changelog.yml
In this PR I propose to add a warning if the `CHANGELOG.md` file has not been modified.
> Throw warning if `CHANGELOG.md` file has not been modified

- .github/workflows/changelog.yml
- .github/workflows/lint.yml
- CHANGELOG.md
- scripts/check-changelog.sh
In this PR I add a `changelog.yml` file. 
This should solve this issue of failing `changelog` CI job on push to `next` or `main`. 
My rationale is that the `CHANGELOG.md` file is considered modified when the PR is still opened but on merge this job should not be ran because the PR context does not exist anymore.
It also adds logic to support the `no changelog` label that can be put on a PR that does not require an update in the `CHANGELOG.md` file.
Once this PR is merged and we confirmed it's functionality I will port these changes to the:
- Node
- Base
And then follow your recommendations regarding other repositories.
> Add `changelog.yml` file

- CHANGELOG.md
- assembly/src/assembler/basic_block_builder.rs
- assembly/src/assembler/instruction/procedures.rs
- assembly/src/assembler/mast_forest_builder.rs
- assembly/src/assembler/mod.rs
- assembly/src/assembler/tests.rs
- assembly/src/errors.rs
- core/Cargo.toml
- core/src/mast/mod.rs
- core/src/mast/serialization/mod.rs
- core/src/mast/serialization/tests.rs
- miden/tests/integration/operations/io_ops/env_ops.rs
- processor/src/chiplets/hasher/tests.rs
- processor/src/chiplets/tests.rs
- processor/src/decoder/tests.rs
- processor/src/trace/tests/chiplets/hasher.rs
- processor/src/trace/tests/decoder.rs
- processor/src/trace/tests/mod.rs
Closes #1392
* Enforce invariant that MastForest node length is < 2^30
* Return errors from add_node() and enforce_node()
* Map errors to AssemblyError
> MastForest maximum node length invariant

- CHANGELOG.md
- assembly/src/assembler/basic_block_builder.rs
- assembly/src/assembler/instruction/procedures.rs
- assembly/src/assembler/mast_forest_builder.rs
- assembly/src/assembler/mod.rs
- assembly/src/assembler/tests.rs
- core/src/mast/node/mod.rs
- core/src/mast/serialization/info.rs
- core/src/mast/serialization/tests.rs
- processor/src/decoder/tests.rs
Closes #1355
Add methods to`MastForestBuilder` to facilitate ensuring nodes with fewer LOC
> Add more functions for ensuring nodes via MastForestBuilder

- assembly/src/assembler/mast_forest_builder.rs
- assembly/src/assembler/mod.rs
- assembly/src/assembler/procedure.rs
- core/src/mast/mod.rs
- core/src/mast/node/basic_block_node/mod.rs
- core/src/mast/node/basic_block_node/op_batch.rs
- core/src/mast/node/call_node.rs
- core/src/mast/node/dyn_node.rs
- core/src/mast/node/external.rs
- core/src/mast/node/join_node.rs
- core/src/mast/node/loop_node.rs
- core/src/mast/node/mod.rs
- core/src/mast/node/split_node.rs
- core/src/mast/serialization/info.rs
- core/src/mast/serialization/mod.rs
- core/src/mast/tests.rs
- core/src/program.rs
- miden/tests/integration/operations/io_ops/env_ops.rs
- processor/src/chiplets/hasher/tests.rs
- processor/src/decoder/mod.rs
- processor/src/decoder/tests.rs
- processor/src/lib.rs
- processor/src/trace/tests/decoder.rs
This PR contains some minor cleanup of MAST-related modules in the `core` create. The main changes are:
1. Removed `MerkleTreeNode` trait as it doesn't seem like we use this abstraction anywhere.
2. Added comments to all MAST nodes and also added section separators in various modules.
3. Split out `OpBatch`-related code into a separate file.
4. Removed `Serializable` and `Deserializable` implementations from `MastNodeId` and fixed a potential panic during deserialization of `MastForest`.
> Minor MAST module cleanup

- CHANGELOG.md
- Makefile
- air/Cargo.toml
- air/src/trace/main_trace.rs
- processor/Cargo.toml
- processor/src/host/advice/inputs.rs
- processor/src/host/advice/providers.rs
- processor/src/host/mod.rs
- processor/src/lib.rs
- processor/src/stack/mod.rs
- processor/src/stack/trace.rs
- stdlib/Cargo.toml
- test-utils/Cargo.toml
This small PR renames the `internals` feature to `testing`. 
Related issue: #1396
> Rename `internals` feature to `testing`

- CHANGELOG.md
- assembly/src/assembler/mast_forest_builder.rs
- assembly/src/assembler/tests.rs
- core/src/mast/mod.rs
- core/src/mast/node/call_node.rs
- core/src/mast/node/join_node.rs
- core/src/mast/node/loop_node.rs
- core/src/mast/node/mod.rs
- core/src/mast/node/split_node.rs
- core/src/mast/serialization/info.rs
- core/src/mast/serialization/tests.rs
- miden/tests/integration/operations/io_ops/env_ops.rs
- processor/src/chiplets/hasher/tests.rs
- processor/src/chiplets/tests.rs
- processor/src/decoder/tests.rs
- processor/src/trace/tests/chiplets/hasher.rs
- processor/src/trace/tests/decoder.rs
- processor/src/trace/tests/mod.rs
Add methods to `MastForest` to allow adding nodes with fewer LOC.
Follow on from #1404 which added similar methods to `MastForestBuilder`.
As per [comment](https://github.com/0xPolygonMiden/miden-vm/pull/1404#pullrequestreview-2190041018).
> Add more functions for adding nodes to MastForest

- .github/workflows/changelog.yml
- air/Cargo.toml
- assembly/Cargo.toml
- core/Cargo.toml
- miden/Cargo.toml
- processor/Cargo.toml
- prover/Cargo.toml
- stdlib/Cargo.toml
- test-utils/Cargo.toml
- verifier/Cargo.toml
This PR increments all crates versions to v0.10.0 so that compiler crates be able to reference next published VM crates to test the compiler crates publishing.
> chore: increment all crates version to v0.10.0

- assembly/src/assembler/mod.rs
- assembly/src/assembler/module_graph/debug.rs
- assembly/src/assembler/module_graph/mod.rs
- assembly/src/assembler/tests.rs
- assembly/src/library/error.rs
- assembly/src/library/masl.rs
- assembly/src/library/mod.rs
- assembly/src/library/module.rs
- assembly/src/library/namespace.rs
- assembly/src/library/tests.rs
- assembly/src/testing.rs
- assembly/src/tests.rs
- miden/benches/program_compilation.rs
- miden/benches/program_execution.rs
- miden/src/cli/bundle.rs
- miden/src/cli/data.rs
- miden/src/examples/blake3.rs
- miden/src/repl/mod.rs
- miden/src/tools/mod.rs
- miden/tests/integration/flow_control/mod.rs
- stdlib/build.rs
- stdlib/src/lib.rs
- stdlib/tests/crypto/falcon.rs
- stdlib/tests/mem/mod.rs
- test-utils/src/lib.rs
This PR performs minor cleanup of the `Assembler` API (though, I think we can clean things up a bit more). It consist of mostly renaming things and moving code around - but there should be no changes which affect the overall functionality or semantics.
The main changes are:
- Renamed `Assembler::add_compiled_library()` into `Assembler::add_library()`.
- Renamed `Assembler::with_compiled_library()` into `Assembler::with_library()`.
- Moved `ModuleInfo` and `ProcedureInfo` structs into a separate file and renamed some methods of `ModuleInfo`.
- Renamed `CompiledLibrary` into `Library`.
- Merged `LibraryError` with `CompiledLibraryError` and eliminated unused error variants.
> Minor refactoring of assembler API

- assembly/src/tests.rs
> test: verify fix for #1377

- CHANGELOG.md
- assembly/src/library/mod.rs
- core/src/mast/node/mod.rs
This PR exposes `MastNode::to_pretty_print`, which is too useful to keep internal to the crate, and without it, there is effectively no way to emit the textual MAST for specific nodes, such as in debug output. Strangely, `Program` itself implements `PrettyPrint`, but `Library` does not (and we would want to take advantage of the additional metadata in `Library` to `PrettyPrint` it differently anyway). The compiler use cases I have could probably be solved for by implementing pretty printers for `Library` and `ProcedureInfo` as MAST, with accompanying path/digest information, but I think there is value in exposing the pretty printer for `MastNode` directly anyway, since there may still be use cases where that is handy.
We should probably aim to make things like this public unless we have a …
> feat: expose pretty printing helper for mast nodes

- CHANGELOG.md
- air/src/trace/main_trace.rs
- processor/src/decoder/aux_trace/block_hash_table.rs
- processor/src/trace/mod.rs
Closes #1344.
Small optimisation - instead of looping over the trace rows, go backwards based on known / expected row contents.
> Get program hash without iterating over entire trace

- CHANGELOG.md
- Cargo.lock
- processor/Cargo.toml
- processor/src/lib.rs
This PR enables support for executing `Dyn` nodes from external MAST forests (i.e., MAST forests loaded into the host).
This is needed for `miden-base` and once merged, I intended to release this as v0.10.4 (will probably release just the `miden-processor` crate).
> Enable executing external `Dyn` nodes

- CHANGELOG.md
- core/src/mast/mod.rs
- core/src/mast/node/mod.rs
- processor/src/host/mast_forest_store.rs
This PR fixes an issue when having a procedure in the `MastForest` which is defined by a single `Export` node can lead to an infinite recursion in the `MemMastForestStore`. 
The fix is that instead of registering all procedures from a `MastForest` with `MastForestStore`, we register only the procedures local to that `MastForest` (i.e., excluding procedures which consist of a single `Export` or `Dyn` node).
> Only register local procedures in the MAST forest store

- CHANGELOG.md
- processor/src/errors.rs
- processor/src/lib.rs
This PR adds a small check to make sure looking up external nodes during execution does not result in a infinite loop.
> fix: detect circular external nodes

- README.md
- miden/README.md
- processor/README.md
- prover/README.md
- verifier/README.md
Adds a warning in the main README that the only officially supported `no_std` environment is WASM
> chore: Add warning about `no_std` environment

- CHANGELOG.md
- assembly/src/assembler/instruction/procedures.rs
- assembly/src/assembler/mast_forest_builder.rs
- assembly/src/assembler/mod.rs
- assembly/src/assembler/procedure.rs
- assembly/src/assembler/tests.rs
- assembly/src/library/error.rs
- assembly/src/library/mod.rs
- assembly/src/library/module.rs
- assembly/src/library/tests.rs
- core/src/mast/mod.rs
- core/src/program.rs
- miden/src/examples/blake3.rs
- miden/src/tools/mod.rs
- processor/src/chiplets/tests.rs
- processor/src/decoder/tests.rs
- processor/src/host/mast_forest_store.rs
- processor/src/host/mod.rs
- processor/src/lib.rs
- processor/src/trace/tests/chiplets/hasher.rs
- processor/src/trace/tests/decoder.rs
- processor/src/trace/tests/mod.rs
- stdlib/src/lib.rs
- stdlib/tests/mem/mod.rs
- test-utils/src/lib.rs
This PR wraps `MastForest` fields in `Program` and `Library` structs in `Arc`. This way, cloning these objects becomes a relatively cheap operation.
Additionally, this PR contains the following changes/refactorings:
1. A check was added to make sure that an entrypoint of a `Program` is registered as a root in the `MastForest`. This was already happening - but now we have an explicit check for this.
2. For every re-exported procedure, we now add an `External` node to the `MastForest`. This makes `Library` and `Program` structs a bit more consistent and also removes a somewhat un-intuitive situations where if a library had only re-exported procedures, its `MastForest` would be completely empty. Since now there is an easy way to track re-exported procedures in the `MastForest` itself, the …
> Wrap MastForest in Program and Library in Arc

- CHANGELOG.md
- assembly/src/ast/block.rs
This is just a small patch that fixes an issue in the formatting of Miden Assembly syntax - namely, blocks nested in operations, such as `if.true`, were being formatted with the first instruction in the block improperly indented. This PR ensures they are indented to the same level as the rest of the block.
@bobbinth Feel free to ignore this one and leave it to @plafer / @Fumuran - accidentally added you as a reviewer, and it's not possible to remove reviewers, so you're in for the long haul now 😆
> fix(assembly): properly indent first op in nested blocks

- CHANGELOG.md
- assembly/src/assembler/instruction/u32_ops.rs
- docs/src/user_docs/assembly/u32_operations.md
- miden/tests/integration/operations/u32_ops/arithmetic_ops.rs
- miden/tests/integration/operations/u32_ops/bitwise_ops.rs
- miden/tests/integration/operations/u32_ops/comparison_ops.rs
- miden/tests/integration/operations/u32_ops/mod.rs
- processor/src/operations/u32_ops.rs
- stdlib/asm/math/u64.masm
- stdlib/tests/math/u64_mod.rs
This PR solves two problems:
1. It ensures that we raise an `ExecutionError` when inputs to a `u32` operation are invalid, rather than attempting the operation with those inputs and potentially panicking, crashing the VM in the process. This has the effect of making the `u32` operations stricter in practice, but this has two primary benefits:
* These errors are handled gracefully, which means you get a useful error (and source locations in the debugger), rather than a crash with no useful information at all.
* It makes relying on undefined behavior impractical, forcing you to instead ensure that your program is semantically correct. It is one thing to avoid checked operations because you know that your program will never produce invalid values, and quite another to rely on the fact that …
> feat: improve handling of u32 operations

- core/src/mast/node/basic_block_node/mod.rs
Small PR that simplifies `batch_ops()` by not returning redundant information (i.e. batch groups).
I also used `Iterator::flat_map` instead of `winter_utils::flatten_slice_elements` since it's more canonical, and doesn't affect performance (blake3 benchmark). I also wouldn't be surprised if it compiled down to the same code after compiler optimizations.
> Simplify `batch_ops()`

- CHANGELOG.md
- processor/Cargo.toml
- processor/src/host/advice/inputs.rs
- processor/src/host/advice/map.rs
closes #1448 
As @bobbinth said at https://github.com/0xPolygonMiden/miden-base/issues/860#issuecomment-2344897083 , the PR is opened against `main` since it is not a breaking change.
> feat: add `PartialEq`,`Eq` and `De/Serialize` for `AdviceInputs` and `AdviceMap`

- docs/src/design/decoder/constraints.md
- docs/src/design/decoder/main.md
Fixes the operation batch flag constraints, as well as a minor fix in the op group table auxiliary constraints.
> Fix operation batch flags constraints

- CHANGELOG.md
- air/src/constraints/stack/op_flags/mod.rs
- air/src/constraints/stack/op_flags/tests.rs
- air/src/trace/main_trace.rs
- assembly/src/assembler/instruction/mod.rs
- assembly/src/assembler/tests.rs
- assembly/src/tests.rs
- core/src/mast/node/basic_block_node/tests.rs
- core/src/mast/serialization/decorator.rs
- core/src/mast/serialization/tests.rs
- core/src/operations/decorators/mod.rs
- core/src/operations/mod.rs
- docs/src/design/decoder/constraints.md
- docs/src/design/stack/io_ops.md
- docs/src/design/stack/op_constraints.md
- docs/src/design/stack/system_ops.md
- miden/tests/integration/flow_control/mod.rs
- miden/tests/integration/operations/sys_ops.rs
- processor/src/decoder/aux_trace/op_group_table.rs
- processor/src/decoder/tests.rs
- processor/src/decoder/trace.rs
- processor/src/lib.rs
- processor/src/operations/mod.rs
- processor/src/operations/sys_ops.rs
> Introduce `Emit` instruction

- CHANGELOG.md
- docs/src/design/decoder/constraints.md
- processor/src/decoder/aux_trace/block_hash_table.rs
- processor/src/decoder/aux_trace/mod.rs
Fixes the block hash table.
Note that the block stack table also seems broken (which is why I didn't add a `debug_assert_eq!` statement for `p1`). I will fix it in a subsequent PR.
> Fix block hash table

- CHANGELOG.md
- processor/src/decoder/aux_trace/block_stack_table.rs
- processor/src/decoder/aux_trace/mod.rs
Fixes the block stack table with the following logic:
- on `CALL`: `fn_hash` contains the parent function hash; it is only set to `callee_hash` in the next row
- on `SYSCALL`: `fn_hash` also contains the parent function hash; it remains unchanged by a syscall
- on `END` for call/syscall: block stack logic resets the `fn_hash` columns to the parent fn hash [only in the next row](https://github.com/0xPolygonMiden/miden-vm/blob/c6e2bc88923780aa15e0680482ac27886cb8351b/processor/src/decoder/mod.rs#L277-L281)
> Fix block stack table

- CHANGELOG.md
- assembly/src/ast/attribute/meta.rs
- assembly/src/ast/attribute/meta/expr.rs
- assembly/src/ast/attribute/meta/kv.rs
- assembly/src/ast/attribute/meta/list.rs
- assembly/src/ast/attribute/mod.rs
- assembly/src/ast/attribute/set.rs
- assembly/src/ast/mod.rs
- assembly/src/ast/procedure/mod.rs
- assembly/src/ast/procedure/procedure.rs
- assembly/src/ast/tests.rs
- assembly/src/parser/error.rs
- assembly/src/parser/grammar.lalrpop
- assembly/src/parser/lexer.rs
- assembly/src/parser/token.rs
- assembly/src/tests.rs
This commit introduces the concept of attributes/annotations to Miden Assembly procedures. These can be used to represent interesting/useful bits of metadata associated with specific procedures in three different forms:
* Marker attributes, e.g. `#[inline]`, a name with no associated data
* List attributes, e.g. `#[inline(always)]`, i.e. a parameterized marker; multiple values can be provided as comma-delimited values.
* Key-value attributes, e.g. `#[key = <value>]`, where `<value>` can be a "meta expression" of three possible types: identifier, string, or integer (in either decimal or hexadecimal format).
Attributes will provide the foundation for upcoming changes that will rely on being able to attach metadata to procedures. For now, attributes may _only_ be attached to procedure …
> feat: implement procedure annotation syntax

- CHANGELOG.md
- miden/tests/integration/main.rs
- processor/src/decoder/aux_trace/block_stack_table.rs
- processor/src/decoder/aux_trace/mod.rs
There was still a bug after #1511 with how the a `RESPAN` operation fetches the `is_loop` virtual column of the block stack table.
The fix is to set `is_loop` to `ZERO` when removing a row from a `RESPAN`, since the `is_loop` flag (read in `hasher_state[5]`) only applies to the `END` operation. For requests, it will only be set for the `LOOP` opcode.
> Fix block stack table respan

- processor/src/chiplets/aux_trace/mod.rs
@Fumuran 's work of integrating the latest miden-vm into miden-base showed us that the chiplets virtual table *and* bus are still broken. #1545 identifies the problem with the virtual table; I haven't diagnosed the issue with the bus yet.
This PR disables the checks for now to unblock @Fumuran.
> Disable chiplets aux columns check

- CHANGELOG.md
- assembly/src/assembler/mast_forest_builder.rs
- core/src/mast/merger/mod.rs
- core/src/mast/merger/tests.rs
- core/src/mast/mod.rs
- core/src/mast/node_fingerprint.rs
- core/src/operations/decorators/mod.rs
Renames `EqHash` to `MastNodeFingerprint` as a follow-up to #1534 and moves the fingerprint to its own module.
> Rename `EqHash` to `MastNodeFingerprint`

- CHANGELOG.md
- core/src/mast/mod.rs
- core/src/mast/serialization/info.rs
- core/src/mast/serialization/mod.rs
- core/src/mast/serialization/tests.rs
Permit child `MastNodeId`s to exceed the `MastNodeId`s of their parents during deserialization. This came up in the context of #1534 (see [this comment chain](https://github.com/0xPolygonMiden/miden-vm/pull/1534#discussion_r1807487205) for details).
Deserialization seems to be the only place where we had a requirement on the mentioned property, judging by the uses of `MastNodeId::from_u32_safe`.
A new constructor for `MastNodeId` was introduced that is similar to the existing one, except that it checks against a total expected node count of the forest instead of the _current_ node count of the forest. This allows child IDs to exceed their parent's IDs, such as in a forest like
```text
[Join(1, 2), Block(foo), Block(bar)]
```
However, we still want forests like this to fail during …
> Permit child `MastNodeId`s to exceed the `MastNodeId`s of their parents

- CHANGELOG.md
- Cargo.lock
- Makefile
- processor/Cargo.toml
- prover/Cargo.toml
- prover/src/lib.rs
This PR makes `miden-prover::prove()` method conditionally asynchronous and adds `async` feature to the `miden-prover` crate. These changes are needed to make `miden-base` work with the latest `miden-vm` and also will be needed for #1459.
I also had to modify the Makefile to run all tests/lints etc. without `async` feature enabled as this feature interferes with others. We should find a better way to handle this in the future.
> Make prover conditionally asynchronous

- CHANGELOG.md
- assembly/src/library/mod.rs
Following the conversation with @bitwalker the checked constructor fits only when parsing MASM code. The Miden package contains the export names crafted according to the Wasm CM naming scheme, i.e. `namespace:package/interface@version#function`. 
Discovered in https://github.com/0xPolygonMiden/compiler/issues/347 when parsing the Miden package file of the basic wallet account code.
The test for the failing case added in #1544 in the `Package` deserialization test suite at https://github.com/0xPolygonMiden/miden-vm/blob/9ff342eacb24315c784e95cea3eeb1f87058fc06/package/src/tests.rs#L136-L147. …
> fix: use unchecked constructor for `ProcedureName` on `Library` deserialization

- assembly/src/library/namespace.rs
- assembly/src/library/path.rs
- assembly/src/parser/scanner.rs
- assembly/src/parser/token.rs
The lint was introduced lately and is failing on `next`
> refactor: fix clippy warnings (`String::as_bytes`)

- CHANGELOG.md
- miden/tests/integration/operations/io_ops/mem_ops.rs
- processor/src/chiplets/memory/mod.rs
- processor/src/chiplets/memory/segment.rs
- processor/src/chiplets/memory/tests.rs
- processor/src/chiplets/mod.rs
- processor/src/errors.rs
- processor/src/operations/comb_ops.rs
- processor/src/operations/io_ops.rs
> Memory handling of 2 reads at the same address in the same clock cycle

- CHANGELOG.md
- core/src/advice/map.rs
- core/src/advice/mod.rs
- core/src/lib.rs
- core/src/mast/merger/mod.rs
- core/src/mast/merger/tests.rs
- core/src/mast/mod.rs
- core/src/mast/serialization/mod.rs
- core/src/mast/serialization/tests.rs
- miden/benches/program_execution.rs
- miden/src/examples/blake3.rs
- miden/src/repl/mod.rs
- miden/src/tools/mod.rs
- miden/tests/integration/exec.rs
- miden/tests/integration/main.rs
- miden/tests/integration/operations/decorators/mod.rs
- processor/src/errors.rs
- processor/src/host/advice/injectors/adv_map_injectors.rs
- processor/src/host/advice/inputs.rs
- processor/src/host/advice/mod.rs
- processor/src/host/advice/providers.rs
- processor/src/host/mod.rs
- processor/src/lib.rs
- stdlib/tests/mem/mod.rs
- test-utils/src/lib.rs
This PR implements VM-facing part of #1547 and adds advice map to the `MastForest` that is loaded in the advice provider when the `MastForest` executed.
This PR contains changes exposing `AdviceProvider` in `Host` (see [commit](https://github.com/0xPolygonMiden/miden-vm/pull/1574/commits/65a306021b00ec13957a795457577ac16191e8ff)) introduced in #1572 (see [comment](https://github.com/0xPolygonMiden/miden-vm/pull/1572#discussion_r1843676098))
> Add `MastForest::advice_map` for the data required in the advice provider before execution

- CHANGELOG.md
- core/src/mast/mod.rs
- core/src/mast/node/basic_block_node/mod.rs
- core/src/mast/node/mod.rs
- core/src/mast/serialization/basic_blocks.rs
- core/src/mast/serialization/decorator.rs
- core/src/mast/serialization/info.rs
- core/src/mast/serialization/mod.rs
Moving all decorator data to the end in order to enable truncating it later. See issue #1489 
Contains a minor refactor to make writing decorator info more direct by reducing interconnected layers of indirection.
Also extracted some functions from the Serializer code to make it easer follow.
> Serialize decorator data at the end

- CHANGELOG.md
- processor/src/operations/comb_ops.rs
- stdlib/asm/crypto/stark/constants.masm
- stdlib/asm/crypto/stark/deep_queries.masm
- stdlib/asm/crypto/stark/ood_frames.masm
- stdlib/asm/crypto/stark/public_inputs.masm
- stdlib/asm/crypto/stark/random_coin.masm
- stdlib/asm/crypto/stark/verifier.masm
- stdlib/tests/crypto/stark/mod.rs
- stdlib/tests/crypto/stark/verifier_recursive/channel.rs
- stdlib/tests/crypto/stark/verifier_recursive/mod.rs
As the title says.
We now use the `rcomb_base` and this leads to faster testing times. Also updated is how the `rcomb_base` is defined so that the accumulator for the `(x - z)` quotient is deeper in the stack than the accumulator for the `(x - gz)` quotient.
Other than that, there are some minor cleanups and re-organization for the testing code.
> Update and sync-up the recursive verifier

- assembly/src/assembler/mod.rs
- assembly/src/assembler/module_graph/mod.rs
- assembly/src/testing.rs
This PR:
- removes some duplication in assemble_library and assemble_kernel
- adds funtions to add multiple modules at once so that recomputation of the graph can be done only once. In this way `recompute` can be made private.
> Assembly: remove duplicate code and make recompute private

- CHANGELOG.md
- air/src/constraints/chiplets/memory/mod.rs
- air/src/constraints/chiplets/memory/tests.rs
- docs/src/design/chiplets/memory.md
- miden/tests/integration/operations/io_ops/mem_ops.rs
- processor/src/chiplets/memory/mod.rs
- processor/src/chiplets/memory/segment.rs
- processor/src/chiplets/memory/tests.rs
- processor/src/errors.rs
- processor/src/operations/io_ops.rs
- processor/src/trace/tests/range.rs
> feat(memory): allow more than 1 memory reads in the same clock cycle (same context & word address)

- core/src/operations/mod.rs
Description:
Add comprehensive documentation for the FriE2F4 operation in the core operations module.  The documentation includes:
- Description of FRI layer folding operation
- List of operations performed
- Detailed stack transition diagram with input and output states
- Explanation of stack overflow table interaction
This documentation helps developers better understand the FRI protocol implementation  in the Miden VM and improves code maintainability.
> docs: add documentation for FriE2F4 operation

- CHANGELOG.md
- assembly/src/assembler/mast_forest_builder.rs
- assembly/src/assembler/mod.rs
- assembly/src/assembler/module_graph/mod.rs
- assembly/src/tests.rs
- core/src/mast/mod.rs
- core/src/mast/node/call_node.rs
- core/src/mast/node/join_node.rs
- core/src/mast/node/loop_node.rs
- core/src/mast/node/mod.rs
- core/src/mast/node/split_node.rs
- miden/src/cli/run.rs
- miden/tests/integration/cli/cli_test.rs
- miden/tests/integration/cli/data/main.masm
Before this MR, the only ways to link a library during assembly are:
- Add the module sources. The library is effectively recompiled as part of the new library/program
- Add a compiled library. In this case all references to this library are compiled as external nodes
This MR adds the possibility to link a compiled library during assembly but have its MAST forest be merged in the resulting library/program. Two desirable properties:
- No external nodes are added for procedures that are present in vendored libraries, which improves performance.
- No unused procedures are present in the resulting program/library. If the vendored library contains extra unused procedures they are removed during assembly.
> Assembler: enable vendoring of compiled libraries (fixes #1435)

- CHANGELOG.md
- processor/src/host/dsa.rs
- stdlib/asm/crypto/dsa/rpo_falcon512.masm
- stdlib/tests/crypto/falcon.rs
As the title says. The current cycle count is around `57500` cycles.
> Update Falcon verification to use `horner_eval_base`

- CHANGELOG.md
- processor/src/decoder/tests.rs
- processor/src/errors.rs
- processor/src/lib.rs
- processor/src/system/mod.rs
In the previous implementation, the processor would allow call/dyncall/syscall while in a syscall in release mode (and crash in debug mode). I believe the assumption was that the assembler would not generate such a `MastForest` - but we also have to support/guard against `MastForest`s that weren't generated by the assembler.
> fix: syscall/dyncall/call in syscall now returns an error

- CHANGELOG.md
- miden/tests/integration/flow_control/mod.rs
- processor/src/lib.rs
Using a non-binary value as a condition from inside the loop wouldn't result in an error (and would crash in debug mode). It now properly returns an error.
> Fix processor `Loop` processing

- stdlib/README.md
Was reading through the Miden `std` docs and wanted to click on the link, when clicking on the link, it brought me to a non-existant page. Personally was expecting to be redirected to the implementation code of the `std` module.
Opening this PR so that when you click on the link for each module you are redirected to the module implementation.
> feat: fix broken links in README

- CHANGELOG.md
- processor/src/chiplets/aux_trace/bus/memory.rs
- processor/src/operations/horner_ops.rs
Fixes bus issue observed in https://github.com/0xPolygonMiden/miden-base/pull/1183.
We reproduced the same pattern that made `RCOMBBASE` break the bus previously - namely to assume that the memory is zeroed for the last 2 elements of the word where the evaluation point is stored. This PR then sends the entire word on the bus, instead of just the first 2 elements.
By the way, to debug this, all I did was to turn on the processor's `bus-debugger` feature in `miden-base`, and then saw a bunch of outstanding requests/responses. Zooming in on a request/response pair that happened on the same clock cycle:
```
The following requests are still outstanding:
- ...
- horner_eval_* req: { op_label: 27, ctx: 4006, addr: 1073744388, clk: 11338, word: [3848212099958106608, 12007821194187770238, 0, 0] } …
```
> fix: include entire memory word in horner bus requests

- Cargo.lock
- Makefile
- prover/Cargo.toml
- prover/src/gpu/metal/mod.rs
This PR updates `miden-gpu` dependency to v0.5 and fixes the current issues with `metal` builds.
> Update `miden-gpu` dependency to v0.5

- CHANGELOG.md
- processor/src/operations/sys_ops/sys_event_handlers.rs
- stdlib/tests/math/u64_mod.rs
The previous version would could crash the processor if `(divisor_hi << 32) + divisor_lo > u64::MAX` or `(dividend_hi << 32) + dividend_lo > u64::MAX` (by addition overflow).
> Prevent `U64Div` event from crashing

- CHANGELOG.md
- assembly/src/ast/attribute/meta.rs
- assembly/src/ast/attribute/meta/expr.rs
- assembly/src/ast/ident.rs
- assembly/src/ast/immediate.rs
- assembly/src/ast/procedure/name.rs
- assembly/src/ast/tests.rs
- assembly/src/library/namespace.rs
- assembly/src/library/path.rs
- assembly/src/parser/error.rs
- assembly/src/parser/grammar.lalrpop
- assembly/src/parser/lexer.rs
- miden/tests/integration/cli/cli_test.rs
This reworks the handling of identifiers in the assembly AST (i.e. `Ident`, `ProcedureName`, `LibraryNamespace`, and `LibraryPath`):
* Renames `new_unchecked` to avoid confusion about its intended use and safety profile
* Relaxes the validation rules for identifiers to allow most all printable, non-whitespace characters, with certain exceptions for the higher-level types that build on `Ident`
* Moves responsibility for stricter validation rules to the Miden Assembly parser where it belongs (and was largely already being handled by the lexer).
* Fixed a conflict in the CLI test suite that arises due when some of the tests are running multi-threaded concurrently
This situation occurred because these types were originally only consumed by the parser, but were repurposed so that downstream …
> fix: relax identifier rules

- CHANGELOG.md
- miden/src/cli/bundle.rs
- miden/src/cli/debug/mod.rs
- miden/src/cli/prove.rs
- miden/src/cli/run.rs
- miden/src/cli/utils.rs
- miden/src/tools/mod.rs
- miden/tests/integration/cli/cli_test.rs
Closes #1725:
- Changed debug mode to be enabled by default in CLI commands
- Added --release flag to disable debug mode (replaces --debug flag)
- Updated affected CLI commands (run.rs and prove.rs)
- Added entry to CHANGELOG.md
All tests and linting checks pass successfully.
> refactor: make debug mode the default in the CLI

- miden/src/repl/mod.rs
Hi! I fixed a broken GitHub link referencing the Scribe project's REPL implementation.
> Fixed dead link in `repl/mod.rs`

- .github/workflows/test.yml
- Cargo.toml
- Makefile
- miden/README.md
Closes: #1738 
Namely
- no longer run tests in nightly, as discussed in meetings offline
- remove test timeout
- add caching (which should bring the most significant performance boost)
Contrary to `miden-base`, we don't disable debug-assertions in `winter-prover`, because we want to get the errors if the trace is not properly built
> Optimize build times

- .config/nextest.toml
- .github/workflows/test.yml
- CHANGELOG.md
- Makefile
- air/src/options.rs
- miden/tests/integration/operations/decorators/events.rs
- processor/src/lib.rs
- stdlib/tests/main.rs
- test-utils/src/lib.rs
- test-utils/src/test_builders.rs
This PR provides 2 minor improvements to testing:
- Adds a `build_debug_test!` in the standard library such that simply changing from `build_test!()` to `build_debug_test!()` now properly makes all `debug.*` statements work.
- `test_utils::build_debug_test!()` doesn't add the standard library to `Test.libraries`, so any test that needs stdlib fails to compile
- Since it's a macro, adding the standard library to `build_test_by_mode!()` was messy (i.e. the stdlib needs to be a dependency everywhere it's used)
- I employed the same fix as `stdlib::build_test!()` and just added a new definition for `build_debug_test!()` in `stdlib`
- Instantiate `Process` in debug mode for debug tests so that `debug` statements are actually printed
So now, if you want to debug your test, all you need to do is …
> `ExecutionOptions::with_debugging()` now takes a boolean parameter

- CHANGELOG.md
- miden/src/cli/debug/command.rs
- miden/src/cli/debug/executor.rs
- miden/src/repl/mod.rs
- miden/src/utils.rs
- miden/tests/integration/exec_iters.rs
- processor/src/chiplets/memory/mod.rs
- processor/src/chiplets/memory/segment.rs
- processor/src/chiplets/memory/tests.rs
- processor/src/debug.rs
- processor/src/host/debug.rs
- processor/src/lib.rs
Changes the type used to store memory addresses from `u64` to `u32` as they are limited to `2**32`. Follows [this suggestion](https://github.com/0xPolygonMiden/miden-vm/pull/1627#issuecomment-2599646003) to wrap the address in a new type: `MemoryAddress(u32)`.
Closes #1612
> refactor: store memory addresses in `MemoryAddress(u32)`

- miden/src/cli/debug/executor.rs
Fixes: #1750 
To verify, run:
```
cargo run --bin miden --features="executable" -- debug --input "./miden/masm-examples/fib/fib.inputs" "./miden/masm-examples/fib/fib.masm"
```
and then `help`
Output:
```
The following mappings are also available:
n -> next
c -> continue
b -> back
r -> rewind
p -> print
l -> clock
q -> quit
h -> help
? -> help
```
> fix: incorrect debug help commands

- .github/workflows/book.yml
- .github/workflows/build.yml
- .github/workflows/changelog.yml
- .github/workflows/lint.yml
Replaced every `actions/checkout@main` reference with
`actions/checkout@v4`.
GitHub recommends pinning to a major version tag instead of the default
branch for better stability, security, and compatibility with future
updates.
[Reference](https://github.com/actions/checkout#usage)
> ci: switch checkout action to v4

- docs/src/SUMMARY.md
- docs/src/user_docs/assembly/instruction_reference.md
This PR introduces a new single-page reference for Miden Assembly instructions
to the VM documentation.
The new page, `docs/src/user_docs/assembly/instruction_reference.md`,
consolidates information from various existing documentation files and
formats it consistently as requested. It aims to provide a quick and
easy-to-use reference for developers working with Miden Assembly.
The reference includes the following categories of instructions:
- Field Operations (Comparison, Assertions/Tests, Arithmetic/Boolean, Extension Field)
- U32 Operations (Conversions/Tests, Arithmetic, Bitwise, Comparison)
- Stack Manipulation (including Conditional Manipulation)
- Input/Output Operations (Constant, Environment, Nondeterministic/Advice Provider, Memory - Absolute & Local)
- Cryptographic Operations …
> docs: Add comprehensive Miden Assembly instruction reference page

- CHANGELOG.md
- processor/src/debug.rs
Fix issue #1751 by modifying the back() method in VmStateIterator to handle the case when clock is at 0. Previously, the method would decrement the clock twice in certain situations, causing an underflow panic. This change ensures clock value is never decremented below 0 by using saturating subtraction.
> fix: prevent panic in VmStateIterator back() method when at clock 0

- CHANGELOG.md
- processor/src/errors.rs
- processor/src/operations/sys_ops/sys_event_handlers.rs
- stdlib/asm/crypto/dsa/rpo_falcon512.masm
Addresses #1819
Adds some range checks to make sure that the Falcon modular reduction advice injector receives inputs that are `u32`.
> Add range checks for Falcon mod reduction

- CHANGELOG.md
- core/src/program.rs
- stdlib/asm/crypto/fri/helper.masm
- stdlib/asm/crypto/stark/constants.masm
- stdlib/asm/crypto/stark/public_inputs.masm
- stdlib/asm/crypto/stark/random_coin.masm
- stdlib/asm/crypto/stark/verifier.masm
- stdlib/tests/crypto/stark/mod.rs
- stdlib/tests/crypto/stark/verifier_recursive/mod.rs
Adds the infrastructure to handle variable length public inputs in the recursive verifier.
The idea is to provide the randomness-reduced value of the variable length public inputs as an input to the ACE circuit.
Although the only variable-length public inputs in the case of the recursive verifier are the kernel procedures digests, the code in this PR tries to be a bit more general to accommodate more general settings.
- …
> Add kernel procedures digests reduction using auxiliary randomness

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- air/src/lib.rs
- core/src/program.rs
- stdlib/asm/crypto/fri/helper.masm
- stdlib/asm/crypto/stark/constants.masm
- stdlib/asm/crypto/stark/public_inputs.masm
- stdlib/asm/crypto/stark/random_coin.masm
- stdlib/asm/crypto/stark/utils.masm
- stdlib/asm/crypto/stark/verifier.masm
- stdlib/tests/crypto/stark/mod.rs
- stdlib/tests/crypto/stark/verifier_recursive/mod.rs
This has the advantage of reducing the number of squeezes needed of the random oracle to generate the aux randomness to just one. This means that the only place where there is a complex squeezing/Duplex logic is in the query generation procedure.
This PR also includes testing to make sure that the query sampling procedure is robust.
This closes #920.
> Simplify auxiliary randomness generation

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- air/src/lib.rs
- air/src/options.rs
- air/src/trace/mod.rs
- core/src/program.rs
- processor/src/trace/mod.rs
- stdlib/asm/crypto/fri/helper.masm
- stdlib/asm/crypto/stark/constants.masm
- stdlib/asm/crypto/stark/deep_queries.masm
- stdlib/asm/crypto/stark/ood_frames.masm
- stdlib/asm/crypto/stark/public_inputs.masm
- stdlib/asm/crypto/stark/random_coin.masm
- stdlib/asm/crypto/stark/utils.masm
- stdlib/asm/crypto/stark/verifier.masm
- stdlib/tests/crypto/stark/mod.rs
- stdlib/tests/crypto/stark/verifier_recursive/channel.rs
- stdlib/tests/crypto/stark/verifier_recursive/mod.rs
(Supersedes #1801)
Simplifies the implementation of the recursive verifier by:
Using Horner batching for the DEEP polynomial,
Evaluating quotient polynomials at gz in addition to z, and
Padding the (main) execution trace to the next multiple of 8 hence simplifying un-hashing.
This will significantly simplify the task of generalizing the ACE codegen in AirScript. As a by product, the recent changes shave off a 1000 cycles of the (stack) trace i.e., the recursive verifier uses ~31500 now instead of ~32500 previously.
- …
> feat: simplify and optimize the recursive verifier

- CHANGELOG.md
- assembly/src/parser/grammar.lalrpop
- assembly/src/parser/token.rs
This PR adds support for setting debugger breakpoints in MASM syntax via the `breakpoint` keyword. The instruction actually already existed, it just wasn't surfaced in the syntax for some reason. This makes it possible to explicitly set a breakpoint to be triggered when the debugger reaches that instruction.
NOTE: I'm not sure how the current debugger handles this, but I made use of it in `midenc-debug` recently, which is when I found out it wasn't supported in MASM syntax. I've been sitting on this PR for awhile, and just got around to submitting it.
> feat(syntax): add support for breakpoint instruction

- CHANGELOG.md
- Cargo.lock
- air/Cargo.toml
- assembly/src/assembler/module_graph/mod.rs
- assembly/src/library/path.rs
- core/src/mast/node/basic_block_node/mod.rs
- miden/Cargo.toml
- package/Cargo.toml
- processor/Cargo.toml
- scripts/publish-release.sh
- stdlib/Cargo.toml
This is the last PR that will make it into v0.15. It
- fixes clippy
- updates the changelog
- updates a bunch of dependencies to their latest version
- improve the release script
> Prepare release 0.15

- scripts/publish-release.sh
Fixes release script based on running it for the first time for v0.15.0.
@bobbinth the only thing outstanding is that `miden-test-utils` is still on the initial `v0.1.0` (and has been for 1-2 years). Is there a good reason for not incrementing that version like the others? Basically when we make changes to it, those changes are never released.
Currently the script still fails for that package since v0.1.0 is already on crates.io.
> Fix release script

- CHANGELOG.md
- assembly/src/assembler/instruction/mod.rs
- assembly/src/ast/instruction/debug.rs
- assembly/src/parser/grammar.lalrpop
- processor/src/host/debug.rs
The compilation of `ast::DebugOptions` was slightly refactored to accommodate these fixes, but bare `debug.local` no longer panics and instead prints all local values, and the other two variants now print from the correct part of memory.
I considered adding tests for this, but currently most of the heavy lifting is also done in the functions that do the actual printing.
Fixes #1853.
- Documentation/comments updated according to …
> fix `debug.local` panic and incorrect value printing

- CHANGELOG.md
- miden-vm/tests/integration/operations/decorators/mod.rs
- processor/src/fast/tests/advice_provider.rs
- processor/src/host/mod.rs
- test-utils/src/host.rs
Fixes #1902
Make Host::get_mast_forest take a mutable reference to `self`.
> Change signature of `Host::get_mast_forest` from `&self` to `&mut self`

- core/src/mast/mod.rs
- core/src/mast/serialization/basic_blocks.rs
- core/src/mast/serialization/decorator.rs
- core/src/mast/serialization/info.rs
- core/src/mast/serialization/mod.rs
- core/src/mast/serialization/string_table.rs
- core/src/mast/tests.rs
- core/src/operations/mod.rs
- core/src/program.rs
This small PR switches to using `crate::utils` as the source of serialization types in the `miden-core` create (instead of importing them from `winter-utils`).
> Use crate dependency in core for serialization types

- air/src/lib.rs
- core/src/lib.rs
- miden-vm/tests/integration/operations/ext2_ops.rs
- processor/src/chiplets/ace/mod.rs
- processor/src/chiplets/ace/tests/circuit.rs
- processor/src/chiplets/ace/tests/encoder.rs
- processor/src/chiplets/ace/tests/mod.rs
- processor/src/chiplets/ace/trace.rs
- processor/src/errors.rs
- processor/src/fast/circuit_eval.rs
- processor/src/fast/fri_ops.rs
- processor/src/fast/horner_ops.rs
- processor/src/lib.rs
- processor/src/operations/ext2_ops.rs
- processor/src/operations/fri_ops.rs
- processor/src/operations/horner_ops.rs
- processor/src/operations/sys_ops/sys_event_handlers.rs
- stdlib/tests/crypto/arithmetic_circuit_eval.rs
- stdlib/tests/crypto/fri/verifier_fri_e2f4.rs
- stdlib/tests/crypto/stark/mod.rs
- stdlib/tests/crypto/stark/verifier_recursive/channel.rs
- stdlib/tests/crypto/stark/verifier_recursive/mod.rs
- test-utils/src/lib.rs
Add `QuadFelt` definition to `core` and removes duplicate definitions. Unify name to `QuadFelt` rather than `QuadExt`.
> Unify `QuadFelt`

- CHANGELOG.md
- assembly-syntax/src/testing/context.rs
- assembly/src/assembler.rs
- assembly/src/testing.rs
- crates/debug/types/src/lib.rs
- crates/debug/types/src/source_manager.rs
- crates/utils/testing/src/lib.rs
- miden-vm/benches/program_execution.rs
- miden-vm/src/cli/data.rs
- miden-vm/src/repl/mod.rs
Closes #1966 
This is a stacked PR on top of #1945 to avoid breaking changes when we merge that one.
Note that contrary to what was discussed in https://github.com/0xMiden/miden-vm/pull/1884#discussion_r2188948366, `ErrorContextImpl` uses `Arc<dyn SourceManager>` (instead of `SourceManagerSync`), and hence is not `Send` or `Sync` (and hence cannot be sent across threads, or be included in the returned `Future` of our `AsyncHost` methods). This is because it is actually not *needed* at this moment, so I prefer to only include the bounds if we find that we do indeed need to send error contexts across threads (which we currently don't).
> Introduce `SourceManagerSync`

- CHANGELOG.md
- processor/src/lib.rs
Makes `Process::state()` public after removing `From<&Process> for ProcessState`
> hotfix: make `Process::state()` public

- CHANGELOG.md
- processor/src/trace/mod.rs
Return the final `AdviceProvider` state as part of the `ExecutionTrace`
> hotfix: Return `AdviceProvider` as part of the `ExecutionTrace`

- CHANGELOG.md
- core/src/mast/node/mod.rs
- processor/src/continuation_stack.rs
- processor/src/fast/mod.rs
- processor/src/lib.rs
Closes #1989
Note: `ContinuationStack` is meant to replace/be merged with the `ExecutionTraversal` in #1839.
Unfortunately, we get the same performance on the `blake3_1to1` benchmark with this change (where we were hoping for an improvement). I didn't try to optimize too much yet, as I'd focus on fully merging #1839 first.
> Convert `FastProcessor` to iterative execution

- CHANGELOG.md
- air/src/proof.rs
Adds a `new_dummy` method to `ExecutionProof`. The reason behind is to ease the testing of `ProvenTransaction`'s validations without needing to execute a transaction.
Related to: https://github.com/0xMiden/miden-node/pull/1093
> chore: add ExecutionProof::new_dummy

- CHANGELOG.md
- crates/utils/testing/src/lib.rs
- miden-vm/tests/integration/operations/decorators/mod.rs
- miden-vm/tests/integration/operations/sys_ops.rs
- processor/src/decoder/tests.rs
- processor/src/fast/sys_ops.rs
- processor/src/fast/tests/advice_provider.rs
- processor/src/host/advice/mod.rs
- processor/src/host/default.rs
- processor/src/host/handlers.rs
- processor/src/host/mod.rs
- processor/src/lib.rs
- processor/src/operations/horner_ops.rs
- processor/src/operations/sys_ops/mod.rs
- stdlib/tests/crypto/falcon.rs
Removes the dependency of a `&mut ProcessState` by a layer of indirection, being `AdviceMutation` The mutations are applied after the respective call to the `(Sync|Async)Host`-trait implementors. The `handler` has been changed in the same fashion, returning a set of `AdivceMutation`s.  
Also remove the `impl err_ctx` to avoid another data dependency.
> refactor: `on_event` should not require `&mut ProcessState` and error context

- CHANGELOG.md
- crates/debug/types/Cargo.toml
- crates/debug/types/src/lib.rs
- crates/debug/types/src/source_manager.rs
- miden-vm/tests/integration/operations/decorators/mod.rs
- processor/Cargo.toml
- processor/src/fast/mod.rs
- processor/src/fast/tests/advice_provider.rs
- processor/src/host/advice/mod.rs
- processor/src/host/default.rs
- processor/src/host/mod.rs
- processor/src/lib.rs
- stdlib/tests/crypto/falcon.rs
The current approach is making the `Sync` bound conditional on the `target_arch`, but it has implications in `miden-base`, i.e. `impl DataStore` is captured in closure scope and hence also needs to have `Sync`.
The next steps: Attempt to use a generic and see if this fares any better. 
Note: Previously https://github.com/0xMiden/miden-vm/pull/2027 which I can't seem to re-open.
Most relevant discussion items:
* https://github.com/0xMiden/miden-vm/pull/2027#discussion_r2228480630
* https://github.com/0xMiden/miden-vm/pull/2027#discussion_r2234137549
> draft: handle `Sync` requirements around `dyn SourceManager` for multithreaded executors

- docs/src/EXPORTED.md
This small PR updates the `EXPORTED.md` file which ensures that the documentation is visible in the miden-book.
The `EXPORTED.md` file represents which md files are displayed in the miden-book.
Fixes this: https://midengroup.slack.com/archives/C08UNH9UEM8/p1753859432326219
> chore: update EXPORTED.md

- CHANGELOG.md
- miden-vm/tests/integration/operations/decorators/mod.rs
- processor/src/fast/mod.rs
- processor/src/fast/tests/advice_provider.rs
- processor/src/host/default.rs
- processor/src/host/mod.rs
Closes #2060 
- This PR makes `get_mast_forest` back to an `async API` now that conditional async support is working.
> feat(host): make `get_mast_forest` async again

- crates/utils/testing/src/lib.rs
- miden-vm/tests/integration/operations/decorators/advice.rs
- stdlib/tests/crypto/falcon.rs
Partially reverts the change to testing framework in [9277ab](https://github.com/0xMiden/miden-vm/commit/9277abe4b7ddf66521666f481a6fb10985a5b032) which statically linked to the standard library. This caused a big increase in time.
Instead, we replace the call to `exec.sys::truncate_stack` in `advice_insert_hqword` by manually truncating the stack.
Interestingly, this changes the number of cylces of the falcon test. It's not clear if it was failing previously but not detected or whether these changes affect the cycle count.
- Commits are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) …
> fix(testing): avoid statically linking `stdlib` for testing

- crates/debug/types/src/source_file.rs
1. Clarify docs for SourceFile::source_slice and SourceContent::source_slice to state byte-index semantics and UTF-8 boundary requirements, aligning with actual str.get usage.
2. Fix SourceContent::update to report InvalidSelectionEnd with range.end instead of range.start.
> chore: clarify source_slice docs to byte indices; fix InvalidSelectionEnd param

- CHANGELOG.md
- processor/src/fast/circuit_eval.rs
- processor/src/fast/crypto_ops.rs
- processor/src/fast/field_ops.rs
- processor/src/fast/fri_ops.rs
- processor/src/fast/horner_ops.rs
- processor/src/fast/io_ops.rs
- processor/src/fast/memory.rs
- processor/src/fast/mod.rs
- processor/src/fast/stack_ops.rs
- processor/src/fast/sys_ops.rs
- processor/src/fast/tests/memory.rs
- processor/src/fast/trace_state.rs
- processor/src/fast/trace_state_builder.rs
- processor/src/fast/tracer.rs
- processor/src/fast/u32_ops.rs
Closes #2089
Stacked on #2023
Introduces the `Tracer` trait, as discussed in #2089. This also cleaned up the `CoreTraceBuilder`, which was left over from #2023.
This is a fairly mechanical change; the general idea is that in the fast processor, we swapped all "if we have a core trace builder, record X" calls to a `tracer.record_x()` call. We then pass in `NoopTracer` (with an empty body for every method) when executing from `execute()`, and pass in `CoreTraceStateBuilder` when executing from `execute_from_trace()`. 
Note that we added a new method `FastProcessor::execute_with_tracer()`, but leaves the discussed `FastProcessor::step_continuation()` (needed for the debugger) for a subsequent PR.
Performance-wise, we recovered the benchmark performance prior to #2023 (i.e. the hypothesis …
> Introduce `Tracer` trait

- Cargo.toml
- prover/src/gpu/metal/tests.rs
#2098 broke the build under the `metal` feature - not sure why `make clippy` in the CI didn't catch it?
Also fixes a typo from #2094.
> chore: fix build and lints

- CHANGELOG.md
- Cargo.lock
- air/Cargo.toml
- assembly-syntax/Cargo.toml
- assembly/Cargo.toml
- core/Cargo.toml
- core/src/mast/mod.rs
- core/src/mast/node/basic_block_node/mod.rs
- core/src/mast/node/call_node.rs
- core/src/mast/node/dyn_node.rs
- core/src/mast/node/external.rs
- core/src/mast/node/join_node.rs
- core/src/mast/node/loop_node.rs
- core/src/mast/node/mod.rs
- core/src/mast/node/split_node.rs
- crates/debug/types/Cargo.toml
- crates/utils/diagnostics/Cargo.toml
- crates/utils/sync/Cargo.toml
- miden-vm/Cargo.toml
- package/Cargo.toml
- processor/Cargo.toml
- prover/Cargo.toml
- stdlib/Cargo.toml
- verifier/Cargo.toml
This PR implements `MastForest::strip_decorators()` function which removes all decorators from the underlying MAST forest. This is needed to help address https://github.com/0xMiden/miden-base/issues/1812. For this reason, the PR is against `main` and I'll make a patch release once this is merged (the changes are non-breaking).
This is not meant as a long-term solution and may change as a result of https://github.com/0xMiden/miden-vm/issues/1580.
> Add ability to remove decorators from `MastForest`

- miden-vm/src/cli/run.rs
Replace unwrap() on DefaultHost::load_library with proper error propagation via into_diagnostic().wrap_err(...)?, aligning with error handling used in other CLI commands (prove/tools). Prevents panics when stdlib or dynamic libraries fail to load and surfaces informative diagnostics to users.
> cli(run): propagate load_library errors instead of panicking

- core/src/mast/merger/mod.rs
Correct the doc comment to describe returning Option<MastNodeId> for a given MastNodeFingerprint
The previous wording incorrectly mentioned returning a slice of nodes and referenced a non-existent mast_root parameter
> fix: incorrect doc for lookup_node_by_fingerprint

- core/src/stack/inputs.rs
- core/src/stack/outputs.rs
Improve error message specificity in StackInputs and StackOutputs deserialization.
Previously, the deserialization methods would always assume length exceeded errors when calling the new() constructor failed, ignoring other possible error types like DuplicateAdviceRoot or NotFieldElement for InputError, and InvalidStackElement or OutputSizeTooBig for OutputError.
This change preserves the original error information by forwarding the actual error message instead of creating a generic one, making debugging easier for users.
Changes:
- core/src/stack/inputs.rs: Use actual error in deserialization error message
- core/src/stack/outputs.rs: Use actual error in deserialization error message
> fix: improve error handling in stack serialization

- Cargo.lock
- Cargo.toml
- assembly-syntax/Cargo.toml
- assembly-syntax/src/ast/procedure/name.rs
- assembly-syntax/src/library/mod.rs
- assembly-syntax/src/library/namespace.rs
- core/Cargo.toml
- core/src/mast/mod.rs
- crates/utils/serde-test-macros/Cargo.toml
- crates/utils/serde-test-macros/src/lib.rs
This PR against #2071 implements a `serde_test` macro that can generate round-trip serialization tests pegged on an implementation of `proptest::prelude::Arbitrary`. This macro:
- supports generic arguments passed as attributes,
- uses ~~`bincode`~~ `serde_json` as the test serializer (I expect this will be replaced by #2130)
=> no more boilerplate tests! (and future tests are easier to define)
Tests failing here are signal for #2071 (unless I messed up something in my `Arbitrary` impls).
> feat: macro-generated serialization tests

- core/src/stack/outputs.rs
Replace hardcoded [Felt; 16] in impl Deref for StackOutputs with [Felt; MIN_STACK_DEPTH].
This removes a latent inconsistency: the struct stores [Felt; MIN_STACK_DEPTH], but Deref::Target was fixed to 16. If MIN_STACK_DEPTH changes, the previous code would break or diverge. Using the constant keeps the type aligned with the single source of truth and matches usage across the codebase.
> chore(core): use MIN_STACK_DEPTH for StackOutputs Deref target

- stdlib/asm/word.masm
While working on https://github.com/0xMiden/miden-vm/pull/2114 I noticed that cycle counts for `word::gt` and `word::lte` were off.
Also, not sure what causes this, but when I measure it like below (compare clk and subtract 2), sometimes I get 117, sometimes 118, depending on the call site.
```
export.gt
clk debug.stack.1 drop
...procedure implementation...
clk debug.stack.1 drop
end
```
- Commit messages and codestyle follow [conventions](../CONTRIBUTING.md).
- Documentation/comments updated according to …
> update cycle counts for word::gt and word::lte

- stdlib/tests/math/u64_mod.rs
The test seems to have been ignored during the development process of #1194, and its ignore missed in review.
> test: un-ignore math::u64_mod::unchecked_shl

- .github/workflows/bench.yml
- .github/workflows/build.yml
- .github/workflows/changelog.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
Makes workflows require just the permissions they need.
> ci: workflows follow least privilege

- crates/utils/testing/src/lib.rs
- processor/src/fast/mod.rs
- processor/src/tests.rs
The test framework was not properly loading advice maps from compiled programs' Mastforests into the execution context, causing "advice provider error" failures in tests that use advice maps defined in assembly source.
The slow processor was working correctly because it automatically calls `self.advice.extend_map(program.mast_forest().advice_map())` in `execute_mast_root()`. The fast processor was failing because `assert_result_with_fast_processor()` was creating the FastProcessor with only manually provided advice inputs, without merging the program's compiled advice map.
This merges that advice map. Closes #1886.
> fix: advice_map loading in test framework for the fast processor

- miden-vm/src/cli/data.rs
Replace unwraps that could crash the CLI on invalid user data or I/O errors.
OutputFile::stack_outputs: map parse::<u64> errors to Result for malformed .outputs.
ProofFile::write: return error on write_all failure instead of panicking.
Aligns with existing Result-based error handling
> fix: avoid panics by propagating errors in outputs parsing and proof writing

- processor/src/lib.rs
- processor/src/operations/sys_ops/sys_event_handlers.rs
- stdlib/src/handlers/sorted_array.rs
No changelog required. Addresses a few comments after #2114 was merged:
- https://github.com/0xMiden/miden-vm/pull/2114#discussion_r2365583544
- https://github.com/0xMiden/miden-vm/pull/2114#discussion_r2365584280
- https://github.com/0xMiden/miden-vm/pull/2114#discussion_r2365585634
> A potential small improvement: maybe this could be a method on the ProcessState? It could look something like:
> ```
> impl ProcessState {
>     pub fn get_mem_addr_range(
>         &self,
>         start_idx: usize,
>         end_idx: usize,
>     ) -> Result<Range<MemoryAddress>, MemoryError> {
>         ...
>     }
> }
> ```
> In the above, I've also used Range<MemoryAddress> instead of (u32, u32) for the return value as I think it is a bit more self-describing (and type-safe).
I used `Range<u32>` …
> sorted_array::push_lowerbound_result refactor

- .github/workflows/bench.yml
- .github/workflows/build.yml
- .github/workflows/lint.yml
This aims at making sure the target installed in e.g. the build workflow matches what's then used. 
Aims at addressing [build failures](https://github.com/0xMiden/miden-vm/actions/runs/17900500488/job/50892829648).
> ci: be specific about which toolchain to install & use

- processor/src/range/aux_trace.rs
- Replaces an invalid "{}" placeholder in an `expect` message with a clear, static string.
- Improves error diagnostics; `expect` does not perform formatting.
> Fix misleading expect message in range aux trace builder

- air/src/constraints/stack/field_ops/mod.rs
- core/src/operations/mod.rs
Fixes a rust doc typo from #2217.
> doc: escape brackets in rustdoc

- .github/workflows/link-checker.yml
- lychee.toml
- Add GNU make manual URL exclusion to lychee.toml to prevent 429 errors
- Set fail-fast=false in CI workflow to allow job to continue (and open an issue) after link failures
> chore: fix link checker job 

- CHANGELOG.md
- processor/src/fast/memory.rs
> chore: Memory::read_element takes &self instead of &mut self

- CHANGELOG.md
- Cargo.lock
- core/src/advice/map.rs
- core/src/kernel.rs
- core/src/mast/mod.rs
- core/src/mast/node/basic_block_node/arbitrary.rs
- core/src/mast/node/basic_block_node/mod.rs
- core/src/mast/serialization/decorator.rs
- core/src/mast/serialization/string_table.rs
- core/src/operations/decorators/assembly_op.rs
- core/src/operations/decorators/debug.rs
- core/src/operations/decorators/mod.rs
- core/src/program.rs
- crates/assembly-syntax/src/ast/attribute/meta/expr.rs
- crates/assembly-syntax/src/ast/attribute/meta/kv.rs
- crates/assembly-syntax/src/ast/attribute/meta/list.rs
- crates/assembly-syntax/src/ast/attribute/mod.rs
- crates/assembly-syntax/src/ast/attribute/set.rs
- crates/assembly-syntax/src/ast/ident.rs
- crates/assembly-syntax/src/ast/procedure/name.rs
- crates/assembly-syntax/src/library/mod.rs
- crates/assembly-syntax/src/library/namespace.rs
- crates/assembly-syntax/src/library/path.rs
- crates/assembly-syntax/src/parser/token.rs
- crates/utils/serde-test-macros/src/lib.rs
- package/Cargo.toml
- package/src/dependency/mod.rs
- package/src/package/manifest.rs
**This PR:**
- is stacked on #2200,
- extends the round-trip macros started in #2132 to also generate winterfell round-trip tests,
- adds a few instances of Arbitrary for types that were missing one (up to and including `Program`), fixing an issue in the instance for `WordValue` 
- adds ~35 roundtrip serialization tests,
- fixes an enum-tagging bug in the serialization of `Attribute`
**Also (unrelated)**:
- adds a rust-toolchain because CI (based on rustup atm) isn't picking up the latest stable.
**Why?** I am working on a feature which is blocked by a (winter) serialization issue in the space *between* `MastForest` (ok) and `Program` (not so). This lets me rule out a range of issues.
> test: Arbitrary + {winter,serde} serialization, up to Program (+ small bugfix)

- CHANGELOG.md
- processor/src/fast/mod.rs
Places the `FastProcessor` stack on the heap to reduce the risk of (OS thread) stack overflow, as observed in e.g. https://github.com/0xMiden/miden-base/issues/1927.
Benchmarks are unaffected by this change.
Also related: https://github.com/0xMiden/miden-base/issues/1936#issuecomment-3380244534
@bobbinth I could rebase this against `main` as well if we want to release a patch version
> chore: place the fast processor stack on the heap instead of the stack
