assembly/src/v1/parsers/crypto_ops.rs, assembly/src/v1/parsers/io_ops.rs, assembly/src/v1/parsers/mod.rs, assembly/src/v1/parsers/stack_ops.rs, assembly/src/v1/parsers/u32_ops.rs
This PR adds stubs for all parser methods needed for v0.2 assembly.
=> Parser method stubs

core/src/v1/program/blocks/join_block.rs, core/src/v1/program/blocks/loop_block.rs, core/src/v1/program/blocks/mod.rs, core/src/v1/program/blocks/span_block.rs, core/src/v1/program/blocks/split_block.rs
This PR contains minor code block updates needed for new processor implementation. These updates include:
- Adding public accessors to a code block's children.
- Refactoring of a span block to contain explicit operation batches.
=> Code block updates

assembly/src/v1/parsers/stack_ops.rs
=> Implement movupw parsing

air/Cargo.toml, air/src/lib.rs, air/src/options.rs, assembly/Cargo.toml, core/Cargo.toml, core/src/utils/mod.rs, core/src/v1/mod.rs, core/src/v1/program/blocks/call_block.rs, core/src/v1/program/blocks/join_block.rs, core/src/v1/program/blocks/loop_block.rs, core/src/v1/program/blocks/mod.rs, core/src/v1/program/blocks/span_block.rs, core/src/v1/program/blocks/split_block.rs, core/src/v1/program/mod.rs, core/src/v1/program/operations.rs, examples/Cargo.toml, examples/src/merkle.rs, miden/Cargo.toml, miden/src/lib.rs, miden/src/tests.rs, processor/Cargo.toml, processor/src/lib.rs, verifier/Cargo.toml
This PR updates Winterfell dependency to v0.3.
=> Winterfell update

processor/Cargo.toml, processor/src/v1/mod.rs, processor/src/v1/operations/field_ops.rs, processor/src/v1/stack/mod.rs, processor/src/v1/tests/mod.rs, processor/src/v1/trace.rs
This PR implements `ExecutionTrace` struct for the new processor. For now, the implementation is very basic and much of the functionality will need to be added later.
=> Execution trace

core/src/v1/program/operations.rs, processor/src/v1/errors.rs, processor/src/v1/operations/field_ops.rs, processor/src/v1/operations/mod.rs, processor/src/v1/operations/utils.rs
This PR implements handling of field operations (arithmetic, boolean, equality comparisons) in the processor crate.
=> Processor field operations

core/src/v1/program/operations.rs, processor/src/v1/operations/mod.rs
This PR adds `SDepth` variant to operations enum.
=> Stack depth op

assembly/src/v1/parsers/stack_ops.rs
=> Implement swap

processor/src/v1/operations/field_ops.rs, processor/src/v1/operations/mod.rs, processor/src/v1/operations/u32_ops.rs
This PR implements handling of u32 operations in the processor.
=> Implement processing of u32 operations

processor/src/v1/operations/io_ops.rs, processor/src/v1/operations/mod.rs, processor/src/v1/stack/mod.rs
This PR implements handling of `sdepth` operation in the processor.
=> Implement processing of sdepth op

core/src/v1/hasher/mod.rs, core/src/v1/mod.rs, core/src/v1/program/operations.rs, processor/src/v1/hasher/mod.rs, processor/src/v1/mod.rs, processor/src/v1/operations/crypto_ops.rs, processor/src/v1/operations/io_ops.rs, processor/src/v1/operations/mod.rs, processor/src/v1/trace.rs
This PR will implement handling of cryptographic operations in the processor. This includes:
This PR will also implement basic structure for the `Hasher` module in the processor.
=> Crypto op processing

assembly/src/parsers/crypto_ops.rs
This PR adds tests to the assembly crypto ops and implements parse_rphash and parse_rpperm
=> Implement crypto ops rphash and rpperm

processor/src/tests/flow_control.rs, processor/src/tests/mod.rs
This PR adds tests to the processor for testing operation of flow control instructions.
=> Implement basic flow control tests

assembly/src/parsers/u32_ops.rs
This PR cleans up code and comments in u32 operation parsers.
=> u32 assembly parser cleanup

assembly/src/parsers/u32_ops.rs
=> Update vm cycle count and fixes for u32 ops

core/src/lib.rs, core/src/operations/debug.rs, core/src/operations/mod.rs, core/src/operations/tests.rs, core/src/program/blocks/span_block.rs, processor/Cargo.toml, processor/src/lib.rs, processor/src/memory/mod.rs, processor/src/operations/decorators/debug_tests.rs, processor/src/operations/decorators/mod.rs, processor/src/operations/mod.rs, processor/src/stack/mod.rs
=> Add debug operations

processor/src/operations/u32_ops.rs, processor/src/tests/u32_ops/arithmetic_ops.rs
=> Add divide by 0 check

processor/src/tests/io_ops/adv_ops.rs, processor/src/tests/io_ops/constant_ops.rs, processor/src/tests/io_ops/env_ops.rs, processor/src/tests/io_ops/local_ops.rs, processor/src/tests/io_ops/mem_ops.rs, processor/src/tests/io_ops/mod.rs, processor/src/tests/mod.rs
=> test: add io ops integration tests to processor

assembly/src/parsers/mod.rs, assembly/src/parsers/stack_ops.rs, miden/tests/integration/operations/mod.rs, miden/tests/integration/operations/stack_ops.rs
Added the swapdw assembly instruction and a test for it in a new file stack_ops.rs
=> implement swapdw assembly instruction

miden/tests/integration/operations/field_ops.rs
Added arithmetic field operation integration tests to fix #165
=> tests: arithmetic field operation integration tests

docs/src/user_docs/main.md
Few links on top level page is broken
=> fix: fix user doc links

miden/tests/integration/stdlib/math/u64_mod.rs, stdlib/asm/math/u64.masm, stdlib/src/asm.rs
=> Add min and max procedures to u64 stdlib module 

miden/tests/integration/stdlib/math/u64_mod.rs, stdlib/asm/math/u64.masm, stdlib/src/asm.rs
=> Add overflowing shl and shr to u64 module in stdlib

core/src/program/blocks/span_block.rs
This PR refactors operation batching logic to make it easier to reason about.
=> Improve readability of operation batching code

processor/src/debug.rs, stdlib/asm/crypto/hashes/keccak256.masm, stdlib/src/asm.rs
Some lines were un-commented in keccak256.masm which should have been commented. Also includes a small typo fix.
=> small fixes

stdlib/asm/crypto/hashes/keccak256.masm, stdlib/src/asm.rs
Two more lines that had to be commented out which was causing issue #224. Sorry, I missed this during previous PR.
=> small fix closes #224

assembly/src/parsers/mod.rs, assembly/src/parsers/u32_ops.rs, core/src/operations/mod.rs, docs/src/user_docs/assembly/u32_operations.md, miden/tests/integration/operations/u32_ops/arithmetic_ops.rs, processor/src/operations/mod.rs, processor/src/operations/u32_ops.rs, stdlib/asm/math/u256.masm, stdlib/asm/math/u64.masm, stdlib/src/asm.rs
Addressing #220.      
- checks top three operands in stack if they are u32 or not
- returns the sum of top three elements in the form of hi & lo bits
- write integration tests for this new operation
=> feat(processor): introduce u32add3 instruction to core VM

docs/src/SUMMARY.md, docs/src/design/decoder/main.md, docs/src/design/programs.md, docs/src/user_docs/assembly/main.md
This PR adds description of how the decoder works to mdBook. This does not yet include description of AIR constraints.
=> Decoder docs

docs/src/design/aux_table/pow2.md
This PR addresses the rendering issue of pow2 auxiliary table.
=> docs(mdbook): fix rendering issue of pow2 aux table

air/src/aux_table/hasher/mod.rs, air/src/aux_table/mod.rs, air/src/lib.rs, docs/src/design/aux_table/hasher.md, processor/src/hasher/mod.rs
=> feat(air): add boundary constraint to hasher

Cargo.toml, examples/src/lib.rs, examples/src/main.rs, miden/Cargo.toml, miden/src/lib.rs, miden/tests/integration/helpers/mod.rs, prover/Cargo.toml, prover/src/lib.rs
This PR migrates prover code to an independent crate.
=> Create prover crate

assembly/src/parsers/field_ops.rs, miden/tests/integration/operations/field_ops.rs, stdlib/asm/math/u64.masm, stdlib/src/asm.rs
This PR address first part of #200.
=> Update pow2 assembly parser to use new procedure.

assembly/benches/script_compilation.rs, assembly/src/lib.rs, assembly/src/parsers/blocks.rs, assembly/src/parsers/mod.rs, assembly/src/procedures/mod.rs, assembly/src/tests.rs, core/src/lib.rs, core/src/operations/decorators/asmop_info.rs, core/src/operations/decorators/mod.rs, core/src/operations/mod.rs, miden/src/cli/data.rs, miden/src/examples/fibonacci.rs, miden/src/tools/mod.rs, miden/tests/integration/helpers/mod.rs, miden/tests/integration/main.rs, processor/benches/script_execution.rs, processor/src/decorators/mod.rs
Partly Addressing #137.
Adds a new decorator called AsmOp which provides debug related info about the script. This decorator is only added to the decorator list in debug mode.
=> feat(core): Add AsmOp decorator

miden/examples/fib/fib.inputs, miden/src/cli/data.rs, miden/src/cli/mod.rs, miden/src/cli/verify.rs, miden/src/tools/mod.rs
=> refactor(cli): miden cli improvements

CONTRIBUTING.md
This PR adds CONTRIBUTING.md to the root.
Related discussion issue #337.
=> community standards: add contributing guideline

CONTRIBUTING.md
Mini changes and suggestions to the contributing guideline.
=> docs: minor changes to the contributing guideline

air/Cargo.toml, air/benches/enforce_stack_constraint.rs, air/src/stack/mod.rs, air/src/stack/op_flags/mod.rs, air/src/stack/op_flags/tests.rs
This PR introduces a framework of stack operation's generic AIR constraints. New composite flags are introduced for generic constraints of all the stack operations.
=> Stack generic AIR constraints structure

air/src/stack/field_ops/mod.rs, air/src/stack/field_ops/tests.rs, air/src/stack/mod.rs, air/src/stack/system_ops/mod.rs, air/src/stack/system_ops/tests.rs, processor/src/operations/field_ops.rs
This PR introduces air constraints of the system and field logical operation.
=> field and system stack AIR constraints 

miden/src/cli/data.rs
Allow advice_tape inputs to cli
=> Add support for advice_tape input to cli

assembly/src/parsers/io_ops/mod.rs, core/src/inputs/mod.rs, core/src/operations/decorators/advice.rs, miden/tests/integration/operations/io_ops/adv_ops.rs, processor/src/advice/mod.rs, processor/src/decorators/mod.rs, processor/src/errors.rs, processor/src/stack/mod.rs
Implementation of advice tapes map, `adv_config` operation and `active_tape` concept
=> Advice provider refactoring

core/src/lib.rs, miden/tests/integration/stdlib/math/ext2.rs, miden/tests/integration/stdlib/math/mod.rs, stdlib/asm/math/ext2.masm, stdlib/docs/ext2_math.md, stdlib/src/asm.rs
This PR implements some operations in the extension field of degree 2 of our base field.
=> Extension of deg 2 operations in Miden assembly

docs/book.toml
Just added Polygon to our title in the docs. 
=> Add Polygon picture to docs

air/benches/enforce_stack_constraint.rs, air/src/stack/io_ops/mod.rs, air/src/stack/mod.rs, air/src/stack/op_flags/mod.rs, air/src/stack/overflow/mod.rs, air/src/stack/overflow/tests.rs, core/src/operations/mod.rs, docs/src/design/stack/main.md
Introduce stack overflow air constraints to the VM. It doesn't include the overflow table multi-set constraints.
=> stack overflow constraints

processor/src/range/mod.rs, processor/src/trace/mod.rs
This commit introduces `RangeCheckTraceTable`, a struct that will contain the 8bit lookups table for the range trace, and the combined length of the 8bits and 16bits tables.
Prior to this commit, the table was generated twice - first to calculate the `max_len`, and then to compute the trace.
From local benchmarks, this optimization improved the performance around ~3%, considering we no longer allocate the tables twice. However, the performance improvement could be mitigated by the compiler since he should be smart enough to understand that the table shouldn't be dropped before the second call to `into_trace`.
resolves #229
=> refactor(processor): add range check trace table

README.md
Last direct commit was not correct and had some errors.
=> docs: Fix README.md after adding two different documentation links

assembly/src/parsers/ast/context.rs, assembly/src/parsers/ast/io_ops.rs, assembly/src/parsers/ast/tests.rs, assembly/src/parsers/ast/u32_ops.rs
=> AST parser bug fix

assembly/src/parsers/ast/context.rs, assembly/src/parsers/ast/mod.rs, assembly/src/parsers/ast/tests.rs, stdlib/src/lib.rs
Nested and sequential `if` expression fix in AST parser.
=> AST if expression parsing fix

docs/src/intro/usage.md, miden/src/repl/mod.rs
This PR updates the docs with the repl cli and commands. 
=> Add Repl docs

miden/src/examples/mod.rs
This PR turns on logging in the example cli command. 
=> Enable logging in example cli command

assembly/src/parsers/ast/mod.rs, assembly/src/parsers/ast/serde/deserialization.rs, assembly/src/parsers/ast/serde/serialization.rs
Updated the ByteReader to work with slices rather than vectors. Also, fixed a minor typo in the serializer. Please review it to see if this works, or if I would have to make some additional changes.
Resolves #462 
=> fix(assembly): Optimized ByteReader serializer

assembly/src/parsers/ast/mod.rs, assembly/src/parsers/ast/tests.rs
=> assembly(feat): change proc map to vec

docs/src/design/decoder/constraints.md
colum -> column
ref: https://github.com/maticnetwork/miden/pull/504
=> docs: fix typo in constraints.md

CHANGELOG.md
This PR adds an initial changelog using the information from the past 2 releases and a draft of updates for v0.3 (not yet released).
Please let me know what other things you think should be included in the v0.3 release notes. I didn't include info about the new assembler changes yet - I'm not sure which things you want to add in.
=> Add changelog for v0.1.0 - v0.3.0

assembly/src/assembler/instruction/procedures.rs, assembly/src/assembler/mod.rs, assembly/src/assembler/tests.rs, assembly/src/errors.rs
=> refactor: use refcell for mut access to procedures cache

assembly/src/parsers/mod.rs
Tiny PR to add `Clone` to `ProgramAst` struct.
=> Add Clone to ProgramAst

miden/Cargo.toml, miden/src/cli/run.rs, miden/tests/integration/cli/cli_test.rs, miden/tests/integration/cli/mod.rs, miden/tests/integration/main.rs, processor/src/trace/mod.rs
Closing #442. Tests are missing, need some input on how to test CLI best. 
=> Print vm cycles after cli execution

assembly/src/assembler/instruction/adv_ops.rs, assembly/src/assembler/instruction/field_ops.rs, assembly/src/assembler/instruction/mem_ops.rs, assembly/src/assembler/instruction/mod.rs, assembly/src/assembler/instruction/u32_ops.rs, assembly/src/parsers/adv_ops.rs, assembly/src/parsers/field_ops.rs, assembly/src/parsers/io_ops.rs, assembly/src/parsers/mod.rs, assembly/src/parsers/u32_ops.rs, core/src/utils/mod.rs
Fixes #535 
Currently added the Range queries in the assembly. I have just changed two of those functions. Please do update if I'll have to make any more changes here, or any corrections to these functions. 
And, Sorry I took a long time to create this PR.
=> fix(assembly): Added Range queries for interval checks

assembly/src/parsers/mod.rs, core/src/outputs.rs, processor/src/chiplets/bus/mod.rs, prover/src/lib.rs
random assortment of changes done while I was reading the code
- typo fix
- runtime check for documented property
- type alias for cycle (idea is to move to a unit-type for better documentation and type safety)
- using `all` to make code a bit more idiomatic
=> Assorted changes

assembly/src/parsers/context.rs, assembly/src/parsers/io_ops.rs
=> Caller is a simple instruction

docs/src/design/programs.md
I'm not sure if "attempt to" or "try to" has any meaning in the context of program execution but if not then it may be good to remove them to make the passage clearer.  This PR removes the instances of this language in the example program execution description.
=> docs: program docs update

miden/tests/integration/stdlib/mem.rs, miden/tests/integration/stdlib/mod.rs, stdlib/asm/mem.masm, stdlib/docs/mem_std.md
This utility is extracted from https://github.com/0xPolygonMiden/miden-base/pull/26 .
=> Add std::mem::memcopy

assembly/src/assembler/instruction/mem_ops.rs, assembly/src/assembler/instruction/mod.rs
mem write without immediate address is pretty straightforward, this makes it easier to count the number of cycles when looking at the code, and removes the `unreachable!()` branch.
=> Simplified handling of write instrucitons

miden/tests/integration/stdlib/crypto/falcon.rs, miden/tests/integration/stdlib/crypto/keccak256.rs
This fixes the warnings like the ones below:
=> Fix cargo check warnings

verifier/src/lib.rs
Fixes https://github.com/0xPolygonMiden/miden-vm/issues/680
=> Re-export all relevant structs in verifier-crate

assembly/src/assembler/mod.rs
This tiny PR fixes a clippy issue with the latest nightly build.
=> Fix clippy error

docs/src/intro/usage.md
=> add docs for --output flag

core/src/program/blocks/call_block.rs, core/src/utils/mod.rs, processor/src/advice/mem_provider.rs, processor/src/decorators/mod.rs, processor/src/errors.rs
This allows the use of ExecutionError as a trait object `dyn Error`.
=> impl error for executionerror

.github/workflows/ci.yml, Makefile, miden/Cargo.toml, processor/Cargo.toml, processor/src/lib.rs
This PR introduces the `internals` feature flag
=> feat(processor): introduce internals flag

assembly/src/parsers/io_ops.rs, assembly/src/parsers/u32_ops.rs, assembly/src/procedures/mod.rs
This replaces some casts with fallible and infallible code. The advantage here is that one doesn't have to worry about data being truncated.
I didn't find any issues with the code, the transformation is mostly to make auditing easier.
=> Replace casting with fallible conversions

miden/src/cli/debug/command.rs, miden/src/cli/debug/executor.rs, miden/src/cli/debug/mod.rs
=> feat: improve ux of debug cli

docs/src/user_docs/assembly/flow_control.md
I'm not sure if this is documented elsewhere. It is nice to have a sentence about it.
=> Repeat unrolling documentation

CHANGELOG.md
Instructions added by https://github.com/0xPolygonMiden/miden-vm/pull/734 and https://github.com/0xPolygonMiden/miden-vm/pull/738
=> Instructions changelog

assembly/src/parsers/context.rs
I didn't read too much the code, just noticed some of the expect strings are referring to the wrong expected value. I didn't try to remove the expects.
=> Fix parser expect messages

processor/src/chiplets/hasher/trace.rs
It is not necessary to track the changes to the `row_addr` column during the runtime, it is sufficient to construct the column when the trace is being filled. This is because the value of the column can be inferred from the any of the other columns in the hasher.
The advantage here is that the HasherTrace is slightly simpler, one fewer attribute. And the column can be allocated and filled with a single loop, which should be more efficient
=> Delay row addr column construction

CHANGELOG.md, miden/src/tools/mod.rs
=> Renamed ProgramInfo to ExecutionDetails 

.git-blame-ignore-revs
the pre-commit PR has been merged, this adds the commit that ran pre-commit and formated the code base into the [`.git-blame-ignore-revs`](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file)
=> Ignore pre commit rev

assembly/src/assembler/instruction/crypto_ops.rs, core/src/lib.rs, docs/src/intro/overview.md, miden/src/lib.rs, miden/tests/integration/air/chiplets/hasher.rs, miden/tests/integration/helpers/crypto.rs, miden/tests/integration/helpers/mod.rs, miden/tests/integration/main.rs, miden/tests/integration/operations/crypto_ops.rs, miden/tests/integration/operations/io_ops/adv_ops.rs, miden/tests/integration/operations/io_ops/mod.rs, miden/tests/integration/stdlib/crypto/fri/channel.rs, miden/tests/integration/stdlib/crypto/fri/mod.rs, miden/tests/integration/stdlib/crypto/fri/verifier_fri_e2f4.rs, processor/src/advice/inputs.rs, processor/src/advice/mem_provider.rs, processor/src/advice/mod.rs, processor/src/chiplets/hasher/tests.rs, processor/src/decorators/mod.rs, processor/src/errors.rs, processor/src/lib.rs, processor/src/operations/crypto_ops.rs, processor/src/trace/tests/chiplets/hasher.rs, processor/src/trace/tests/hasher.rs, prover/src/lib.rs
=> feat: add miden-crypto merkle store as advice provider backend

miden/tests/integration/stdlib/crypto/fri/mod.rs, processor/src/advice/mem_provider.rs, processor/src/errors.rs
=> refactor: remove unused processor error variants

docs/src/user_docs/assembly/field_operations.md
Prior to this PR:
After this PR:
=> docs: formatting is_odd as the other ops

CHANGELOG.md, README.md, core/src/utils/mod.rs, docs/src/intro/main.md, docs/src/intro/usage.md, prover/src/lib.rs
This PR does minor cleanup for v0.5.0 release.
=> Minor cleanup before v0.5.0 release

docs/src/intro/usage.md
Update the usage CLI documentation with information about types of inputs
=> Add inputs to the usage docs

miden/tests/integration/operations/crypto_ops.rs, processor/src/operations/crypto_ops.rs, test-utils/src/lib.rs
And updated a test to use RPO state.
=> Added documentation for `build_expected_perm`

Makefile, processor/src/lib.rs, prover/Cargo.toml, prover/src/gpu.rs, prover/src/lib.rs
GPU acceleration of Rpo256 trace commitments on Apple Silicon devices.
=> GPU accelerate RPO trace commitments

stdlib/tests/crypto/stark/mod.rs, stdlib/tests/crypto/stark/verifier_recursive/mod.rs
A small change for readability sake.
=> Returning struct instead of tuple

docs/src/design/decoder/constraints.md, docs/src/design/stack/op_constraints.md
This PR adds documentation for the extra register constraints in the decoder and stack constraints sections.
=> Add documentation for the extra register constraints

docs/src/user_docs/assembly/field_operations.md
=> docs: document stack state for ext2 instructions

assembly/src/parsers/mod.rs
typo fix: MAX_LOCL_PROCS -> MAX_LOCAL_PROCS
=> fix: minor typo fix

core/src/random.rs, stdlib/asm/crypto/stark/random_coin.masm
=> Change implementation of Proof-of-Work in RpoRandomCoin

stdlib/asm/crypto/stark/constants.masm, stdlib/asm/crypto/stark/random_coin.masm
This adds a little bit of documentation to `generate_z_zN`
=> verifier: document generate_z_zN

core/src/operations/mod.rs, docs/src/user_docs/assembly/stack_manipulation.md, processor/src/operations/stack_ops.rs
The instruction was only mentioned in the design docs, added missing user docs.
=> docs: add documentation for `swapdw`

docs/src/design/stack/main.md
this just removed one unnecessary word
=> docs: small word fix

docs/src/user_docs/assembly/code_organization.md
This PR adds a new paragraph for the constant value description.
=> Constant value docs hotfix

docs/src/design/decoder/constraints.md
This PR fixes 3 small errors in the decoder documentation found during review of #1065
=> Minor fixes to the decoder constraint documentation

docs/src/design/decoder/main.md, processor/src/range/aux_trace.rs, processor/src/range/mod.rs
Fixes a few typos related to LogUp
=> Minor doc fix LogUp

processor/src/host/advice/inputs.rs
This PR introduces an `extend` method on `AdviceInputs` that allows for the extension of the instance using another isntance.
=> `AdviceInputs` extend

stdlib/tests/collections/mmr.rs
After [this PR](https://github.com/0xPolygonMiden/crypto/pull/230) from the crypto repository has been merged, some of the stdlib tests start to fail. This small PR fixes these tests.
=> Hotfix for the stdlib tests

air/src/lib.rs, air/src/proof.rs, core/src/stack/inputs.rs, core/src/stack/outputs.rs
Implements serializable and deserializable for execution proof (dependency to make ProvenTransaction serializable)
=> ExecutionProof: impl Serializable & Deserializable

assembly/src/assembler/context.rs, assembly/src/assembler/mod.rs, assembly/src/errors.rs, assembly/src/lib.rs, core/src/errors.rs, core/src/program/info.rs, core/src/program/mod.rs, core/src/program/tests.rs, processor/src/chiplets/kernel_rom/tests.rs, processor/src/chiplets/tests.rs, processor/src/decoder/tests.rs
Added validation and some simplifications.
=> Kernel serde

docs/src/user_docs/assembly/field_operations.md
This small PR adds a brief explanation of field arithmetic and should close #1186.
=> Explanation of field arithmetic

air/src/trace/main_trace.rs, processor/src/chiplets/aux_trace/mod.rs, processor/src/decoder/auxiliary.rs, processor/src/stack/aux_trace.rs, processor/src/stack/overflow.rs, processor/src/trace/mod.rs, processor/src/trace/tests/stack.rs, processor/src/trace/utils.rs
Introduces a trait for auxiliary column build. 
=> Trait for auxiliary column build

stdlib/build.rs
Motivation: https://github.com/0xPolygonMiden/miden-vm/issues/1208
I'm not sure if this will fix the issue, but I guess it is worth giving it a try.
=> Stdlib build: Only delete out folder contents, not the folder itself

processor/src/operations/comb_ops.rs
Fixes a bug due to not copying previous stack state in `RCOMBBASE`.
=> Bug fix for `RCOMBBASE`

air/src/constraints/chiplets/hasher/mod.rs, air/src/constraints/chiplets/memory/mod.rs, air/src/constraints/stack/mod.rs, core/Cargo.toml, core/src/lib.rs, core/src/operations/decorators/advice.rs, processor/src/host/advice/injectors/smt.rs, processor/src/host/advice/mod.rs
Follow-up to: https://github.com/0xPolygonMiden/crypto/pull/277
=> Removes any remnants of `TieredSmt`

README.md, docs/src/background.md
=> Fix broken links

CHANGELOG.md
Add changelog line requested at https://github.com/0xPolygonMiden/miden-vm/pull/1271
=> Changelog for crate rename

assembly/src/ast/parsers/constants.rs
=> refactor: fix typo in constants.rs

docs/src/design/lookups/main.md
Found a broken link while reading the VM's documentation. Checked on discord to see [where it should point to](https://discord.com/channels/893151281848406016/1114419272165376030/1220616524365303808).
=> docs: fix multiset link in design section

docs/src/user_docs/assembly/execution_contexts.md
=> docs: update execution context docs to mention dyncall

CHANGELOG.md, air/Cargo.toml, assembly/Cargo.toml, assembly/src/errors.rs, core/Cargo.toml, core/src/errors.rs, miden/Cargo.toml, processor/Cargo.toml, processor/src/errors.rs, prover/Cargo.toml, stdlib/Cargo.toml, verifier/Cargo.toml, verifier/src/lib.rs
=> Ensure all errors implement at least `Debug`, `Clone`, `PartialEq` and `Eq` traits

processor/src/trace/virtual_bus/circuit/prover.rs, processor/src/trace/virtual_bus/circuit/verifier.rs, processor/src/trace/virtual_bus/sum_check/prover/mod.rs
=> Fix problem 

.git-blame-ignore-revs, CHANGELOG.md, README.md, air/Cargo.toml, air/src/options.rs, assembly/Cargo.toml, core/Cargo.toml, docs/src/intro/main.md, docs/src/intro/usage.md, docs/src/user_docs/assembly/field_operations.md, miden/Cargo.toml, processor/Cargo.toml, processor/src/chiplets/aux_trace/mod.rs, processor/src/errors.rs, processor/src/host/mod.rs, processor/src/lib.rs, processor/src/operations/comb_ops.rs, prover/Cargo.toml, stdlib/Cargo.toml, test-utils/Cargo.toml, verifier/Cargo.toml, verifier/src/lib.rs
This PR resolves the conflicts between `main` and `next` branches, creating a merge commit.
=> Merge `main` branch into `next`

miden/src/examples/fibonacci.rs, miden/src/examples/mod.rs, prover/src/gpu/metal/mod.rs
Pick up https://github.com/0xPolygonMiden/miden-vm/pull/1281 and rebase from next, credit goes to @cf
=> Fix segment page alignment issue in metal prover

CHANGELOG.md, air/src/lib.rs, miden/src/examples/fibonacci.rs, miden/src/examples/mod.rs, prover/Cargo.toml, prover/src/gpu/metal/mod.rs, prover/src/gpu/metal/tests.rs
Before this can be merged, it is required for miden-gpu [PR](https://github.com/0xPolygonMiden/miden-gpu/pull/2) to be merged as well.
=> fix: update metal codebase to adjust it to 0.9 version of crates

docs/src/design/chiplets/bitwise.md, docs/src/design/chiplets/hasher.md, docs/src/design/chiplets/kernel_rom.md, docs/src/design/chiplets/main.md, docs/src/design/range.md
Hello
While looking through your docs I fixed several spelling issues.
Br, Elias.
=> Fix spelling issues

CHANGELOG.md, processor/src/chiplets/aux_trace/mod.rs, processor/src/trace/tests/hasher.rs
=> Fix chiplets vtable construction

processor/src/chiplets/aux_trace/mod.rs
=> Simplify requests hasher chiplet

miden/src/examples/blake3.rs, processor/src/decoder/aux_trace/mod.rs
Needed to truncate the stack as per @bobbinth suggestion. Also the block stack table has a bug and is not summing to 0 so I have removed the assertion for now.
=> Fix Blake example

CHANGELOG.md, miden/tests/integration/flow_control/mod.rs, processor/src/chiplets/aux_trace/mod.rs, processor/src/chiplets/mod.rs, processor/src/trace/utils.rs
Closes #1545
I also confirmed that `miden-base` tests pass.
=> Fix kernel ROM multiset check

miden/README.md
=> fix: fix typo in README

miden/Cargo.toml
Addresses https://github.com/0xPolygonMiden/miden-vm/pull/1587#discussion_r1866168366
=> fix: fix miden-vm Cargo.toml

docs/src/intro/overview.md
=> Fix overview.md document

CHANGELOG.md, air/src/trace/chiplets/hasher.rs, air/src/trace/chiplets/mod.rs, air/src/trace/mod.rs
=> Fix docs on layout of auxiliary segment trace

miden/src/cli/run.rs
=> Always load advice provider in run command

CHANGELOG.md, Cargo.lock, air/src/lib.rs, stdlib/Cargo.toml, stdlib/asm/crypto/stark/constants.masm, stdlib/asm/crypto/stark/public_inputs.masm, stdlib/asm/crypto/stark/random_coin.masm, stdlib/asm/crypto/stark/utils.masm, stdlib/asm/crypto/stark/verifier.masm, stdlib/tests/crypto/stark/mod.rs, stdlib/tests/crypto/stark/verifier_recursive/mod.rs
=> Add kernel procedures to public inputs

assembly/src/ast/tests.rs, assembly/src/testing.rs, assembly/src/tests.rs
=> Fix `assert_diagnostic_lines!`

CHANGELOG.md, Makefile, miden/src/tools/mod.rs
=> Add `executable` feature to `make test` and `make test-build`

air/src/trace/rows.rs, assembly/src/ast/instruction/print.rs, assembly/src/ast/invocation_target.rs, assembly/src/ast/procedure/alias.rs, assembly/src/sema/context.rs, assembly/src/testing.rs, core/src/mast/mod.rs, core/src/mast/serialization/info.rs, core/src/operations/decorators/mod.rs, core/src/stack/inputs.rs, core/src/stack/outputs.rs, miden/benches/program_execution.rs, miden/src/cli/bundle.rs, miden/src/cli/data.rs, miden/src/cli/debug/command.rs, miden/src/cli/debug/executor.rs, miden/src/cli/debug/mod.rs, miden/src/cli/prove.rs, miden/src/repl/mod.rs, miden/src/tools/mod.rs, package/src/package/mod.rs, stdlib/tests/collections/mmr.rs, stdlib/tests/mem/mod.rs, test-utils/src/lib.rs
Fix clippy due to the latest nightly compiler
=> Fix clippy

CHANGELOG.md, assembly/src/parser/grammar.lalrpop, processor/src/tests.rs
=> Assert: fix grammar and tests

assembly/src/assembler/instruction/mod.rs, assembly/src/compile.rs, assembly/src/diagnostics.rs, assembly/src/parser/mod.rs, assembly/src/tests.rs, miden/src/cli/data.rs
Fixes #1739 
@plafer please let me know if this was the intended direction. Happy to make edits if needed
=> feat: Abstract away the miette! macro

docs/src/user_docs/assembly/field_operations.md, docs/src/user_docs/assembly/u32_operations.md, scripts/check-changelog.sh
=> Fix assert documentation

CONTRIBUTING.md
Should be useful for future contributors.
cc @plafer
=> Comment about signing keys in `CONTRIBUTING.md`

CHANGELOG.md, assembly/src/assembler/mod.rs, assembly/src/testing.rs, miden/src/cli/data.rs, test-utils/src/lib.rs
=> chore: make `Assembler::source_manager()` be `Send + Sync`

CHANGELOG.md, assembly/src/assembler/mast_forest_builder.rs, core/src/advice/map.rs, core/src/mast/merger/mod.rs, processor/src/host/advice/errors.rs, processor/src/host/advice/mod.rs, processor/src/host/mod.rs, processor/src/lib.rs
=> chore(AdviceProvider): replace `SimpleAdviceMap` with `AdviceMap` & add `merge_advice_map`

miden-vm/tests/integration/cli/cli_test.rs
Adds better error reporting when running 
`cargo test --package miden-vm --test miden-cli cli::cli_test`.
=> Helpful error for CLI tests

CHANGELOG.md, processor/src/host/debug.rs
=> bugfix(`host::default::debug`): Fix stack debug issue (#1984)

CHANGELOG.md, processor/src/fast/mod.rs
Fixes (hopefully) the underflow issue described in https://github.com/0xMiden/miden-base/pull/1636#issuecomment-3127853384.
=> Processor underflow hotfix

docs/src/design/decoder/constraints.md, docs/src/design/decoder/main.md, docs/src/design/programs.md, processor/src/decoder/block_stack.rs, processor/src/decoder/mod.rs, processor/src/decoder/trace.rs, processor/src/fast/basic_block.rs, processor/src/fast/execution_tracer.rs, processor/src/fast/trace_state.rs, processor/src/lib.rs
Closes #2126. I think I haven't missed anything (?).
=> fix: complete rename Span -> Basic Block

CONTRIBUTING.md
Include a new paragraph with AI-generated PR policy
=> Add contribution guidelines against AI slop
